### ISSUE TITLE
足迹地图

### ISSUE THREAD

**Issue by cscny** [LIlGG/halo-theme-sakura#106]
希望大佬可以添加一个足迹地图功能

**Comment by LIlGG** [comment]
足迹地图倒是没有使用过。
可以详细介绍或者举例说明一下足迹地图的功能和实现么？？ 或者采用自定义页面能否实现？ 
不确定是否为大众化功能，所以有待讨论。

**Comment by cscny** [comment]
emm 应该是把jvectormap集成到主题中，然后地图上每个地点标记有一段旅行故事描述
大佬可以考虑以下
