### ISSUE TITLE
随机图

### ISSUE THREAD

**Issue by lexiaobei** [LIlGG/halo-theme-sakura#107]
请问下随机图的相册、分类、用户参数该如何填写？

**Comment by LIlGG** [comment]
参看 https://lixingyong.com/2021/01/05/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E#toc-head-18

**Comment by lexiaobei** [comment]
> 参看 https://lixingyong.com/2021/01/05/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E#toc-head-18

好的，感谢
