### ISSUE TITLE
无法导入！

### ISSUE THREAD

**Issue by niantoudeyisi** [LIlGG/halo-theme-sakura#108]
<img width="413" alt="屏幕截图 2021-01-16 223621" src="https://user-images.githubusercontent.com/52864219/104814819-c7095080-584b-11eb-8325-f48ddaecf17f.png">

**Comment by LIlGG** [comment]
这个不是主题的问题。看看你的后台日志里面有什么提示

**Comment by LIlGG** [comment]
问题很久没有回复，先关闭了哈，如果有需求可以再次打开
