### ISSUE TITLE
关于分类、标签页的bug

### ISSUE THREAD

**Issue by ShallowHui** [LIlGG/halo-theme-sakura#109]
如果在后台设置了分类、标签页的头部图片，那么在分类、标签页上点击一个具体的分类或者标签是显示不出来网页的，报500错误，我看了下打印日志，应该是模板引擎的问题。

**Comment by LIlGG** [comment]
使用的是 release 版本的 1.3.0 吗？？？ 你可以试一下下载一下开发版本的，看看还会不会出现这个问题 
![image](https://user-images.githubusercontent.com/31335418/105125874-66fafe80-5b18-11eb-9591-e7d52ac2f210.png)

**Comment by ShallowHui** [comment]
是的，我用的是release 版本的 1.3.0

**Comment by LIlGG** [comment]
> 是的，我用的是release 版本的 1.3.0

可以先试一下开发版本，看看是否仍旧存在这个问题

**Comment by mimajiushi** [comment]
1.3.1和开发版问题依旧
