### ISSUE TITLE
模板丢失。独立主题需要有index.php模板文件，子主题必须在style.css样式表中包含模板标头。

### ISSUE THREAD

**Issue by roryshanshan** [LIlGG/halo-theme-sakura#110]
halo-theme-sakura/styles | 模板丢失。独立主题需要有index.php模板文件，子主题必须在style.css样式表中包含模板标头。

**Comment by LIlGG** [comment]
本 sakura 分支版本基于 [halo](https://halo.run) ，并不是基于 WordPress 的。如果需要 WordPress 版本的，可以参看 https://github.com/mashirozx/Sakura
