### ISSUE TITLE
代码块中一行代码太长，内容会跑到框外去！

### ISSUE THREAD

**Issue by jiangqiang2020** [LIlGG/halo-theme-sakura#111]
另外，公告内容可以支持链接点击跳转么？

**Comment by LIlGG** [comment]
用的是最新版本的主题吗？？ 之前版本确实有代码过长会跑到框外的情况。但这个问题很早之前就已经修复了。
可以提供一个截图或者主题地址吗？
另外公告内容可以写 html。所以是支持链接点击跳转的

**Comment by jiangqiang2020** [comment]
> 用的是最新版本的主题吗？？ 之前版本确实有代码过长会跑到框外的情况。但这个问题很早之前就已经修复了。
> 可以提供一个截图或者主题地址吗？
> 另外公告内容可以写 html。所以是支持链接点击跳转的

好像用的去年十月底的版本，有这个问题，昨天更新了，没测。
公共是直接写html？我写的markdown。。。😄

**Comment by LIlGG** [comment]
> > 用的是最新版本的主题吗？？ 之前版本确实有代码过长会跑到框外的情况。但这个问题很早之前就已经修复了。
> > 可以提供一个截图或者主题地址吗？
> > 另外公告内容可以写 html。所以是支持链接点击跳转的
> 
> 好像用的去年十月底的版本，有这个问题，昨天更新了，没测。
> 公共是直接写html？我写的markdown。。。😄

评论这里是没有用 markdown 转换过的，但实际上 markdown 也就是 html，所以直接用 html 就行
