### ISSUE TITLE
部分数学公式渲染错误

### ISSUE THREAD

**Issue by LIlGG** [LIlGG/halo-theme-sakura#113]
能够正确渲染的数据公式如
```
$$
x = {-b \pm \sqrt{b^2-4ac} \over 2a}.
$$
```
无法正确渲染的公式如
```
$$\theta_{min} = \frac{x}{\alpha}$$
```

如果在 `{` 之前使用 `\` 即可解决。推测是由于 `{` 的转义原因

**Comment by LIlGG** [comment]
根据研究，属于 halo 后台保存 markdown 时， html 被分隔，暂时没有好的解决办法。除非使用前端渲染的方式，但官方已经有所计划 https://github.com/halo-dev/halo/issues/989

**Comment by gerayking** [comment]
可以自己接过来写一个前端渲染吗？

**Comment by ruibaby** [comment]
如果对此有强需求，可以尝试 Halo 1.5 并使用 Sakura 的 next 分支，在主题设置开启 Katex。

https://bbs.halo.run/d/2139-halo-150-alpha
