### ISSUE TITLE
社交网络部分能不能弄一个自定义链接和图标啊？

### ISSUE THREAD

**Issue by jiangqiang2020** [LIlGG/halo-theme-sakura#114]
偶然发现QQ邮箱有个邮我功能，想设置到这个位置，我又不想改代码，改了后面更新又得改，所以想官方支持这个功能。

**Comment by LIlGG** [comment]
emmm 现在不是有邮箱了吗

**Comment by jiangqiang2020** [comment]
> emmm 现在不是有邮箱了吗

现在这个邮箱，点击后会打开系统的邮箱软件再进行发邮件。QQ邮箱那个邮我可以直接打开一个发信窗口，方便很多啊。

**Comment by LIlGG** [comment]
emmm 好吧。 那我在 1.3.1 版本里面加一个自定义的社交属性吧
