### ISSUE TITLE
主题无法配置

### ISSUE THREAD

**Issue by li1753846989** [LIlGG/halo-theme-sakura#115]
1. halo后台点击主题配置保存按钮,报500
2. 数据库为mysql 5.7
3. 查看数据字段发现不存在
![image](https://user-images.githubusercontent.com/50787560/106230370-4d4d6b80-622a-11eb-97f8-c0e1c11aceba.png)

4. 疑似主题配置文件问题
5. 其他主题正常配置

**Comment by LIlGG** [comment]
这段日志不能体现什么。。 你使用的是最新版的主题吗？ halo 也要求是 1.3.2 + 版本的

**Comment by li1753846989** [comment]
halo信息
版本：1.4.3
数据库：MySQL 5.7.28-log
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
主题包名称为"halo-theme-sakura-master.zip",尝试过1.3.3.与1.3.4,但这两个版本都无法安装[缺主题配置文件]

**Comment by LIlGG** [comment]
> halo信息
> 版本：1.4.3
> 数据库：MySQL 5.7.28-log
> 运行模式：production
> User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
> 主题包名称为"halo-theme-sakura-master.zip",尝试过1.3.3.与1.3.4,但这两个版本都无法安装[缺主题配置文件]

嗯？？？我主题的最新版本是 1.3.0。

**Comment by LIlGG** [comment]
你可以考虑，删除目前有的主题，重新上传试试

**Comment by li1753846989** [comment]
重新下了这个仓库的1.3.0版本里的[halo-theme-sakura-master.zip]安装包

但还是无法提交
![image](https://user-images.githubusercontent.com/50787560/106240393-29e0eb80-623f-11eb-9d24-25472c295a59.png)

**Comment by LIlGG** [comment]
大概就是后台数据冲突或者什么的问题。以前有过的问题是会出现重复字段。。之前有用过本主题吗？

**Comment by li1753846989** [comment]
有,但安装前我把主题数据清除了

**Comment by LIlGG** [comment]
> 有,但安装前我把主题数据清除了

那就不该出现这个问题了啊。。加我 QQ 吧。 1103069291

**Comment by li1753846989** [comment]
加了
