### ISSUE TITLE
首页＂发现＂无法自定义

### ISSUE THREAD

**Issue by codesensi** [LIlGG/halo-theme-sakura#116]
![Screenshot_20210201-163135](https://user-images.githubusercontent.com/66196408/106433564-5600a480-64ab-11eb-9221-f0115b8b2f35.jpg)
如图，这里为啥写  ＂发现＂  这俩字？聚焦图不是可以自定义么？我也想自定义这里。么么哒～(^з^)-☆

**Comment by LIlGG** [comment]
不给

**Comment by codesensi** [comment]
> 不给

我看你是飘了，我40米的大刀已经给你备好了

**Comment by LIlGG** [comment]
> > 不给
> 
> 我看你是飘了，我40米的大刀已经给你备好了

来啊，来，砍死我，砍不死我请自尽

**Comment by codesensi** [comment]
> > > 不给
> > 
> > 
> > 我看你是飘了，我40米的大刀已经给你备好了
> 
> 来啊，来，砍死我，砍不死我请自尽

那我直接请你自尽吧
