### ISSUE TITLE
文章页不展示封面图片

### ISSUE THREAD

**Issue by Aerotheif** [LIlGG/halo-theme-sakura#117]
![截屏2021-02-03 上午10 47 00](https://user-images.githubusercontent.com/42369782/106690686-397c7d80-660d-11eb-934a-e0d1b9bf75dd.png)
![截屏2021-02-03 上午10 47 16](https://user-images.githubusercontent.com/42369782/106690692-3d100480-660d-11eb-881a-cd5263ac8971.png)
![截屏2021-02-03 上午10 47 26](https://user-images.githubusercontent.com/42369782/106690723-45683f80-660d-11eb-98e9-ff3c6337c02d.png)

**Comment by LIlGG** [comment]
可以发一下你的博客地址吗？我去看一下

**Comment by Aerotheif** [comment]
http://8.136.111.157

**Comment by LIlGG** [comment]
你用的是开发版本的吗？？如果不是的话试一下开发版的看看。。
另外可以把后端的 随机图 设置，截图给我看看吗

**Comment by Aerotheif** [comment]
![截屏2021-02-03 下午1 25 40](https://user-images.githubusercontent.com/42369782/106702558-80756d80-6623-11eb-81b2-0727fc430a0a.png)
![截屏2021-02-03 下午1 25 29](https://user-images.githubusercontent.com/42369782/106702561-82d7c780-6623-11eb-897d-b1954d7c164a.png)
打开随机图 封面图会展示随机图 即使已经设置了封面

**Comment by Aerotheif** [comment]
我这边图片用的七牛云

**Comment by LIlGG** [comment]
正常来说，你设置什么链接都没问题的。。看你上面展示的也没有什么问题。 你这个问题也确实很奇怪。

不行你加我 QQ 好友吧，等会儿我可以帮你远程看看。 1103069291
