### ISSUE TITLE
请问文章页面的知识共享署名这句话在哪里可以去掉呢？

### ISSUE THREAD

**Issue by wellmoonloft** [LIlGG/halo-theme-sakura#118]
就是这一句，嘿嘿

 知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议

**Comment by LIlGG** [comment]
删掉下图中对应位置的代码即可。

![image](https://user-images.githubusercontent.com/31335418/106976606-a7eb4800-6793-11eb-90db-b2ba8f236634.png)

但需要注意，手动删除主题代码会导致无法更新本主题。目前这个地方还没有设置来开关他，后续会考虑添加

**Comment by wellmoonloft** [comment]
收到，非常感谢
