### ISSUE TITLE
请问首页＂发现＂里面的内容可以定义某个分类目录吗？

### ISSUE THREAD

**Issue by wellmoonloft** [LIlGG/halo-theme-sakura#119]
作者安

因为我自己做了一个菜单叫做“新闻动态”，挂的是/categories/news
然后这个分类里面的文章不想在首页发现里面显示出来

请问是不是也要改主题样式呀？应该在哪里改呢？

**Comment by LIlGG** [comment]
Halo 下个版本会增加分类输入密码查看。也会增加是否显示在首页。因此在下个版本会实现

**Comment by wellmoonloft** [comment]
> Halo 下个版本会增加分类输入密码查看。也会增加是否显示在首页。因此在下个版本会实现

收到，非常感谢～
