### ISSUE TITLE
 Markdown转义字符$渲染错误

### ISSUE THREAD

**Issue by CShisan** [LIlGG/halo-theme-sakura#120]
不知道是我用法错误还是主题渲染问题    我用markdown写下的是`\$xxx`  但是主题渲染出来的却是斜体_xxx_

**Comment by LIlGG** [comment]
你好~经过测试转义是没有任何问题的。 你可以再检查一下

![image](https://user-images.githubusercontent.com/31335418/107146356-acc21e80-6982-11eb-9bba-74a434941050.png)

![image](https://user-images.githubusercontent.com/31335418/107146353-a633a700-6982-11eb-9409-2d2c99679432.png)

**Comment by CShisan** [comment]
首先我是这样写的(我应该没写错吧~~右边预览都是对得)
![微信截图_20210207203502](https://user-images.githubusercontent.com/55305718/107146549-037c2800-6984-11eb-9c2d-29bf759c6e04.png)
然后再刚进到页面的时候是这样的
![微信截图_20210207203243](https://user-images.githubusercontent.com/55305718/107146561-1bec4280-6984-11eb-983e-d8c4293254da.png)
然后接着变成这样
![微信截图_20210207203249](https://user-images.githubusercontent.com/55305718/107146575-29a1c800-6984-11eb-8432-e24d9ddc7b22.png)
最后变成这样
![微信截图_20210207203254](https://user-images.githubusercontent.com/55305718/107146580-30c8d600-6984-11eb-81ed-779d74b085fa.png)

**Comment by CShisan** [comment]
变成斜体的时候就是资源全部请求完的状态    缓存我已经禁用了

**Comment by LIlGG** [comment]
> 变成斜体的时候就是资源全部请求完的状态 缓存我已经禁用了

可以将你的代码片段发一下么？

**Comment by CShisan** [comment]
或许你可以进我[博客](https://blog.chisan.com)看看什么情况

**Comment by LIlGG** [comment]
> 或许你可以进我[博客](https://blog.chisan.com)看看什么情况

博客无法打开

**Comment by CShisan** [comment]
或许你可以进我[博客](https://blog.cshisan.com)看看什么情况

**Comment by CShisan** [comment]
> > 或许你可以进我[博客](https://blog.chisan.com)看看什么情况
> 
> 博客无法打开

少打了个字符

**Comment by CShisan** [comment]
> > 变成斜体的时候就是资源全部请求完的状态 缓存我已经禁用了
> 
> 可以将你的代码片段发一下么？

https://blog.cshisan.com/archives/vue%E7%88%B6%E5%AD%90%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1

**Comment by LIlGG** [comment]
> > > 变成斜体的时候就是资源全部请求完的状态 缓存我已经禁用了
> > 
> > 
> > 可以将你的代码片段发一下么？
> 
> https://blog.cshisan.com/archives/vue%E7%88%B6%E5%AD%90%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1

是不是添加了额外的插件？

**Comment by LIlGG** [comment]
BUG 的原因应该是，将 $ 符解析为了数学公式符号

**Comment by CShisan** [comment]
> BUG 的原因应该是，将 $ 符解析为了数学公式符号

那是我写法问题吗   还是什么原因   我刚尝试了把插件关掉好像还是这样

**Comment by CShisan** [comment]
> BUG 的原因应该是，将 $ 符解析为了数学公式符号

emmmm   是我这样写导致被解析成数学公式么

**Comment by LIlGG** [comment]
这可能是个普遍性的 BUG，属于数学公式和 markdown 语法的冲突，我正在想办法找一个比较适中的解决方法

**Comment by CShisan** [comment]
好的,谢谢   最后就是希望往后版本中可以加入自定义鼠标样式φ(゜▽゜*)♪

**Comment by LIlGG** [comment]
> 好的,谢谢 最后就是希望往后版本中可以加入自定义鼠标样式φ(゜▽゜*)♪

自定义鼠标样式还是比较困难的，因为要添加很多个图标文件。不过完全可以自己替换本地图标资源，这样也等于自定义鼠标样式了

**Comment by CShisan** [comment]
> > 好的,谢谢 最后就是希望往后版本中可以加入自定义鼠标样式φ(゜▽゜*)♪
> 
> 自定义鼠标样式还是比较困难的，因为要添加很多个图标文件。不过完全可以自己替换本地图标资源，这样也等于自定义鼠标样式了

好   没关系    我只是想在别人访问的时候变成我想要的样式   我本地改过了  谢谢大佬

**Comment by LIlGG** [comment]
> > > 好的,谢谢 最后就是希望往后版本中可以加入自定义鼠标样式φ(゜▽゜*)♪
> > 
> > 
> > 自定义鼠标样式还是比较困难的，因为要添加很多个图标文件。不过完全可以自己替换本地图标资源，这样也等于自定义鼠标样式了
> 
> 好 没关系 我只是想在别人访问的时候变成我想要的样式 我本地改过了 谢谢大佬

只要你本地改过了，别人访问的话应该也会访问你的样式

**Comment by CShisan** [comment]
> 只要你本地改过了，别人访问的话应该也会访问你的样式

哦  你说的修改主题哎   我说的修改电脑的 哈哈哈

**Comment by LIlGG** [comment]
。似乎没有特别完美的方法来整合这两个。目前只能采取如下方式来解决这个问题：
1. 更新之后，只有使用元数据 math = true 的文章才会开启 mathjax
2. 使用 class="no-math" 来防止误渲染非数学公式

**Comment by CShisan** [comment]
> 。似乎没有特别完美的方法来整合这两个。目前只能采取如下方式来解决这个问题：
> 
> 1. 更新之后，只有使用元数据 math = true 的文章才会开启 mathjax
> 2. 使用 class="no-math" 来防止误渲染非数学公式

好的👌
