### ISSUE TITLE
Mac上的safari浏览器菜单换行，手机上主题样式似乎有点问题

### ISSUE THREAD

**Issue by wellmoonloft** [LIlGG/halo-theme-sakura#121]
如图所示，在chrome下就是正常的，safari打开就变这样了

![image](https://user-images.githubusercontent.com/20944693/107169110-14668100-69f8-11eb-82f1-84154bd83fe4.png)

此外我设定了黑夜模式，但是在手机上用浏览器打开背景还是白色的，而且我主题色设置橙色，如下图，感觉样式没生效

![IMG_3979](https://user-images.githubusercontent.com/20944693/107169469-df0e6300-69f8-11eb-91cf-27e80bfbce8e.PNG)

**Comment by LIlGG** [comment]
1. 对于 safari 的支持确实不如 chrome。毕竟我主要使用 chrome 来开发，对于 safari 不太清楚怎么调试。
2. 移动端目前不支持更改主题。因此不会生效。但已经具有开发计划，详见 #97 
3. 主题色应该不会有太大的问题

**Comment by wellmoonloft** [comment]
移动端的主题色可能是有些问题的，你看我下面的图是用浏览器模拟的，左上角的图标是正常的主题色。
再看issues里面的第二张图，是用手机里面浏览器直接打开的，就是灰色的，我不知道是特例还是都存在这个问题。

![image](https://user-images.githubusercontent.com/20944693/107444215-21f54580-6b75-11eb-922f-d830fa322d53.png)
