### ISSUE TITLE
CDN地址里面缺少公安的图片

### ISSUE THREAD

**Issue by wellmoonloft** [LIlGG/halo-theme-sakura#122]
如下图所示，加速地址里面应该是少了公安那张png
![1612932426519](https://user-images.githubusercontent.com/20944693/107465922-3437a980-6b9e-11eb-9c4e-283c4c59ef8f.jpg)

**Comment by LIlGG** [comment]
了解。在 1.3.1 发布之后就会修复这个问题，感谢

**Comment by LIlGG** [comment]
1.3.1 版本已经发布，更新即可解决
