### ISSUE TITLE
安装最新版主题出现错误

### ISSUE THREAD

**Issue by Lilac-Dream** [LIlGG/halo-theme-sakura#125]
## 问题如图所示：
![image](https://user-images.githubusercontent.com/49761134/108499015-a3bd3f80-72e8-11eb-8d1b-51633252d263.png)

## 安装方式1：本地安装
通过本地上传安装最新版的主题，控制台会报错。主页右下角切换主题按钮也显示出不来。
![image](https://user-images.githubusercontent.com/49761134/108499031-ac157a80-72e8-11eb-9623-6f927d6886db.png)

## 安装方式2：远程安装
安装的主题没问题，但是不是最新版的主题（因为我发现作者大大您添加的class功能并没有生效）。

**Comment by LIlGG** [comment]
嗯。因为远程安装默认安装的是最新的发行版本。。
这个报错的原因可能与我上次开发的原因有关。。新添加了一个方法。但线上的工具类中没有。。
如果我现在发布 1.3.1 版本的话就不会有这个问题。
不过现在的话，你可以先在设置 其他里面 关闭使用 cdn

**Comment by Lilac-Dream** [comment]
嗯嗯

**Comment by JohnNiang** [comment]
我也看到这个错误了，似乎没有任何影响。

**Comment by LIlGG** [comment]
> 我也看到这个错误了，似乎没有任何影响。

嗯嗯 这个错误属于主题的错误。开发版本工具类中新增了一个函数方法，但默认调用的是 cdn 上的，所以会出现不存在的问题。将主题配置 `其他 -> 使用 CDN ` 关闭= 暂时就能解决。

但我看在 halo 讨论的那个 1.4.3 -> 1.4.4/1.4.5 的问题，我本地也复现过，会出现连接中断的问题。 而且我的主题会出现的频繁，尤其是在有大量文章的时候。 但在 1.4.3 版本是没有出现那种情况的。推测可能是由于超过了单次请求的数据大小导致被截断？

**Comment by LIlGG** [comment]
新版本已经发布，更新即可解决这个问题。
