### ISSUE TITLE
页面缺少元素

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#127]
#如图
![image](https://user-images.githubusercontent.com/43897062/108624310-2841c680-747f-11eb-810e-7827e3ee15d7.png)
<a href="https://blog.chenjaly.cn/">博客地址</a>

**Comment by CodeChenL** [comment]
#浏览器版本
![image](https://user-images.githubusercontent.com/43897062/108624328-43143b00-747f-11eb-9305-68bdcf5206b2.png)

**Comment by LIlGG** [comment]
不要使用 1.4.3 以上的 halo 版本。使用 1.4.3 版本以上的 halo 再使用本主题，就会出现这个 bug

**Comment by CodeChenL** [comment]
> 不要使用 1.4.3 以上的 halo 版本。使用 1.4.3 版本以上的 halo 再使用本主题，就会出现这个 bug

那后续会支持把

**Comment by LIlGG** [comment]
> > 不要使用 1.4.3 以上的 halo 版本。使用 1.4.3 版本以上的 halo 再使用本主题，就会出现这个 bug
> 
> 那后续会支持把

与当前主题无关，属于 Halo 的 BUG。等待修复即可。

也可以关注这个 issue 来了解进展

https://github.com/halo-dev/halo/issues/1270

**Comment by CodeChenL** [comment]
> > > 不要使用 1.4.3 以上的 halo 版本。使用 1.4.3 版本以上的 halo 再使用本主题，就会出现这个 bug
> > 
> > 
> > 那后续会支持把
> 
> 与当前主题无关，属于 Halo 的 BUG。等待修复即可。
> 
> 也可以关注这个 issue 来了解进展
> 
> [halo-dev/halo#1270](https://github.com/halo-dev/halo/issues/1270)

好的😀

**Comment by cetr** [comment]
@LIlGG 我的主题为啥正常🤔

**Comment by LIlGG** [comment]
> @LIlGG 我的主题为啥正常🤔

不知道。 但确实是后台的问题。而且在上面的 issue 里面，也提到了 Sagiri

**Comment by cetr** [comment]
> > @LIlGG 我的主题为啥正常🤔
> 
> 不知道。 但确实是后端的问题。而且在上面的 issue 里面，也提到了 Sagiri

我自用的和开源的不一样，源码什么的也不太一样，自用的没遇见问题，不知道开源的线上啥情况，哈哈

**Comment by LIlGG** [comment]
> > > @LIlGG 我的主题为啥正常🤔
> > 
> > 
> > 不知道。 但确实是后端的问题。而且在上面的 issue 里面，也提到了 Sagiri
> 
> 我自用的和开源的不一样，源码什么的也不太一样，自用的没遇见问题，不知道开源的线上啥情况，哈哈

🔪 幸灾乐祸的必须砍死
