### ISSUE TITLE
添加更新时间显示

### ISSUE THREAD

**Issue by wpengsen** [LIlGG/halo-theme-sakura#130]
因为很多文章都重新编辑过，感觉还是在文章列表页还有文章内容中，区分显示下发布时间与最后编辑时间比较好，望大佬采纳

**Comment by LIlGG** [comment]
已有计划。会增加文章字数、更新时间等。据上次更新天数等等。

**Comment by codesensi** [comment]
> 已有计划。会增加文章字数、更新时间等。据上次更新天数等等。

再顺便改改翻页啵，显示总文章数，当前第几页，每页多少文章，嘿嘿

**Comment by LIlGG** [comment]
> > 已有计划。会增加文章字数、更新时间等。据上次更新天数等等。
> 
> 再顺便改改翻页啵，显示总文章数，当前第几页，每页多少文章，嘿嘿

感谢投喂嗷。但改我是不会改的 这辈子都不可能的了

**Comment by codesensi** [comment]
> > > 已有计划。会增加文章字数、更新时间等。据上次更新天数等等。
> > 
> > 
> > 再顺便改改翻页啵，显示总文章数，当前第几页，每页多少文章，嘿嘿
> 
> 感谢投喂嗷。但改我是不会改的 这辈子都不可能的了

投喂只是为了和你击剑，但是你不改，那我就霸王硬上弓，折服你。

**Comment by wpengsen** [comment]
> > > > 已有计划。会增加文章字数、更新时间等。据上次更新天数等等。
> > > 
> > > 
> > > 再顺便改改翻页啵，显示总文章数，当前第几页，每页多少文章，嘿嘿
> > 
> > 
> > 感谢投喂嗷。但改我是不会改的 这辈子都不可能的了
> 
> 投喂只是为了和你击剑，但是你不改，那我就霸王硬上弓，折服你。

兄弟牛批

**Comment by LIlGG** [comment]
[[cim]()](https://github.com/LIlGG/halo-theme-sakura/commit/1f023c962026596794cdd8493ba51d92a35a5033)
close
