### ISSUE TITLE
代码块外框样式加载失败

### ISSUE THREAD

**Issue by kk140906** [LIlGG/halo-theme-sakura#131]
<img width="1858" alt="2021-02-23_194048" src="https://user-images.githubusercontent.com/23394525/108838777-10994800-760f-11eb-9d4e-eaa32c7d24dd.png">
如图所示，该方法执行失败，导致外框样式无法正常加载，注释掉该语句后，样式正常，该过程可复现。

不清楚注释掉该语句后对其他地方是否有影响，麻烦帮忙排查一下。

**Comment by LIlGG** [comment]
这是开发版本的 bug。因为这个方法目前正式版本的 cdn 里没有，所以会报错。
你可以将 `主题设置-其他-资源使用cdn` 关闭之后再试试

**Comment by LIlGG** [comment]
issue 许久未回复，先 close 了。如有问题可再次打开
