### ISSUE TITLE
数学公式渲染不出来

### ISSUE THREAD

**Issue by txcjhaz** [LIlGG/halo-theme-sakura#132]
1. 开启了mathjax插件
2. 文章设置了元数据

实际页面未加载mathjax （halo版本1.4.5）

**Comment by LIlGG** [comment]
有网址吗？？我看一下

**Comment by txcjhaz** [comment]
> 有网址吗？？我看一下

https://hglo.top/archives/ce-shi-shu-xue-gong-shi
![image](https://user-images.githubusercontent.com/32667852/109093473-5f4ffa80-7753-11eb-973e-4577812c6599.png)
![image](https://user-images.githubusercontent.com/32667852/109093494-6840cc00-7753-11eb-9cbf-f28d686127e6.png)

**Comment by LIlGG** [comment]
你使用的是开发版本的主题，目前开发版本静态资源与线上版本不一致。
关闭 `主题设置-其他-资源使用cdn` 之后再尝试

**Comment by txcjhaz** [comment]
可以了，谢谢

**Comment by txcjhaz** [comment]
![image](https://user-images.githubusercontent.com/32667852/109096469-8c52dc00-7758-11eb-9223-3e240fc3df16.png)
![image](https://user-images.githubusercontent.com/32667852/109096491-97a60780-7758-11eb-90cf-efb4c06f30d0.png)
再请问一下，这个\sum_{i=1}这种为啥不能正常渲染啊，halo预览它是可以渲染的 :)
https://hglo.top/archives/ce-shi-shu-xue-gong-shi

**Comment by LIlGG** [comment]
已知问题，markdown 功能冲突的原因。 $ 标签被提前解析过了，目前正在找解决方案，但以目前我了解的办法，解决的几率可能不大，最大的可能就是妥协。 #113

**Comment by txcjhaz** [comment]
有没有可能在解析markdown的时候跳过$$开头$$结尾的部分呢？

对于类似
$$
\sum_{i=1}_n
$$
我理解上应该可以跳过吧？

$\sum_{i=1}_n$ 这种不支持我觉得暂时没关系

**Comment by LIlGG** [comment]
> 有没有可能在解析markdown的时候跳过$$开头$$结尾的部分呢？
> 
> 对于类似
> $$
> \sum_{i=1}^n
> $$
> 我理解上应该可以跳过吧？
> 
> $\sum_{i=1}^n$ 这种不支持我觉得暂时没关系

我一周前测试过，属于 markdown 的两个额外功能之间的问题。今天下班之后我会在进行尝试一下。这两个功能是相互冲突的，虽然我可以更改其中的任意一个。但根据正常情况来说，假设改掉数学公式的渲染，将 $$ 改成其他的，但通用的就是 $$。同理其他的也是一样的，所以比较难处理

**Comment by LIlGG** [comment]
问题重复，先关闭此 issue，后续进展在 #113
