### ISSUE TITLE
如图，菜单在safari下错位了。

### ISSUE THREAD

**Issue by maolog** [LIlGG/halo-theme-sakura#135]
如图，菜单超过5个，第6个会换行。
![2021-02-25-10.50.28.png](https://yys.show/images/2021/02/25/2021-02-25-10.50.28.png)

**Comment by LIlGG** [comment]
主题版本是多少？

**Comment by maolog** [comment]
1.3.0

**Comment by LIlGG** [comment]
目前对 safari 的适配做的还不是很好。后续会进行优化的
