### ISSUE TITLE
关于公安备案

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#137]
请问公安备案在哪添加呢,只能看到工信部的备案
![image](https://user-images.githubusercontent.com/43897062/109377483-a500f480-7906-11eb-98fe-aa45582bce87.png)
![image](https://user-images.githubusercontent.com/43897062/109377488-afbb8980-7906-11eb-8ffe-829c14082267.png)

**Comment by LIlGG** [comment]
更新最新版本的主题即可
