### ISSUE TITLE
图库默认分组设置后只切换标签

### ISSUE THREAD

**Issue by Lilac-Dream** [LIlGG/halo-theme-sakura#138]
## Bug
在图库里面添加图片，如果分组的中间带有空格，会导致此分组内图片在访问页面的时候不显示。例如：”照 片“。

## 建议
能否在主题设置里面，添加一个选项，设置进入图库页面默认打开的分组，当前默认的分组是“全部”。

**Comment by LIlGG** [comment]
> 导致此分组内图片在访问页面的时候不显示

意思是不会在画廊页面显示吗？

建议确实可以考虑。但可以告诉我一下这么做的意义吗？？或者说你的想法，用在哪儿这种的。一般来说默认为全部我认为就已经足够了。

**Comment by Lilac-Dream** [comment]
### BUG
是的，不会显示出来，就因为分组带了个空格。

### 分组
默认是全部，会把不想直接展示出来的图片展示出来。

毕竟默认的分组，如果精致一下，图库的首页精致起来比杂乱好看嘛~

比如：九宫格图片，在一个图库里面展示才有意义，但是全部在这个页面就会把其他图库的图片都给拿过来插入进来，图片显得很乱~
嘿嘿，只是一个建议，如果作者大大您方便的话，希望可以添加一下~

**Comment by Lilac-Dream** [comment]
还有一个事情，希望作者大大看看是否能优化一下。
## 关于分类：
### 比如： 
一级目录 A
二级目录 B、C、D。（这三个目录都是在一级目录A里面）

假设目录 B、C、D里面都有文章。

“分类”里面（/categories页面），会显示标签“A”，但是会显示"A"没有任何文章，点进去也搜索不到任何文章，但是分类B、C、D里面都有文章，B、C、D都属于A里面。

### 修改这个问题的三个想法：
1. 文章分类中，直接不显示这种外层的标签。（外层的这个目录标签，文章也无法存到这个最外层目录里面，只能存到最低级的分类目录）
2. 所有标签内文章数量是0的，就不在分类目录显示出来了。
3. 分类目录查询的时候，能够显示所有子目录里面的内容。（难度好像很大~~~）

**Comment by LIlGG** [comment]
> ### BUG
> 是的，不会显示出来，就因为分组带了个空格。
> 
> ### 分组
> 默认是全部，会把不想直接展示出来的图片展示出来。
> 
> 毕竟默认的分组，图库的首页，如果精致起来比杂乱好看嘛~
> 
> 比如：九宫格图片，在一个图库里面展示才有意义，但是全部在这个页面就会把其他图库的图片都给拿过来插入进来，图片显得很乱~
> 嘿嘿，只是一个建议，如果作者大大您方便的话，希望可以添加一下~

了解了，这个功能将会在 1.3.2 考虑添加

**Comment by Lilac-Dream** [comment]
谢谢作者大大~你真棒~嘿嘿

**Comment by LIlGG** [comment]
> 还有一个事情，希望作者大大看看是否能优化一下。
> 
> ## 关于分类：
> ### 比如：
> 一级目录 A
> 二级目录 B、C、D。（这三个目录都是在一级目录A里面）
> 
> 假设目录 B、C、D里面都有文章。
> 
> “分类”里面（/categories页面），会显示标签“A”，但是会显示"A"没有任何文章，点进去也搜索不到任何文章，但是分类B、C、D里面都有文章，B、C、D都属于A里面。
> 
> ### 修改这个问题的三个想法：
> 1. 文章分类中，直接不显示这种外层的标签。（外层的这个目录标签，文章也无法存到这个最外层目录里面，只能存到最低级的分类目录）
> 2. 所有标签内文章数量是0的，就不在分类目录显示出来了。
> 3. 分类目录查询的时候，能够显示所有子目录里面的内容。（难度好像很大~~~）

关于这个的话，实际上分类目录查询，目前做了另外一种，不过是定制化给别人做的，实现了分类层级的那种情况。但样式不是很好看。后续会考虑该地方的优化

**Comment by Lilac-Dream** [comment]
噢噢，期待ing~

**Comment by Lilac-Dream** [comment]
作者大大，我这里出bug了~
设置图片默认展示分组，只是标签过去了，但是图片显示的还是全部。

**Comment by LIlGG** [comment]
> 作者大大，我这里出bug了~
> 设置图片默认展示分组，只是标签过去了，但是图片显示的还是全部。

emm 刚试了一下。似乎是。。可能是我限制了过滤条件的原因。。但不限制的话，加载途中点切换就会出现问题。。
后续再看看吧。今天可能没时间了

**Comment by Lilac-Dream** [comment]
嗯嗯，不急，辛苦了~

**Comment by Lilac-Dream** [comment]
作者大大~~请教一个问题~~
https://lixingyong.com/s/comment
这里留言板的一局话，md写法里面有这种格式吗？还是新建页面时候，用html写的呀？

**Comment by LIlGG** [comment]
> 作者大大~~ 请教一个问题~~
> https://lixingyong.com/s/comment
> 这里留言板的一句话，md写法里面有这种格式吗？还是新建页面时候，用html写的呀？

用 html 写的

**Comment by LIlGG** [comment]
2.0.0-Beta.2 版本已经修复此问题，此 issue 关闭。 #340
