### ISSUE TITLE
ipad的默认浏览器中菜单栏产生错位

### ISSUE THREAD

**Issue by lukeewin** [LIlGG/halo-theme-sakura#139]
版本号1.3.1中，在ipad的默认浏览器中菜单栏产生错位

**Comment by LIlGG** [comment]
有对应的图吗？目前博主手里没有 ipad，对于 ipad 方面的适配可能无法进行

**Comment by lukeewin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LIlGG/halo-theme-sakura"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午2:00
收件人:&nbsp;"LIlGG/halo-theme-sakura"<halo-theme-sakura@noreply.github.com&gt;;
抄送:&nbsp;"Luke Ewin"<2131672767@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LIlGG/halo-theme-sakura] ipad的默认浏览器中菜单栏产生错位 (#139)





 
有对应的图吗？目前博主手里没有 ipad，对于 ipad 方面的适配可能无法进行

**Comment by LIlGG** [comment]
刚刚发布了针对于 safari 的菜单修复，你可以更新一下 master 看看 ipad 的是否也是同样的问题

**Comment by parasomn1a** [comment]
我觉得他可能说的是这个：
这是在 ios 上的效果
![image](https://user-images.githubusercontent.com/22992947/112251991-36aa1a80-8c97-11eb-9e0b-601c0ae12fb4.png)
这是在安卓上的效果
![image](https://user-images.githubusercontent.com/22992947/112252413-0b73fb00-8c98-11eb-8e5d-e36a336051b9.png)

**Comment by LIlGG** [comment]
> 我觉得他可能说的是这个：
> 这是在 ios 上的效果
> ![image](https://user-images.githubusercontent.com/22992947/112251991-36aa1a80-8c97-11eb-9e0b-601c0ae12fb4.png)
> 这是在安卓上的效果
> ![image](https://user-images.githubusercontent.com/22992947/112252413-0b73fb00-8c98-11eb-8e5d-e36a336051b9.png)

原来是这样的问题吗？？这个我没有 ipad 似乎不好调整。。。

**Comment by LIlGG** [comment]
BUG 记录一下，后续有机会我再进行修补吧 🤪

**Comment by parasomn1a** [comment]
这个问题最奇葩的地方是使用 chrome f12 选择 iphonex 却是好的，在真机上就错位了

**Comment by LIlGG** [comment]
> 这个问题最奇葩的地方是使用 chrome f12 选择 iphonex 却是好的，在真机上就错位了

现在的手机、浏览器什么的种类太多了。。部分情况下总会出现各种问题。。其实这种少部分的细节问题可以暂时忽略掉我感觉

**Comment by LIlGG** [comment]
> 这个问题最奇葩的地方是使用 chrome f12 选择 iphonex 却是好的，在真机上就错位了

不过 chrome 模拟的肯定不标准，他并没有实际的手机内核
