### ISSUE TITLE
第一屏大图无法显示

### ISSUE THREAD

**Issue by qinbo1022** [LIlGG/halo-theme-sakura#142]
大佬你好，我这碰到一个问题，初步估计可能是nginx没配好导致的，情况是部署之后首页背景图无法显示，但是点击归档页面再回到首页又可以显示了，后台和前台console没有报错，检查了两天没有找到原因，架构是在docker部署的halo，然后nginx代理的二级域名和https，大佬能帮忙看看嘛？地址https://my.abo.life

**Comment by LIlGG** [comment]
恕我直言，我也没看懂。 你的网页请求会被截断。而且请求的异常慢，甚至我的 CDN 也跟着一起慢。这种情况我也是第一次看到。
但点击归档再返回首页确实可以显示了。而且速度回到了正常情况。
你的 nginx 是否配置了限流？使用其他主题有没有这种情况？

**Comment by qinbo1022** [comment]
没有配置限流，使用其他主题没有这个问题，我的另一个二级域名下面如果也用这个主题的话也会出现同样问题，nginx配置如下
server {
    listen       80;

    listen 443 ssl;
    ssl_certificate ssl/main.crt;
    ssl_certificate_key ssl/main.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;

    server_name  my.abo.life;
    client_max_body_size 10m;
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript applic
ation/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    location / {
        proxy_pass http://172.17.0.16:8002;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

**Comment by Lilac-Dream** [comment]
这个问题好像是我之前在halo提问的问题呀，1.4.4和1.4.5版本的bug，halo更新到1.4.6最新版就好了吧？

**Comment by LIlGG** [comment]
> 这个问题好像是我之前在halo提问的问题呀，1.4.4和1.4.5版本的bug，halo更新到1.4.6最新版就好了吧？

但是如果是 1.4.4 和 1.4.5 的bug，似乎在控制台会有报错。但他这个并没有出现报错的问题。。

**Comment by qinbo1022** [comment]
我尝试更新一下1.4.6

**Comment by Lilac-Dream** [comment]
不不不，不是一定会报错的，我之前就是这样。

**Comment by Lilac-Dream** [comment]
我喜欢上他页面最下面的统计人数了……嘿嘿……

**Comment by Lilac-Dream** [comment]
![image](https://user-images.githubusercontent.com/49761134/110430962-194a4d80-80e8-11eb-985e-48b2d4944d50.png)

**Comment by qinbo1022** [comment]
哈哈哈 疯狂暗示

**Comment by Lilac-Dream** [comment]
嘿嘿~(手动滑稽狗头）

**Comment by qinbo1022** [comment]
感谢LIlGG和梦梦，问题解决，升级1.4.6就好了

**Comment by LIlGG** [comment]
> 嘿嘿~(手动滑稽狗头）

后面会加上的。。

**Comment by LIlGG** [comment]
> 感谢LIlGG和梦梦，问题解决，升级1.4.6就好了

原来确实是因为 1.4.4 和 1.4.5 的问题。。 我以为肯定会报错

**Comment by qinbo1022** [comment]
前后端都没报错 就很难排查了

**Comment by Lilac-Dream** [comment]
> > 嘿嘿~(手动滑稽狗头）
> 
> 后面会加上的。。

嘿嘿嘿，作者大大真棒！（撒花撒花）

**Comment by LIlGG** [comment]
问题解决了吧？那 issue 我就关闭了。有问题可以再次打开

**Comment by qinbo1022** [comment]
> 问题解决了吧？那 issue 我就关闭了。有问题可以再次打开

是的，感谢大大
