### ISSUE TITLE
主题编辑器样式问题

### ISSUE THREAD

**Issue by wuyan-ling** [LIlGG/halo-theme-sakura#145]
在vscode里面的代码样式复制到文章里面，样式就变了。主要空格很不正常，这是啥原因啊？
![image](https://user-images.githubusercontent.com/33196182/111870882-1e4dad80-89c2-11eb-9a0b-80c83e11dc5a.png)

请问一下有啥解决方法嘛？

**Comment by LIlGG** [comment]
这种很正常。你在后台手动更改就行了。

**Comment by wuyan-ling** [comment]
> 这种很正常。你在后台手动更改就行了。

怎么手动更改。有快速的方法？我暂时没找到，要一个个手动删除好累啊。可以请教一下嘛

**Comment by LIlGG** [comment]
> > 这种很正常。你在后台手动更改就行了。
> 
> 怎么手动更改。有快速的方法？我暂时没找到，要一个个手动删除好累啊。可以请教一下嘛

有的编辑器会附带格式，你可以从 vscode 里，先复制到其他的编辑器，比如 txt 文本里，然后再从其他的编辑器复制到博客里。 我没有试过 vscode 直接复制，所以也不是很了解。
