### ISSUE TITLE
关闭左下方音乐浮动后，左下角仍会出现播放器

### ISSUE THREAD

**Issue by parasomn1a** [LIlGG/halo-theme-sakura#150]
如题
![image](https://user-images.githubusercontent.com/22992947/112720908-0f27ac00-8f3c-11eb-848a-18860587b5ab.png)

![image](https://user-images.githubusercontent.com/22992947/112720918-1f3f8b80-8f3c-11eb-9d8b-b7ef3e8cd84e.png)

**Comment by LIlGG** [comment]
刚刚试了一下，确实存在这个问题。

**Comment by parasomn1a** [comment]
已经再改了，马上PR

**Comment by LIlGG** [comment]
> 已经再改了，马上PR

哈哈 效率呀。可怜我刚刚才加班回来 一身疲惫。
