### ISSUE TITLE
样式加载错误

### ISSUE THREAD

**Issue by SusurHe** [LIlGG/halo-theme-sakura#152]
我的style.css文件无法加载
有大佬知道是什么原因么
```
GET http://*****/styles/style.min.css?ver=1.3.1 net::ERR_ABORTED 404 (Not Found)
```
![image](https://user-images.githubusercontent.com/51081799/112972549-f3faad80-9182-11eb-9ae2-f90aa2c56d95.png)

**Comment by LIlGG** [comment]
试试开启或者关闭这个

![image](https://user-images.githubusercontent.com/31335418/112972994-6e2b3200-9183-11eb-9510-b89270c0f413.png)
