### ISSUE TITLE
希望支持文章浏览时自动收起导航栏的功能

### ISSUE THREAD

**Issue by bigcoder84** [LIlGG/halo-theme-sakura#153]
希望支持文章浏览时自动收起导航栏的功能，现在导航栏高度太高，有点影响阅读体验
![image](https://user-images.githubusercontent.com/41669762/113137638-5de48700-9257-11eb-9d45-554769dfa6ae.png)

**Comment by LIlGG** [comment]
非常感谢。很不错的建议~向下滚动阅读文章的时候确实应该收缩起来。
