### ISSUE TITLE
视频文章的优化

### ISSUE THREAD

**Issue by PandaQ1** [LIlGG/halo-theme-sakura#16]
![20200711-1](https://user-images.githubusercontent.com/27286999/87217596-8f41bd80-c37d-11ea-9123-af5116d64059.png)
PC端发布视频文章，视频位置似乎不在居中的位置，麻烦大佬帮忙看下。
另外，IOS手机浏览器打开视频文章，界面没有显示视频播放。

**Comment by LIlGG** [comment]
> ![20200711-1](https://user-images.githubusercontent.com/27286999/87217596-8f41bd80-c37d-11ea-9123-af5116d64059.png)
> PC端发布视频文章，视频位置似乎不在居中的位置，麻烦大佬帮忙看下。
> 另外，IOS手机浏览器打开视频文章，界面没有显示视频播放。

是使用video标签添加的视频吗？

**Comment by PandaQ1** [comment]
> > ![20200711-1](https://user-images.githubusercontent.com/27286999/87217596-8f41bd80-c37d-11ea-9123-af5116d64059.png)
> > PC端发布视频文章，视频位置似乎不在居中的位置，麻烦大佬帮忙看下。
> > 另外，IOS手机浏览器打开视频文章，界面没有显示视频播放。
> 
> 是使用video标签添加的视频吗？

yep。

**Comment by PandaQ1** [comment]
辛苦大佬了

**Comment by LIlGG** [comment]
@PandaQ1 video这里暂时还没测试。但是如果用video标签的话应该能自定义样式的，这个地方主题不会规定的太死，如果在video里面设置样式无效的话，你可以在主题 -> 设置 -> 自定义样式 中，增加自己想要的css
对应视频我后面会测试一遍，然后设置默认的视频样式

**Comment by PandaQ1** [comment]
> @PandaQ1 video这里暂时还没测试。但是如果用video标签的话应该能自定义样式的，这个地方主题不会规定的太死，如果在video里面设置样式无效的话，你可以在主题 -> 设置 -> 自定义样式 中，增加自己想要的css
> 对于视频我后面会测试一遍，然后设置默认的视频样式

好的~我改下哈哈哈，麻烦啦
