### ISSUE TITLE
给标签页和分类页设置头部图片后打不开

### ISSUE THREAD

**Issue by mimajiushi** [LIlGG/halo-theme-sakura#162]
- 点开时页面如下：
![image](https://user-images.githubusercontent.com/33995610/117940786-02201a00-b33c-11eb-96e6-4244d7ace6c9.png)
- 浏览器控制台出现如下错误：
![image](https://user-images.githubusercontent.com/33995610/117940943-3398e580-b33c-11eb-915f-e4fec0064e32.png)

#109

**Comment by LIlGG** [comment]
可以提供一下博客地址吗？

**Comment by LIlGG** [comment]
提供博客地址后再打开即可

**Comment by mimajiushi** [comment]
设置别名之后就打不开了，把别名去掉即可

**Comment by mimajiushi** [comment]
实际上貌似把别名重新保存一遍就可以了。。不知道是不是历史遗留的数据格式问题
