### ISSUE TITLE
我想问一下为什么我配置了音乐和开启了插件还是显示不出来那个音乐呢

### ISSUE THREAD

**Issue by xiaodeme-aha** [LIlGG/halo-theme-sakura#171]
我想问一下为什么我配置了音乐和开启了插件还是显示不出来那个音乐呢

**Comment by parasomn1a** [comment]
请提供以下信息：
1. 音乐配置处的截图
2. 网易云音乐的歌单链接（确保歌单存在）

**Comment by LIlGG** [comment]
除了 @parasomn1a  所说的条件，目前还需要确保歌单 ID 不是 “我喜欢” 的歌单，“我喜欢” 的歌单接口需要登录之后才能获取到了

**Comment by xiaodeme-aha** [comment]
我找到原因了哈哈哈，我看到id就把前面的全删了，结果是我的是user_id没看见哈哈哈
