### ISSUE TITLE
音乐播放器

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#175]
目前音乐播放器的id还只能是歌单,是否可以添加歌曲id和歌手id的功能呢

**Comment by CodeChenL** [comment]
还有顺手催一下鸽了很久的#46 😂

**Comment by LIlGG** [comment]
关于 QQ 音乐已经要开始着手准备了。目前在研究其他的一些东西，所以主题这块儿耽搁了不少时间

**Comment by Leixqiao** [comment]
音乐播放器用不了了
![image](https://user-images.githubusercontent.com/73173080/141079442-ce8349dd-ff33-427b-97b9-8a12487ad5f7.png)

**Comment by CarrotVegeta** [comment]
音乐播放器从页面切换菜单不显示，刷新页面又有了

**Comment by xiongtete0519** [comment]
你们音乐播放器怎么配置的啊，我两个插件功能都开启了，但是博客的左下角没有播放的那个东西。

**Comment by CarrotVegeta** [comment]
> 你们音乐播放器怎么配置的啊，我两个插件功能都开启了，但是博客的左下角没有播放的那个东西。

在背景音乐里面有个开启左下方音乐浮动

**Comment by xiongtete0519** [comment]
![image](https://user-images.githubusercontent.com/66518135/160347733-82e6627f-2270-488e-830f-0db49af49ad3.png)
我把最后这个id写在了下面这里，
![image](https://user-images.githubusercontent.com/66518135/160347871-0486bda2-2354-4343-bbe7-2430dd816a32.png)
而且插件功能也开启了，如下：
![image](https://user-images.githubusercontent.com/66518135/160347941-80154807-1ff9-46b1-b398-b528fc24e3ee.png)
但是我的博客中开始没有，我的博客链接：[https://www.codeleader.top](url)
