### ISSUE TITLE
评论问题

### ISSUE THREAD

**Issue by Liner03** [LIlGG/halo-theme-sakura#177]
提交评论无反应

**Comment by LIlGG** [comment]
能描述的更详细一些吗

**Comment by Liner03** [comment]
你好，就是点击回复后没有任何反应

**Comment by LIlGG** [comment]
> 你好，就是点击回复后没有任何反应

使用的是否是 https://github.com/LIlGG/halo-comment-sakura 评论组件？ 目前我的博客并没有发现回复后没有反应的情况。

你可以看看是否是开启了评论审核？前往 `系统 - 博客设置 - 评论设置` 查看。
一般没有任何反应，说明是后台报错，或许可以提供一下点击评论时的后台日志

**Comment by LIlGG** [comment]
经过测试并没有问题，你可以看看我的回复
