### ISSUE TITLE
修改社交网络图标，统一风格

### ISSUE THREAD

**Issue by alex3236** [LIlGG/halo-theme-sakura#182]
现在的样子有的暗有的亮，非常不舒服。
从 iconfont 找了一些我觉得合适的，供你们参考（包括了当前主题支持的所有社交网络）
[ZIP文件](https://files.catbox.moe/i4rzhn.zip)

**Comment by yikexiaoyao** [comment]
有个问题想反馈一下，作者的图库里面怎么还有大专证明题截图啊，能不能整理一下图库，谢谢，哈哈

**Comment by LIlGG** [comment]
> 有个问题想反馈一下，作者的图库里面怎么还有大专证明题截图啊，能不能整理一下图库，谢谢，哈哈

应该是其他人所上传的，后续会整理一次图库
