### ISSUE TITLE
主题开启了mathjax 数学公式插件，但文章中仍然无法正确的解析Latex语法

### ISSUE THREAD

**Issue by Crazypointer** [LIlGG/halo-theme-sakura#185]
![image](https://user-images.githubusercontent.com/30772089/137000531-c5ffe0b0-ebae-4107-9551-662c30d51f3a.png)

**Comment by FelicxFoster** [comment]
> 由于开启 mathjax 会加载不少资源，所以目前实现了懒加载方式。查看文章 https://lixingyong.com/2021/01/05/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E#toc-head-41 不仅需要在主题设置中开启，还需要在 `发布文章时的元数据中` 输入对应的 K-V 才可生效。 目前主题设置中没有相应的注释，十分抱歉造成困扰。

请问怎么操作“输入对应的 K-V ”，对前端这一块不是很了解

**Comment by LIlGG** [comment]
这个 issue 我先关闭了哈，如果有需求可以再次打开

**Comment by FelicxFoster** [comment]
谢谢哈，一直忘记回复了

Li ***@***.***> 于2021年12月23日周四 16:08写道：
