### ISSUE TITLE
数学公式渲染不出来

### ISSUE THREAD

**Issue by thomas10011** [LIlGG/halo-theme-sakura#186]
开启了全局mathjax，也设置了元数据，但是数学公式完全渲染不出来

**Comment by FelicxFoster** [comment]
> > 如果拿到原始 markdown 再使用 js 渲染可能会导致 SEO 的问题。这块还需要好好考虑怎么处理，目前暂时建议先使用临时方案解决吧。
> 
> 好的

请问您现在是怎么解决的，设置元数据这一步不知道怎么设

**Comment by ruibaby** [comment]
如果对此有强需求，建议尝试 Halo 1.5，并使用 Sakura 的 next 分支。在主题设置开启 Katex。

https://bbs.halo.run/d/2139-halo-150-alpha
