### ISSUE TITLE
随机图的api好像挂掉了。。

### ISSUE THREAD

**Issue by hugh-zhan9** [LIlGG/halo-theme-sakura#189]

**Comment by LIlGG** [comment]
您好，目前我服务器项目挂了，但大概只有晚上下班才可以处理，静待即可！谢谢关心

**Comment by WowUhm** [comment]
我也刚发现，访问了博客，然后来这儿看问题了emm

**Comment by LIlGG** [comment]
> 我也刚发现，访问了博客，然后来这儿看问题了emm

正在修，打工人刚刚下班，蕾姆~

**Comment by LIlGG** [comment]
已经处理完了，本 issue 关闭了哈！

**Comment by monkeyKinn** [comment]
> 已经处理完了，本 issue 关闭了哈！



> 已经处理完了，本 issue 关闭了哈！

2023年5月31日 23:46:38  好像又挂了
另外 我也看了其他issue,没有找到对应自己搭建的api文档格式,请问如果我需要自己搭建随机图api,需要符合什么格式?对应的文档有吗?

顺便提一嘴,网易云的播放器也挂了

主题: 1.3.4
Halo: 1.6.0

**Comment by LIlGG** [comment]
> > 已经处理完了，本 issue 关闭了哈！
> 
> 2023年5月31日 23:46:38 好像又挂了 另外 我也看了其他issue,没有找到对应自己搭建的api文档格式,请问如果我需要自己搭建随机图api,需要符合什么格式?对应的文档有吗?
> 
> 顺便提一嘴,网易云的播放器也挂了
> 
> 主题: 1.3.4 Halo: 1.6.0 @LIlGG

查看 #343 
随机图将支持第三方 API 格式。
至于音乐播放器，也将使用第三方 API。

目前没有太多精力来修复随机图和网易云 API，因此打算支持一下目前比较好的一些 API
