### ISSUE TITLE
博主什么时候更新可以上视频的功能

### ISSUE THREAD

**Issue by Qxin-X** [LIlGG/halo-theme-sakura#190]
博主什么时候更新可以上视频的功能

**Comment by LIlGG** [comment]
什么是“上视频” 功能。。。

**Comment by Qxin-X** [comment]
不好意思，描述不清晰 。就是可以像图片那个板块一样，但是都是视频，视频板块。

**Comment by LIlGG** [comment]
这个功能没有在计划之中，可以问一下具体用途吗？如果都是视频，是否没有太大必要？因为这就相当于把 halo 作为一个视频播放软件了，感觉没有太大意义

**Comment by Qxin-X** [comment]
嗯，有道理，那谢谢了。

**Comment by LIlGG** [comment]
不用谢，如果可以的话你可以自行定制，但本主题的定位还是博客，所以不会考虑在主题中增加这个功能。
