### ISSUE TITLE
分类与标签文字重叠

### ISSUE THREAD

**Issue by justinkhant** [LIlGG/halo-theme-sakura#194]
你好，有2个问题：

1. 我的文章分类跟标签都是这种重叠状态，是不是需要设置什么？
2. lixingyong.com打不开了，显示502，主题使用还在自己研究所以需要看说明页面求作者大大解决下。

<img width="655" alt="Screen Shot 2021-11-26 at 1 17 33 PM" src="https://user-images.githubusercontent.com/56903102/143556970-333163c3-467b-4e0b-a97a-72b2087d8593.png">

**Comment by LIlGG** [comment]
> 你好，有2个问题：
> 
> 1. 我的文章分类跟标签都是这种重叠状态，是不是需要设置什么？
> 2. lixingyong.com打不开了，显示502，主题使用还在自己研究所以需要看说明页面求作者大大解决下。
> 
> <img alt="Screen Shot 2021-11-26 at 1 17 33 PM" width="655" src="https://user-images.githubusercontent.com/56903102/143556970-333163c3-467b-4e0b-a97a-72b2087d8593.png">

正常应该不会出现重叠状态，目前仅你一个人出现这种情况，你可以把网址发出来。
网站今天崩了，不过上班的时候不能访问外网，所以无法解决这个问题，等会儿我下班之后再一起解决。

**Comment by justinkhant** [comment]
我是在本地测试的所以没买服务器，不过我发现右边的chrome没问题，左边的safari（Version 12.1.2有问题。可能是浏览器适配问题吧。
另外期待大大的网站能恢复！
<img width="1277" alt="Screen Shot 2021-11-26 at 2 30 09 PM" src="https://user-images.githubusercontent.com/56903102/143567042-a2fe66a3-c2eb-411e-b69c-fdc0466238e4.png">

**Comment by LIlGG** [comment]
> 我是在本地测试的所以没买服务器，不过我发现右边的chrome没问题，左边的safari（Version 12.1.2）有问题。可能是浏览器适配问题吧。 另外期待大大的网站能恢复！ <img alt="Screen Shot 2021-11-26 at 2 30 09 PM" width="1277" src="https://user-images.githubusercontent.com/56903102/143567042-a2fe66a3-c2eb-411e-b69c-fdc0466238e4.png">

由于我开发的时候是基于 chrome 开发的，因此其他浏览器的效果可能都有些问题。这块得慢慢适配，主要是手上没有 mac 本，这方面不好测。
【网站已经恢复】
