### ISSUE TITLE
大部分歌曲接口错误

### ISSUE THREAD

**Issue by justinkhant** [LIlGG/halo-theme-sakura#195]
作者,你好
我在测试音乐的时候歌曲里有些可以听有些不可以跳过了,然后看了看原来是网易接口的问题:
https://music.163.com/song/media/outer/url?id=###.mp3 这个接口请求有些可以,但大部分返回404.我原本以为就我的这样,然后我去看作者的博客歌单https://lixingyong.com/s/music 发现也有同样的问题(大多数都播放不了跳过了,在手机app里去听过歌单了.已确认没有地区版权问题或者vip问题)

**Comment by LIlGG** [comment]
感谢反馈！今天下班之后会进行排查，也许是网易云本身接口有所变化导致

**Comment by LIlGG** [comment]
我测试了我博客内的歌单，发现并没有你说的这种情况。你可以定位一个歌曲然后发一下歌曲 ID 吗

**Comment by justinkhant** [comment]
https://music.163.com/song/media/outer/url?id=28445990.mp3
这是作者歌单里的一曲

**Comment by LIlGG** [comment]
> https://music.163.com/song/media/outer/url?id=28445990.mp3 这是作者歌单里的一曲

这首歌似乎没有问题

**Comment by LIlGG** [comment]
> https://music.163.com/song/media/outer/url?id=28445990.mp3 这是作者歌单里的一曲

经过测试，仅有 VIP 单曲和私密歌单的无法获取到。其他的大部分都可以获取到。你可以检查一下你本地的网络设置等

**Comment by justinkhant** [comment]
奇怪了,同一个wifi下面手机直接访问链接可以打开,用app也可以打开,电脑就不行(不是refuse to connect 就是404).
虽然找不到原因不过我手机可以访问说明不是主题的问题了

**Comment by LIlGG** [comment]
> 奇怪了,同一个wifi下面手机直接访问链接可以打开,用app也可以打开,电脑就不行(不是refuse to connect 就是404). 虽然找不到原因不过我手机可以访问说明不是主题的问题了

也许是你电脑开了代理，拦截了请求。又或者是设置了某些 DNS。总之大概率就是电脑网络问题

**Comment by justinkhant** [comment]
好的,谢谢回复
