### ISSUE TITLE
css 资源什么的好像挂了

### ISSUE THREAD

**Issue by wyf2215087636** [LIlGG/halo-theme-sakura#200]
css 资源什么的好像挂了，图片和代码等样式出现了问题

**Comment by LIlGG** [comment]
如果本地的资源出了问题，可以采用线上的。 在后台主题中选择。

**Comment by wyf2215087636** [comment]
![image](https://user-images.githubusercontent.com/46517422/146707536-69c8c706-4139-4012-aad8-07b19657aa27.png)
奥，
好像是CDN 出现问题了，关闭就解决了，官网的blog 好像也出现这样的问题了，可以看一下= =
![image](https://user-images.githubusercontent.com/46517422/146707714-6b99d343-6cbe-4cce-84a3-29b027d2e8bd.png)

**Comment by LIlGG** [comment]
> ![image](https://user-images.githubusercontent.com/46517422/146707536-69c8c706-4139-4012-aad8-07b19657aa27.png) 奥， 好像是CDN 出现问题了，关闭就解决了，官网的blog 好像也出现这样的问题了，可以看一下= = ![image](https://user-images.githubusercontent.com/46517422/146707714-6b99d343-6cbe-4cce-84a3-29b027d2e8bd.png)

嗯 那可能是 jsdelivr 出现了问题，不过也有可能是你的网络访问不到这个地址。关闭 CDN 即可。

**Comment by wyf2215087636** [comment]
![image](https://user-images.githubusercontent.com/46517422/146708987-3e38b5be-664e-4b7f-8951-7117c0f464d5.png)

**Comment by LIlGG** [comment]
> ![image](https://user-images.githubusercontent.com/46517422/146708987-3e38b5be-664e-4b7f-8951-7117c0f464d5.png)

意思是即使关闭 CDN 也仍旧有使用 CDN 的链接吗？？

**Comment by parasomn1a** [comment]
> ![image](https://user-images.githubusercontent.com/46517422/146707536-69c8c706-4139-4012-aad8-07b19657aa27.png) 奥， 好像是CDN 出现问题了，关闭就解决了，官网的blog 好像也出现这样的问题了，可以看一下= = ![image](https://user-images.githubusercontent.com/46517422/146707714-6b99d343-6cbe-4cce-84a3-29b027d2e8bd.png)

https://github.com/jsdelivr/jsdelivr/issues/18348#issuecomment-997777996

**Comment by wyf2215087636** [comment]
好的，感谢
