### ISSUE TITLE
首页视频的跨域问题

### ISSUE THREAD

**Issue by Carinx** [LIlGG/halo-theme-sakura#201]
![image](https://user-images.githubusercontent.com/49282008/146859348-88d7fe66-f8dd-4d27-b0d5-8c1195c372e3.png)

**Comment by LIlGG** [comment]
> ![image](https://user-images.githubusercontent.com/49282008/146859348-88d7fe66-f8dd-4d27-b0d5-8c1195c372e3.png)

即使不跨域目前首页视频也用不了。。接口不合适了，还没有进行调整。你可以暂时用本地资源来使用首页视频功能。

**Comment by Carinx** [comment]
👌，大佬回复得真快，只是刚好看到了就提一下问题😏

**Comment by LIlGG** [comment]
> 👌，大佬回复得真快，只是刚好看到了就提一下问题😏

#169 
嗯嗯~ 有问题就可以问。这个 issue 我先关闭了哈，属于重复问题了。
