### ISSUE TITLE
支持用户自行指定CDN

### ISSUE THREAD

**Issue by Qxin-X** [LIlGG/halo-theme-sakura#204]
作者你好，由于jsdelivr的CDN加速失效，halo后台已经更新到1.4.17,支持用户的全站CDN加速，我还是比较喜欢你的主题，但是由于要经过jsDelivr的CDN，导致非常慢，比较影响用户体验，希望你能考虑一下，下放资源到用户本地服务器，可以支持用户自行指定CDN，恢复之前的访问速度，谢谢。

**Comment by LIlGG** [comment]
在 1.2.0 版本之后，主题就支持了资源使用本地，在 `主题设置 -> 其他 -> 资源使用 CDN` 选关闭即可使用本地资源 
![image](https://user-images.githubusercontent.com/31335418/148954414-6a9f8bb4-74e8-4d76-8be8-4cbf7880d8e9.png)

**Comment by Qxin-X** [comment]
> 

好的谢谢，你的主题真不错，点赞！

**Comment by LIlGG** [comment]
> > 
> 
> 好的谢谢，你的主题真不错，点赞！

非常感谢~ 如果有其他问题可以再询问。这个 issue 我就关闭了哈
