### ISSUE TITLE
jsdelivr CDN不稳定

### ISSUE THREAD

**Issue by asd123wto** [LIlGG/halo-theme-sakura#206]
大陆网连接cdn.jsdelivr.net慢，有什么解决办法吗（除了挂梯子）

**Comment by LIlGG** [comment]
主题支持使用本地资源，在 主题设置 -> 其他 -> 资源使用 CDN 选关闭即可使用本地资源。转为本地资源后，可以自行使用 CDN。

**Comment by LIlGG** [comment]
#204 #205
