### ISSUE TITLE
代码块风格问题

### ISSUE THREAD

**Issue by L-weici** [LIlGG/halo-theme-sakura#208]
代码块长度过长时候,下方会产生左右移动的小横条,此横条左右没有圆滑处理,为直角 与上半部分对比有些突兀 
<img width="866" alt="iShot2022-01-14 16 31 38" src="https://user-images.githubusercontent.com/54562194/149478611-385f3c37-905b-4b8f-a59a-2113027452de.png">

**Comment by LIlGG** [comment]
这个地方的设计默认就是窗口式的，因此样式不存在问题。如果有什么好的想法，可以提交 PR 或者共同商议一下。
