### ISSUE TITLE
管理后台找回密码时，邮件发送问题

### ISSUE THREAD

**Issue by Cloudkkk** [LIlGG/halo-theme-sakura#209]
请问一下，
邮箱未开启SMTP服务导致发送邮件失败，提示信息是可在系统日志中获取
系统日志在哪里？这里的系统日志是指什么系统的日志呢？

**Comment by LIlGG** [comment]
点击后台左上角 Halo 标志多次，就可以打开`开发者选项`。之后在 `系统 -> 小工具 -> 开发者选项` 里面就可以看到有个实时日志

**Comment by LIlGG** [comment]
这个问题前往 https://github.com/halo-dev/halo 提问效果会更好
