### ISSUE TITLE
输完域名,第一次打开页面主题样式没有生效

### ISSUE THREAD

**Issue by Chen-CBO** [LIlGG/halo-theme-sakura#210]
输完域名按回车,打开页面主题样式没有生效,点一下首页或者别的导航,才会生效主题样式

**Comment by LIlGG** [comment]
可以给一下博客地址吗？？

**Comment by Chen-CBO** [comment]
81.70.100.234

**Comment by Chen-CBO** [comment]
> 可以给一下博客地址吗？？

81.70.100.234

**Comment by LIlGG** [comment]
> > 可以给一下博客地址吗？？
> 
> 81.70.100.234

我这里查看已经生效了的。 
![image](https://user-images.githubusercontent.com/31335418/150244916-5b73f45a-e646-49e2-97c8-66cf42b75c81.png)

**Comment by Chen-CBO** [comment]
> > > 可以给一下博客地址吗？？
> 
> 我这里查看已经生效了的。 ![image](https://user-images.githubusercontent.com/31335418/150244916-5b73f45a-e646-49e2-97c8-66cf42b75c81.png)

没有,我给的默认主题是八,点一下首页,背景就是黑色的了

**Comment by LIlGG** [comment]
> 没有,我给的默认主题是八,点一下首页,背景就是黑色的了

你可以看看我的博客是否是默认黑色 https://lixingyong.com/

**Comment by Chen-CBO** [comment]
> > 没有,我给的默认主题是八,点一下首页,背景就是黑色的了
> 
> 你可以看看我的博客是否是默认黑色 https://lixingyong.com/

没问题,你的是默认黑色,怎么设置的?我的为什么不生效呢?

**Comment by LIlGG** [comment]
> 没问题,你的是默认黑色,怎么设置的?我的为什么不生效呢?

我的也是设置默认主题八，有可能是我之前回滚 master  版本的原因。你可以使用 https://github.com/LIlGG/halo-theme-sakura/archive/refs/tags/v1.3.2.zip 下载发行版主题。

**Comment by Chen-CBO** [comment]
> https://lixingyong.com/

好的, 我去试试,谢谢

**Comment by LIlGG** [comment]
> > https://lixingyong.com/
> 
> 好的, 我去试试,谢谢

ok 包含你 IP 的相关评论我已经删了。如果下次是 IP 方式可以发邮件，切勿在公共场合暴露 IP。防止被 DDOS 攻击

**Comment by Chen-CBO** [comment]
> 

恩,好的,问题已经解决了,域名还在备案中,谢谢
