### ISSUE TITLE
1.3.3版本文章页时间会显示成 time . edit_time

### ISSUE THREAD

**Issue by sherlocky** [LIlGG/halo-theme-sakura#212]
![image](https://user-images.githubusercontent.com/8652013/150643077-449a7f86-0c98-43af-b64d-9a9980bb5910.png)

**Comment by LIlGG** [comment]
我1.3.3 还没准备发布。 https://github.com/LIlGG/halo-theme-sakura/pull/211 待发布后各项配套内容才能正常显示

**Comment by LIlGG** [comment]
或者你拉去 1.3.3 最新代码。然后使用本地资源尝试

**Comment by sherlocky** [comment]
拉取了最新的133分支，关闭了cdn，走了本地资源了

**Comment by LIlGG** [comment]
> 拉取了最新的133分支，关闭了cdn，走了本地资源了

如果按照上述操作进行，不应当会出现问题

**Comment by sherlocky** [comment]
等您Release了我再试试吧，tks~

**Comment by LIlGG** [comment]
> 等您Release了我再试试吧，tks~

如果不使用 CDN 资源的话。用本地开发和 release 应该是一样的。发行后可以再试试

**Comment by LIlGG** [comment]
已发布 1.3.3 版本。可以再试试

**Comment by sherlocky** [comment]
明早我再试下，辛苦👍🏻

**Comment by sherlocky** [comment]
最新的master还是不行呢，服务端也更新到最新的1.4.7了

**Comment by LIlGG** [comment]
> 最新的master还是不行呢，服务端也更新到最新的1.4.7了

删除主题之后重新下载。（别删除配置项）。或者清理一下浏览器及 CDN 缓存。版本肯定是没问题的，我现在就使用的 1.3.3。

**Comment by sherlocky** [comment]
确实是缓存问题👍🏻
