### ISSUE TITLE
文章分享功能BUG

### ISSUE THREAD

**Issue by Carinx** [LIlGG/halo-theme-sakura#213]
1. 微信二维码没有生成成功
![image](https://user-images.githubusercontent.com/49282008/151130265-44cb3450-9e56-423f-bfa7-7bef7cd85e92.png)
2. QQ分享生成二维码好像有信息长度限制而导致报错
![image](https://user-images.githubusercontent.com/49282008/151131211-613055b9-3572-424b-8ed6-75fc848d0539.png)

**Comment by LIlGG** [comment]
了解，后面会看一下

**Comment by LIlGG** [comment]
测试之后没有发现问题
![image](https://user-images.githubusercontent.com/31335418/159216087-635573b6-bedf-4587-bcd2-251683ebb1e0.png)

**Comment by Carinx** [comment]
你好大佬！
去大佬的博客看了下，发现也是会出现这个问题
![image](https://user-images.githubusercontent.com/49282008/159220591-965cf990-e822-4973-b595-58f86cbe5fc0.png)

<hr>

只懂一丢丢前端，根据id名去搜索相关代码，然后在console手动执行就能生成二维码
![image](https://user-images.githubusercontent.com/49282008/159222106-d07ce6fe-c54b-4543-b548-1ba1356671de.png)

<hr>

![image](https://user-images.githubusercontent.com/49282008/159222036-71c7a191-2c7d-460f-918a-4509f5441f71.png)

<hr>

好像是第一次渲染页面时出现问题导致没有生成二维码成功，但HTML页面标签却是有
![image](https://user-images.githubusercontent.com/49282008/159223155-2290cd18-bfee-46a1-8822-2de4897de54b.png)

<hr>
并且显示二维码的窗口位置也不对，鼠标放在微信上，但是窗口指向的却是微博的图标

![image](https://user-images.githubusercontent.com/49282008/159223867-5210ea2b-f7bd-4142-8369-a09d10693779.png)

<hr>

![image](https://user-images.githubusercontent.com/49282008/159224025-f98f693a-3bfb-44cf-ba44-3c0ee4eb3418.png)

**Comment by LIlGG** [comment]
了解了，但 next 版本无此问题。应该是上个版本 minicode 的bug 导致
