### ISSUE TITLE
文章内容页面小BUG

### ISSUE THREAD

**Issue by yikexiaoyao** [LIlGG/halo-theme-sakura#214]
打开文章页面，右上角会显示一连串缩略标题，但是当文章翻阅到最后位置的时候，右上角缩略标题就不见了，很不方便，希望作者帮忙改善，谢谢

**Comment by LIlGG** [comment]
可以给个截图吗？纯文本不太看得明白

**Comment by yikexiaoyao** [comment]
Li ***@***.***> 于2022年1月27日周四 22:03写道：

**Comment by LIlGG** [comment]
问题已经复现，属于 TOC 的定位问题，将于近期修复

**Comment by yikexiaoyao** [comment]
感谢回复，希望尽快修复，辛苦了
