### ISSUE TITLE
文章内容的一些小问题

### ISSUE THREAD

**Issue by waltz26** [LIlGG/halo-theme-sakura#215]
更新主题后发现了两个小问题：

1. 右侧目录的小黄条（就是显示当前在读哪个标题下的内容）在载入文章页后是停留在第一个标题，但是往下滑之后会直接变到最后一个标题处，起不到它应有的作用。实际的例子请看[这个](https://www.waltz26.cn/archives/%E9%85%8D%E7%BD%AE%E4%B8%80%E4%B8%AA%E9%80%82%E5%90%88%E7%AE%97%E6%B3%95%E7%AB%9E%E8%B5%9B%E7%9A%84vscode)，注意未往下滑时和往下滑之后右侧目录的变化。
2. 手机（safari浏览器）和微信点击页面浏览时```代码块都会变成`代码块。

**Comment by LIlGG** [comment]
感谢提供的信息，目前发现确实是这样的。将会在近期进行修复！
