### ISSUE TITLE
文章发布页面时间获取问题

### ISSUE THREAD

**Issue by julylLes** [LIlGG/halo-theme-sakura#218]
# 版本 
halo后台拉取最新的

# 问题
post页面没有获取到文章发布时间，出现time  edit_time字段

ps：第一次写Lssues，抱歉

**Comment by LIlGG** [comment]
可以看查看 #212

**Comment by julylLes** [comment]
Ok,幸苦了

**Comment by julylLes** [comment]
> 可以查看 #212

Ok,幸苦了
