### ISSUE TITLE
分类雷达失效了

### ISSUE THREAD

**Issue by cuntoushifu** [LIlGG/halo-theme-sakura#219]
<img src="https://cdn.jsdelivr.net/gh/cuntoushifu/imgs@master/blog/202202051915523.png"/>
<img src="https://cdn.jsdelivr.net/gh/cuntoushifu/imgs@master/blog/202202051917862.png"/>
<img src="https://cdn.jsdelivr.net/gh/cuntoushifu/imgs@master/blog/202202051918125.png"/>
分类雷达失效了

**Comment by LIlGG** [comment]
确实发现此 BUG，将于近期修复，感谢！
