### ISSUE TITLE
mac上文字上方的标题图片仍然是.pattern-center样式，宽度100%。

### ISSUE THREAD

**Issue by limin04551** [LIlGG/halo-theme-sakura#22]

**Comment by LIlGG** [comment]
有图片吗？

**Comment by limin04551** [comment]
http://182.61.27.43/upload/2020/07/截屏2020-07-14 下午11.32.54-224ba27cdd9348a5bba7b1cd10880d94.png
在你的demo上看文章是没问题的，但是自己这边就有问题，从https://github.com/LIlGG/halo-theme-sakura拉的主题。

**Comment by LIlGG** [comment]
> [http://182.61.27.43/upload/2020/07/截屏2020-07-14](http://182.61.27.43/upload/2020/07/%E6%88%AA%E5%B1%8F2020-07-14) 下午11.32.54-224ba27cdd9348a5bba7b1cd10880d94.png
> 在你的demo上看文章是没问题的，但是自己这边就有问题，从[https://github.com/LIlGG/halo-theme-sakura拉的主题。](https://github.com/LIlGG/halo-theme-sakura%E6%8B%89%E7%9A%84%E4%B8%BB%E9%A2%98%E3%80%82)

emmm 图片不存在。 我看你的博客也似乎没有什么问题。。

**Comment by limin04551** [comment]
图片地址：“http://182.61.27.43/upload/2020/07/截屏2020-07-14 下午11.32.54-224ba27cdd9348a5bba7b1cd10880d94.png”；
存在的哟，我用windows上去看是没问题，mbp上去看标题图就拉长了 ### - -

**Comment by LIlGG** [comment]
> [http://182.61.27.43/upload/2020/07/截屏2020-07-14](http://182.61.27.43/upload/2020/07/%E6%88%AA%E5%B1%8F2020-07-14) 下午11.32.54-224ba27cdd9348a5bba7b1cd10880d94.png

推荐使用markdown的方式发送图片 ```![]()```这样的。
我这边看过你这个图，看起来是和我预期的差不多的。 默认确实会将图片长度设置为100%。 有什么更好的建议吗？

**Comment by limin04551** [comment]
我这边直接.pattern-center也改成800px;margin: 0 auto;了

**Comment by LIlGG** [comment]
@limin04551 也许是你的用法不太对。pattern-center为800px的情况，只有当主题里面开启背景缩进，并且目前为对应的主题才会缩进。如下图
![themeSettings](https://lixingyong.com/upload/2020/07/themeSettings-ca86499cdba54e949a8e8337600f154e.png)
如果你想达到对应的效果，可以在 主题设置 -> 主题切换 -> 背景缩进中 将默认主题的背景缩进勾选即可
