### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by waltz26** [LIlGG/halo-theme-sakura#221]
没错又是我......看见更新之后立马上线测试了下，还是有点小问题

1.右侧目录又不跟随滑动了，这个我测试了下大概是在第一个一级标题内容快结束后就不跟随滑动了
2.点击右侧目录的某个标题后点击文章中的某个图片观看，退出后会直接回到刚才点击的标题处（1.3.2无此问题，1.3.3有此问题）

上述问题可以在<a href="https://www.waltz26.cn/archives/%E9%85%8D%E7%BD%AE%E4%B8%80%E4%B8%AA%E9%80%82%E5%90%88%E7%AE%97%E6%B3%95%E7%AB%9E%E8%B5%9B%E7%9A%84vscode" target="_blank">我的这篇文章</a>中看到。

作者大大辛苦

**Comment by LIlGG** [comment]
问题一没有复现，问题二确实存在。。需要解决一下

**Comment by waltz26** [comment]
https://cloud.waltz26.cn/picture/c751a3848b2144bfa279fc1bc4d0f110.gif 可以看下这个gif
