### ISSUE TITLE
代码块语言识别无法自定义

### ISSUE THREAD

**Issue by codingboylj** [LIlGG/halo-theme-sakura#222]
代码块检测错误，添加了标签也无效，*powershell*命令它识别为*PHP*代码。
![Screenshot_2022-02-11-17-54-48-361_com kiwibrowser browser](https://user-images.githubusercontent.com/57084184/153574959-ec31d908-1828-4ebb-8823-76f70cd319b2.jpg)
![Screenshot_2022-02-11-17-54-29-666_com kiwibrowser browser](https://user-images.githubusercontent.com/57084184/153575001-71398425-a0e8-4d4a-9c02-cf207783158c.jpg)
已经添加了这个自定义，但没有用

**Comment by LIlGG** [comment]
可以尝试使用 shell
