### ISSUE TITLE
建议增加自行替换CDN功能

### ISSUE THREAD

**Issue by HenMie** [LIlGG/halo-theme-sakura#224]
目前国内环境jsdelivr速度比较慢，无法正常使用，但是直接使用服务器资源的话，对于小服务器来说速度也是不理想的。我在主题设置关闭了使用cdn，并且把后台能进行设置的资源地址都改成了自己的腾讯云cdn，发现还是有一些资源使用了jsdelivr的，并且它们无法直接修改，需要手动修改主题，略微麻烦。  
建议可以在后台一键设置自定义cdn地址，这样的话直接拷贝jsdelivr的资源到自己的cdn，变一个域名保持目录一致就可以了，一个个换实在是有些麻烦。

**Comment by LIlGG** [comment]
换成本地地址之后，便可以使用 CDN 代理本地地址了。自行替换 CDN 我觉得一般人可能很容易操作失误

**Comment by HenMie** [comment]
> 换成本地地址之后，便可以使用 CDN 代理本地地址了。自行替换 CDN 我觉得一般人可能很容易操作失误

那好像确实，不过目前halo有些后台操作是用PUT或者DELETE的，有不少小厂cdn不支持（比如我之前用的ucloud就不支持，还排查了半天）
