### ISSUE TITLE
希望可以增加 “ one-dark ” 这个代码块。

### ISSUE THREAD

**Issue by BJianCheng** [LIlGG/halo-theme-sakura#225]

**Comment by LIlGG** [comment]
可以述说一下详细内容吗？？

**Comment by BJianCheng** [comment]
> 可以述说一下详细内容吗？？

是个代码块主题，我试用其他主题的时候看见的，感觉这个主题色彩多一些。 如果麻烦的话就算了，也不是什么刚需，哈哈。

**Comment by LIlGG** [comment]
> > 可以述说一下详细内容吗？？
> 
> 是个代码块主题，我试用其他主题的时候看见的，感觉这个主题色彩多一些。 如果麻烦的话就算了，也不是什么刚需，哈哈。

代码块主题还是比较容易添加的。我后面会注意一下，如果发现的话就可以迁移过来

**Comment by BJianCheng** [comment]
> > > 可以述说一下详细内容吗？？
> > 
> > 
> > 是个代码块主题，我试用其他主题的时候看见的，感觉这个主题色彩多一些。 如果麻烦的话就算了，也不是什么刚需，哈哈。
> 
> 代码块主题还是比较容易添加的。我后面会注意一下，如果发现的话就可以迁移过来

**Comment by BJianCheng** [comment]
> 代码块主题还是比较容易添加的。我后面会注意一下，如果发现的话就可以迁移过来

好的感谢。
