### ISSUE TITLE
启动樱花主题以后博客报错，halo默认的主题就没有问题

### ISSUE THREAD

**Issue by dxl519** [LIlGG/halo-theme-sakura#227]
Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> theme_base [in template "themes/LIlGG_Sakura/index.ftl" at line 4, column 98] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: #global res_base_url = settings.cdn?t... [in template "themes/LIlGG_Sakura/index.ftl" at line 4, column 1] ----

**Comment by LIlGG** [comment]
看日志大概率是主题设置的原因。之前有使用过 sakura 主题吗

**Comment by dxl519** [comment]
用过，那时候没有搞域名，然后我给服务器重装了，重新装的主题

**Comment by dxl519** [comment]
> 用过，那时候没有搞域名，然后我给服务器重装了，重新装的主题

你可以访问我的管理后台帮我看看吗？

**Comment by LIlGG** [comment]
> 用过，那时候没有搞域名，然后我给服务器重装了，重新装的主题

那你可以试试将主题配置清空，然后再试试。

**Comment by dxl519** [comment]
怎么清空？

**Comment by LIlGG** [comment]
> 怎么清空？

删除主题的时候，有个选项。是否清空主题配置。

**Comment by dxl519** [comment]
点删除没反应·。。。。

**Comment by LIlGG** [comment]
> 点删除没反应·。。。。

..那只能通过数据库删除了。

**Comment by dxl519** [comment]
删除了，但是没让我选择清空主题配置

**Comment by LIlGG** [comment]
> 删除了，但是没让我选择清空主题配置

删除的时候下面应该有个复选框吧？你需要勾选才行。具体我忘了，目前在上班，无法帮你详细查看

**Comment by dxl519** [comment]
![Snipaste_2022-02-22_16-23-46](https://user-images.githubusercontent.com/58040954/155091864-ce54a266-b716-4d26-9f75-9b8cff6304e1.png)

**Comment by LIlGG** [comment]
> ![Snipaste_2022-02-22_16-23-46](https://user-images.githubusercontent.com/58040954/155091864-ce54a266-b716-4d26-9f75-9b8cff6304e1.png)

对，然后你点删除

**Comment by dxl519** [comment]
![Snipaste_2022-02-22_16-26-04](https://user-images.githubusercontent.com/58040954/155092174-6c5302c9-6014-4832-aad7-92b239287215.png)

点击确定直接就删除了

**Comment by dxl519** [comment]
https://www.lovelights.top/admin/index.html#/interface/themes

这是我的博客后台地址，
admin
123456789

**Comment by LIlGG** [comment]
> ![Snipaste_2022-02-22_16-26-04](https://user-images.githubusercontent.com/58040954/155092174-6c5302c9-6014-4832-aad7-92b239287215.png)
> 
> 点击确定直接就删除了

。。。那你点那个设置呢？应该是主题设置 - 其他里面的使用 CDN 选项的问题

**Comment by LIlGG** [comment]
公司不允许登录外网的。所以没办法帮你看。

**Comment by dxl519** [comment]
我知道问题出在哪里了，我没有开启资源使用CDN，但是现在我的首页样式好像出了问题

**Comment by dxl519** [comment]
![Snipaste_2022-02-22_16-32-47](https://user-images.githubusercontent.com/58040954/155093174-5ca5b39b-c6a4-405f-a4bd-7f4b0d5acc5d.png)

**Comment by LIlGG** [comment]
> 我知道问题出在哪里了，我没有开启资源使用CDN，但是现在我的首页样式好像出了问题

可以不开启使用 cdn，且目前不建议使用 cdn。 你再尝试关闭。或许只是配置出了问题。

**Comment by dxl519** [comment]
> > 我知道问题出在哪里了，我没有开启资源使用CDN，但是现在我的首页样式好像出了问题
> 
> 可以不开启使用 cdn，且目前不建议使用 cdn。 你再尝试关闭。或许只是配置出了问题。

> 关闭CDN以后就出现了开头的那个问题

**Comment by LIlGG** [comment]
> > > 我知道问题出在哪里了，我没有开启资源使用CDN，但是现在我的首页样式好像出了问题
> > 
> > 
> > 可以不开启使用 cdn，且目前不建议使用 cdn。 你再尝试关闭。或许只是配置出了问题。
> 
> > 关闭CDN以后就出现了开头的那个问题

正常不应该。。可能是有什么特殊情况导致的。晚上下班之后我再帮你排查吧。目前我自己的网站就是关闭了 cdn 的。

**Comment by dxl519** [comment]
我按照halo官网的文档进行操作，配置了nginx

**Comment by dxl519** [comment]
> > > > 我知道问题出在哪里了，我没有开启资源使用CDN，但是现在我的首页样式好像出了问题
> > > 
> > > 
> > > 可以不开启使用 cdn，且目前不建议使用 cdn。 你再尝试关闭。或许只是配置出了问题。
> > 
> > 
> > > 关闭CDN以后就出现了开头的那个问题
> 
> 正常不应该。。可能是有什么特殊情况导致的。晚上下班之后我再帮你排查吧。目前我自己的网站就是关闭了 cdn 的。

> 好的，非常感谢.

**Comment by LIlGG** [comment]
下班了。现在可以帮你看看了，向我邮件内发送你的账号密码就行，别发到这里

**Comment by dxl519** [comment]
昨天由于疫情隔离了，很抱歉；账号密码已经发送到你的邮箱
