### ISSUE TITLE
怎么在页面显示网易云歌单

### ISSUE THREAD

**Issue by dxl519** [LIlGG/halo-theme-sakura#229]
怎么在页面显示网易云歌单,请指教

**Comment by LIlGG** [comment]
[查看我主题内的教程](https://lixingyong.com/2021/01/05/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E)

注意歌单编号不能是私密歌单与我喜欢歌单
