### ISSUE TITLE
关于头部装饰图与主题切换背景图的一些建议

### ISSUE THREAD

**Issue by solitudealma** [LIlGG/halo-theme-sakura#230]
如果对于当前背景图不满意时，在主题切换中设置的背景图与头部装饰图或者自定义页面的封面图同时设置时中间会存在向上突起的空白，对于默认主题当然是没啥太大的问题，但是自定义背景时会显得不太协调，比如下图
![image](https://user-images.githubusercontent.com/57446969/156203299-c26c3568-e322-4c7e-8ee5-2c23aebb712c.png)

在查看了css之后，发现是 ```.pattern-center:after{ width:0 /*去掉头部装饰图与背景图的白色遮挡*/}``` 这个css样式的关系，只要将width设置为0并添加到全局css上即可
![image](https://user-images.githubusercontent.com/57446969/156203760-d86ac47e-1a60-4258-b705-8a557c8bc01e.png)

当然，如果您觉得这个遮挡层有什么美观效果的话，是否能考虑将上传的主题切换中的背景图做一个向上突起的效果，实在是太麻烦的话去掉那个css也是可以的哦~再次感谢作者提供了这么好看的主题

**Comment by LIlGG** [comment]
在 2.0.0-beta.2 中重写了 Header，此问题同步被修改。详细查看 #340
