### ISSUE TITLE
无法渲染流程图

### ISSUE THREAD

**Issue by marswh12312313** [LIlGG/halo-theme-sakura#233]
再控制台写文章的时候可以，但是发布的正式网页不行

**Comment by ruibaby** [comment]
这属于 Halo 的问题，1.4 版本需要手动添加插件，参考：https://docs.halo.run/user-guide/markdown#%E5%9B%BE%E8%A1%A8

目前 Halo 1.5 已经支持直接渲染为 svg 并保存，所以不在需要手动添加插件，如果对此有强需求，可以尝试体验下 1.5。

https://bbs.halo.run/d/2139-halo-150-alpha
