### ISSUE TITLE
我用的最新版本的1.33,也会发现目录问题,当文章过长的时候会默认开启到最后一个标题

### ISSUE THREAD

**Issue by jykSS** [LIlGG/halo-theme-sakura#234]
![问题](https://user-images.githubusercontent.com/49031577/156927348-54f86760-506d-437f-aeab-0c4ff3819da2.png)

**Comment by jykSS** [comment]
http://82.156.4.191/

**Comment by jykSS** [comment]
这是我的网址,帮忙看下第一个文章就是出现了这个bug,

**Comment by LIlGG** [comment]
这是已知 BUG，新版本导致的。最新 master 版本已经修复此问题。但还未发布。可以直接在 code 页面进行下载试用。

**Comment by jykSS** [comment]
更新后确实好了,还有一个小问题就是第一次进去,继续往下走的时候,右边目录会丢失的问题,刷新后就会恢复

**Comment by LIlGG** [comment]
> 更新后确实好了,还有一个小问题就是第一次进去,继续往下走的时候,右边目录会丢失的问题,刷新后就会恢复

因为这个 BUG 还没完全修复。。master 版本只是修复了一部分。。如果想完全解决这个问题，可以回退使用 1.3.2 版本。
