### ISSUE TITLE
在平板设备上无法渲染代码块

### ISSUE THREAD

**Issue by Blusand** [LIlGG/halo-theme-sakura#236]
同样的文章，在平板上无法渲染出代码块，而在手机和电脑就可以，后台显示都是正常的
<br/>
平板：
![平板](https://user-images.githubusercontent.com/62822221/157351491-42bc2a3f-650e-4606-b139-768efeaae962.png)

<br/>
电脑：

![电脑](https://user-images.githubusercontent.com/62822221/157351498-5d0508f3-33c3-4e03-be98-9932415ffb1b.png)

<br/>
手机：

![手机](https://user-images.githubusercontent.com/62822221/157351505-1420a79b-c3e9-4ab2-a5af-5d33dd98ce7d.png)

**Comment by ruibaby** [comment]
能否提供一下示例文章。

**Comment by Blusand** [comment]
> 能否提供一下示例文章。
好的

[文章在这](https://halo.blusand.xyz/archives/smartpointer)

**Comment by ruibaby** [comment]
@Blusand 感觉问题并不是出在平板的设置，而是你站点的服务器带宽可能太低了，资源还没有加载完成，我是用桌面端也加载了很久。建议再测试一下。

**Comment by Blusand** [comment]
我的平板上浏览[另一位大佬的网站](https://lixingyong.com/2020/07/15/chevereto)也是无法渲染出来，但是手机和电脑倒是很快

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/157475579-f397b9a0-9470-4b65-9beb-cbb13e5c12c6.png)

好吧，我自己的也无法显示。我的 iOS 设备同样无法显示，应该是 Safari 内核导致的。

**Comment by Blusand** [comment]
> ![image](https://user-images.githubusercontent.com/21301288/157475579-f397b9a0-9470-4b65-9beb-cbb13e5c12c6.png)
> 
> 好吧，我自己的也无法显示。我的 iOS 设备同样无法显示，应该是 Safari 内核导致的。

哦哦，那看来是没办法了，非常感谢

**Comment by ruibaby** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/21301288/157476799-f8a6afd9-e869-4148-9d46-e77b129685a1.png">

已经调试出应该是 JS 不兼容的问题，我将尝试修复此问题。

**Comment by LIlGG** [comment]
已计划在下个版本删除迷你代码块，并同步修复此问题。
