### ISSUE TITLE
打开文章归档后之前月份的文章不会显示

### ISSUE THREAD

**Issue by LingluoYusa** [LIlGG/halo-theme-sakura#238]
打开文章归档后之前月份的文章不会显示，需要点击一下本月的文章然后返回文章归档页面，再次点击日期才会弹出之前的文章

**Comment by ITBoy-China** [comment]
我也是这个问题，想着在issue上能不能找到解决方案，然后就有人提了

**Comment by LIlGG** [comment]
增加迷你代码块时引入的 BUG。将在下个版本中删除迷你代码块
