### ISSUE TITLE
代码块在Safari下无效

### ISSUE THREAD

**Issue by maolog** [LIlGG/halo-theme-sakura#240]
如图，使用Microsoft EDGE浏览器正常显示
[![2022-03-18-9.20.58.png](https://yys.ink/images/2022/03/18/2022-03-18-9.20.58.png)](https://yys.ink/image/yFL)

使用Safari浏览器则代码块无渲染。
[![2022-03-18-9.21.28.png](https://yys.ink/images/2022/03/18/2022-03-18-9.21.28.png)](https://yys.ink/image/unu)

**Comment by ruibaby** [comment]
已知问题，你暂时可以使用 next 分支的代码。
