### ISSUE TITLE
使用二级分组时没有对齐

### ISSUE THREAD

**Issue by LingluoYusa** [LIlGG/halo-theme-sakura#241]
如图所示，添加二级分组时会挡住下面的横条并右偏

![1](https://user-images.githubusercontent.com/87465762/159392783-194bc66e-a87f-4412-a84c-b912caa87fc0.png)

![2](https://user-images.githubusercontent.com/87465762/159392787-feb437bc-a60f-4542-a26f-524a6e79331c.png)

**Comment by LIlGG** [comment]
2.0.0-beta.2 版本已经修复此问题，此 issue 关闭 #340
