### ISSUE TITLE
音乐播放器不在左下角显示

### ISSUE THREAD

**Issue by xiongtete0519** [LIlGG/halo-theme-sakura#243]
<img src="https://user-images.githubusercontent.com/66518135/160347733-82e6627f-2270-488e-830f-0db49af49ad3.png">
我把最后这个id写在了下面这里，
<img src="https://user-images.githubusercontent.com/66518135/160347871-0486bda2-2354-4343-bbe7-2430dd816a32.png">
而且插件功能也开启了，如下：
<img src="https://user-images.githubusercontent.com/66518135/160347941-80154807-1ff9-46b1-b398-b528fc24e3ee.png">
但是我的博客主页面左下角不显示音乐播放器。

**Comment by LIlGG** [comment]
歌单 ID 不允许为私密歌单。可以检查一下

**Comment by xiongtete0519** [comment]
感谢作者，歌单确实是私密的，问题已经解决。厉害啊！

**Comment by xiongtete0519** [comment]
感谢作者，歌单确实是私密的，问题已经解决。厉害！！！
