### ISSUE TITLE
halo 文章目录定位问题

### ISSUE THREAD

**Issue by Doomwatcher2004** [LIlGG/halo-theme-sakura#246]
长文章定位问题

![image-20220402213752883](https://cdn.jsdelivr.net/gh/Doomwatcher2004/my-image-host@master/%20img%20/image-20220402213752883.png)

**Comment by LIlGG** [comment]
当前的 release 版本（1.3.3）确实会存在这个问题，在 next 版本中将会解决目前已知的问题。
