### ISSUE TITLE
背景音乐设置的背景色有问题

### ISSUE THREAD

**Issue by MoeElaina** [LIlGG/halo-theme-sakura#247]
![image](https://user-images.githubusercontent.com/101780750/161396174-de1d357d-f08c-4b64-bffa-dc523cdb5057.png)
如图，请优化一下！

**Comment by LIlGG** [comment]
此处选择器属于 Halo 功能。与主题无关。

**Comment by LIlGG** [comment]
有关问题可以前往 [@halo](https://github.com/halo-dev/halo) 进行提问，此 issue 关闭
