### ISSUE TITLE
首页个性签名框不能自动缩放

### ISSUE THREAD

**Issue by mashirotj** [LIlGG/halo-theme-sakura#248]
如图，签名过长则无法完全显示
![Snipaste_2022-04-04_17-56-06.jpg](https://s2.loli.net/2022/04/04/y8Hb6Capu4Ej1SI.jpg)

**Comment by mashirotj** [comment]
给个建议，边框设置一个初始长度，文字长度和边框的距离大于某个固定值时，边框不动
小于固定值的时候边框延长，使距离和固定值相等
不知道代码层面实现是否简单

**Comment by mashirotj** [comment]
> 已知问题，目前还没想好到达最大长度之后要怎么处理。

给个建议，边框设置一个初始长度，文字长度和边框的距离大于某个固定值时，边框不动
小于固定值的时候边框延长，使距离和固定值相等
不知道代码层面实现是否简单

**Comment by LIlGG** [comment]
> > 已知问题，目前还没想好到达最大长度之后要怎么处理。
> 
> 给个建议，边框设置一个初始长度，文字长度和边框的距离大于某个固定值时，边框不动 小于固定值的时候边框延长，使距离和固定值相等 不知道代码层面实现是否简单，直接换行太僵硬了

感谢提供的建议，已经在昨天发布的 1.3.4 版本中修复这个 BUG。

**Comment by mashirotj** [comment]
> > > 已知问题，目前还没想好到达最大长度之后要怎么处理。
> > 
> > 
> > 给个建议，边框设置一个初始长度，文字长度和边框的距离大于某个固定值时，边框不动 小于固定值的时候边框延长，使距离和固定值相等 不知道代码层面实现是否简单，直接换行太僵硬了
> 
> 感谢提供的建议，已经在昨天发布的 1.3.4 版本中修复这个 BUG。

![Snipaste_2022-04-06_12-06-45.jpg](https://s2.loli.net/2022/04/06/sPz1fhcQWwl6mbZ.jpg)
好像修复的不是很理想

**Comment by LIlGG** [comment]
> ![Snipaste_2022-04-06_12-06-45.jpg](https://camo.githubusercontent.com/8c2b70f1767a55b059dcca0dea5b4037cc9c6dace5da62933d1d89757c3ba268/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30342f30362f73507a316668635157776c366d625a2e6a7067) 好像修复的不是很理想，意思是签名不能过长了吗，过长就无法显示？

是的，为了保证整体美观度。毕竟我这里是要考虑大部分博客的样式。毕竟不能允许无限制延长，否则个性签名一旦过长，界面将非常难看。而如果限制最大长度，这样同限制长度也并没有什么区别。
所以如果个人博客有要求，比如你的文本过长，那么可以写入以下 CSS 来实现个性化。
在 `主题设置 - 基本设置 - css` 加入如下 css 试试
```
.header-info {
  width: 70%
}
```
