### ISSUE TITLE
音乐播放那里太小了感觉，希望可以自定义位置大小，再弄个加载完页面就自动播放音乐的按钮

### ISSUE THREAD

**Issue by handsomeZZD** [LIlGG/halo-theme-sakura#25]

**Comment by LIlGG** [comment]
大小建议自行调整CSS样式来实现，毕竟属于样式的东西每个人的审美不一样！不太好调整
加载完页面就播放音乐对于用户来说实在是一个不好的体验，尤其是移动端基本上都是禁止自动播放的，即使你配置了。建议考虑一下。不过既然你有这个需求，我就考虑增加一个自动播放音乐的设置。
