### ISSUE TITLE
能否设置对单独文章禁止评论？

### ISSUE THREAD

**Issue by lvtenghui** [LIlGG/halo-theme-sakura#251]
不知道能否通过设置文章元数据来控制能否评论

**Comment by LIlGG** [comment]
Halo 默认是支持对文章控制评论的
![image](https://user-images.githubusercontent.com/31335418/162587283-b727978b-33c5-42d5-9cac-1810be89b96c.png)

**Comment by lvtenghui** [comment]
咦 感谢感谢！ 一直没看到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月10日(星期天) 凌晨2:35
收件人: ***@***.***&gt;; 
抄送: "Lv ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LIlGG/halo-theme-sakura] 能否设置对单独文章禁止评论？ (Issue #251)





 
Halo 默认是支持对文章控制评论的
