### ISSUE TITLE
音乐播放器加载不出来

### ISSUE THREAD

**Issue by webchuanzhou** [LIlGG/halo-theme-sakura#253]
![image](https://user-images.githubusercontent.com/32433532/162886507-921315f1-69cc-4e59-9dfe-43f9a2903513.png)

是哪里还需要设置吗？

**Comment by webchuanzhou** [comment]
![image](https://user-images.githubusercontent.com/32433532/162898310-789bee95-c187-4466-ad99-2e1d5808f062.png)

左下角无法出现播放器

**Comment by LIlGG** [comment]
查看填写的歌单是否为 `我喜欢` 或者私密歌单。 上述两歌单无法在未登录的状态下获取，因此接口无法读取。

**Comment by webchuanzhou** [comment]
需要登录？  在哪里登录

**Comment by LIlGG** [comment]
> 需要登录？ 在哪里登录

本接口不允许登录。并且提供帐密给第三方接口是不太赞成的行为。因此请选择非 `我喜欢` 及私密歌单。

**Comment by LIlGG** [comment]
> 无法增加自定义歌曲的吗？我本地上传首歌上去

主题是不能做到这种东西的。Halo 目前不支持

**Comment by wzry623090** [comment]
你填的是网易云网址歌单最后面ID的数字，应该填网易云最前面ID 数字，这是我刚发现的，点后面的id 后面的数字还是别人的歌单，只有最前面的ID是你本人的，创建的歌单

**Comment by xiaofengjue** [comment]
你好我也遇到了这个问题，这个我的歌单分享链接，https://y.music.163.com/m/playlist?id=5425916639&userid=556998213&creatorId=556998213，是非私密的，浏览器打开也能看到歌曲列表，我填入的歌单id是5425916639，但是播放器也是没有出现，我的网站是 https://sillage.wang/

**Comment by LIlGG** [comment]
> 你好我也遇到了这个问题，这个我的歌单分享链接，[https://y.music.163.com/m/playlist?id=5425916639&userid=556998213&creatorId=556998213，](https://y.music.163.com/m/playlist?id=5425916639&userid=556998213&creatorId=556998213%EF%BC%8C) 是非私密的，浏览器打开也能看到歌曲列表，我填入的歌单id是5425916639，但是播放器也是没有出现，我的网站是 https://sillage.wang/

目前出现这个原因是因为接口问题，暂时还没有时间去做处理。

**Comment by wzry623090** [comment]
我能用，我是通过播放器代码的方法实现
 更新一下那个嵌入音乐播放代码，那个，早就用不了了

你可以暂时先用这个

<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width="100%" height="450" src="//music.163.com/outchain/player?type=0&id=填写歌单id &auto=1&height=430"></iframe>
