### ISSUE TITLE
页面显示问题

### ISSUE THREAD

**Issue by yikexiaoyao** [LIlGG/halo-theme-sakura#254]
![1](https://user-images.githubusercontent.com/36374114/163314796-21128945-27b3-429b-bbd8-d1ed0965f53b.png)
![2](https://user-images.githubusercontent.com/36374114/163314805-2488f95d-7a00-4b0d-b98e-79aeb95af2ba.png)
$ 符号删了改改了删完全没有任何改变，只会显示成这样，完全达不到指数表达式的预期效果，求帮忙看一下，谢谢

**Comment by yikexiaoyao** [comment]
图1 是文章编辑页面的书写和预览效果，图2 是文章页面的实际展现效果

**Comment by ruibaby** [comment]
应该是没有开启 Katex 渲染，这需要你使用最新的主题版本以及 Halo 版本。然后在主题设置有 Katex 渲染的选项。

**Comment by LIlGG** [comment]
使用最新版本的 Sakura 可以解决此问题。
