### ISSUE TITLE
文章阅读数统计问题

### ISSUE THREAD

**Issue by julylLes** [LIlGG/halo-theme-sakura#255]
# 版本
halo :1.5.2
halo-theme-sakura:1.3.4

# 问题
多次刷新文章，阅读量也跟着上去。

**Comment by ruibaby** [comment]
这属于 Halo 的问题，与主题无关。参考：https://github.com/halo-dev/halo/issues/1756

**Comment by MatchLittle** [comment]
我的2.15版本，使用的是九涯的dream主题，文章阅读数量不会变化，无论我是更换设备还是刷新页面，新发布的和旧的文章的阅读数量都不会变化，这个是什么问题呢？

**Comment by lakersWin** [comment]
@MatchLittle 我也一样，你的问题解决了吗
