### ISSUE TITLE
想问下主题7“bing”和主题8“dark”的区别在哪

### ISSUE THREAD

**Issue by Tianchen627** [LIlGG/halo-theme-sakura#258]
试了几个不同的终端，发现主题7和主题8显示效果都一样~看主题设置里的选项，主题7的功能好像是拉去必应的图片？

**Comment by LIlGG** [comment]
是的，主题 7 是去拉取必应的图片，目前接口似乎不能正常返回结果了，后面会看一下。 主题8 默认情况下是黑夜模式所用。

**Comment by monkeyKinn** [comment]
> 
这个bing 后台的那个接口变成广告了  偶尔点进去跳进18禁网站

**Comment by monkeyKinn** [comment]
自己替换掉连接后 回到切换主题还是默认关灯

**Comment by monkeyKinn** [comment]
> 是的，主题 7 是去拉取必应的图片，目前接口似乎不能正常返回结果了，后面会看一下。 主题8 默认情况下是黑夜模式所用。

https://api.1314.cool/bingimg 网上搜来的几口 可以换 不过为了防止他再吃饭 可以考虑自己搭一个

**Comment by LIlGG** [comment]
> https://api.1314.cool/bingimg 网上搜来的几口 可以换 不过为了防止他再吃饭 可以考虑自己搭一个

beta.2 已经使用上述接口作为默认接口，不过暂不考虑自建。此 issue 关闭，如果还有其他问题可以打开
