### ISSUE TITLE
comment_gravatar_source配置不生效

### ISSUE THREAD

**Issue by sherlocky** [LIlGG/halo-theme-sakura#259]
comments.ftl 文件中
  "gravatarSource": "${settings.comment_gravatar_source!}", 这行有bug

settings.comment_gravatar_source 在数据库中有值，读取不到

**Comment by LIlGG** [comment]
1.3.4 版本之后推荐使用 `博客设置 - 评论设置 - gravatar` 来设置。主题内设置的不再支持。
