### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by kfyidrig** [LIlGG/halo-theme-sakura#26]
首页背景图上面有那个纹理，好好看，怎么实现的啊，我是个css初学者，麻烦告诉我下

**Comment by LIlGG** [comment]
> 首页背景图上面有那个纹理，好好看，怎么实现的啊，我是个css初学者，麻烦告诉我下

实际上就是一个像素的图片。然后x轴y轴重复就可以了。。 没什么特别的 唯一需要注意的就是设置一下z-index，让它在最上方就行

**Comment by kfyidrig** [comment]
像素照片？？方便发我下吗，感觉像在做ppt，谢谢啦

**Comment by LIlGG** [comment]
![grid.png](https://cdn.jsdelivr.net/gh/LIlGG/cdn@1.0.1/img/Sakura/images/grid.png)
```
https://cdn.jsdelivr.net/gh/LIlGG/cdn@1.0.1/img/Sakura/images/grid.png
```

**Comment by kfyidrig** [comment]
这样填几千个，不会影响性能吗，为啥不直接弄个更大分辨率的放到背景图片上面

**Comment by LIlGG** [comment]
> 这样填几千个，不会影响性能吗，为啥不直接弄个更大分辨率的放到背景图片上面

你弄一张大图也可以。 但我个人还是觉得小图比较适合。
1. 就算重复十几万像素点 对于现代电脑来说也是可以忽略不计的
2. 使用大图和使用小图，在渲染上来说是一样的。甚至更大分辨率的图像需要渲染的像素点更多
3. 从网络请求一张大图，远比一张小图速度慢的多

不过现代浏览器，这两个差别也不会很大。实际上你用哪种方式都行。但如果用大图，网速慢的时候，可能会很突兀
