### ISSUE TITLE
QQ音乐播放什么时候有啊呜呜呜

### ISSUE THREAD

**Issue by Musicminion** [LIlGG/halo-theme-sakura#262]
想要qq音乐

**Comment by LIlGG** [comment]
QAQ. 我也想知道。。。同求

**Comment by Musicminion** [comment]
> QAQ. 我也想知道。。。同求

我记得有另外的一个主题支持的QQ的什么的都支持
就是不知道该怎么搬过来.....

**Comment by LIlGG** [comment]
> > QAQ. 我也想知道。。。同求
> 
> 我记得有另外的一个主题支持的QQ的什么的都支持 就是不知道该怎么搬过来.....

哪个主题？QQ 的我倒是写了一部分，就是还没写完，搁浅了，后续拿出来再继续填坑。。

**Comment by Musicminion** [comment]
> > > QAQ. 我也想知道。。。同求
> > 
> > 
> > 我记得有另外的一个主题支持的QQ的什么的都支持 就是不知道该怎么搬过来.....
> 
> 哪个主题？QQ 的我倒是写了一部分，就是还没写完，搁浅了，后续拿出来再继续填坑。。

不不不，我是说官方主题里面给的另外的一个主题，hhh

**Comment by LIlGG** [comment]
目前 2.0.0-Beta.2 版本支持 Meting 接口，因此理论上可以支持 QQ 音乐，此 issue 关闭。

**Comment by Musicminion** [comment]
芜湖芜湖！
