### ISSUE TITLE
评论作者头像部分清晰度低

### ISSUE THREAD

**Issue by ASTqiaomu** [LIlGG/halo-theme-sakura#263]
前几天刚搭好博客，使用评论功能的时候，发现自动拉取QQ号获取到的头像清晰度较低，QQ原头像尺寸是足够清晰的。
找了一下，元素是class="commentator"。

**Comment by LIlGG** [comment]
目前应该是不能使用 QQ 头像的。

**Comment by ASTqiaomu** [comment]
![](https://storage-bucket-1311694464.cos.ap-chengdu.myqcloud.com/images/2022-5-9/QQ%E6%88%AA%E5%9B%BE20220509154509.png)
我测试是能用的，但是清晰度差

**Comment by Yhcrown** [comment]
我这里也是 拉取的时候可以获得头像，但是发布之后的评论就没有头像了。

**Comment by MutBlackTea** [comment]
> 我这里也是 拉取的时候可以获得头像，但是发布之后的评论就没有头像了。

对博客设置里的gravartar换源即可

**Comment by LIlGG** [comment]
QQ 头像只支持拉取而不支持保存，因此是无用选项。Halo 也没有提供此类解决方案，因此不建议使用 QQ 头像。
