### ISSUE TITLE
首页个性签名问题

### ISSUE THREAD

**Issue by Simple-Stark** [LIlGG/halo-theme-sakura#264]
更新  1.3.4 版本之后
首页的个性签名未居中对齐
网址：https://simplestark.com

现象：
![fa6dacd036821ea6446f9522033652e](https://user-images.githubusercontent.com/61400566/167377463-49164b7f-ee76-40c9-b910-ecb2ac772373.png)
问题可能存在的地方：
![8f47558e230e7f8245ae81e3e14b321](https://user-images.githubusercontent.com/61400566/167377541-561a8cfc-a401-4118-afca-920d21e751e6.png)

**Comment by LIlGG** [comment]
fix #273
