### ISSUE TITLE
cdn貌似又挂了

### ISSUE THREAD

**Issue by Cloudkkk** [LIlGG/halo-theme-sakura#267]
cdn.jsdelivr.net 请求全部都超时了

**Comment by LIlGG** [comment]
cdn.jsdelivr.net 本身已经不再支持使用。 #206 。在 1.3.4 版本中新增了其他的 CDN，可以考虑使用

**Comment by Cloudkkk** [comment]
请问现在控制台打不开  应该如何升级主题版本

**Comment by LIlGG** [comment]
> 请问现在控制台打不开 应该如何升级主题版本

意思后端无法登陆吗？后端无法登陆的话就不能升级主题。你可以试试下载主题之后，将主题解压并放到服务器 ~/halo 目录对应的主题资源下。但这种操作不能保证配置项成功修改

**Comment by Cloudkkk** [comment]
升级成功了 谢谢
