### ISSUE TITLE
音乐播放器无法使用

### ISSUE THREAD

**Issue by 91Metis** [LIlGG/halo-theme-sakura#270]
作者你好，咱们的这个主题的播放器好像有点问题，关于播放器的选项都设置好以后，刷新后不显示播放器，也没有播放歌曲。歌单为公开，且非我喜欢歌单。

[歌单地址](https://music.163.com/#/playlist?id=7455734959)

![](https://pic.imgdb.cn/item/628f719609475431295778b2.png)

![](https://pic.imgdb.cn/item/628f719609475431295778b6.png)

**Comment by LIlGG** [comment]
目前发现接口需要校验，待修复即可

**Comment by 91Metis** [comment]
> 



> 目前发现接口需要校验，待修复即可

收到，感谢回复！

**Comment by LIlGG** [comment]
已修复~

**Comment by 91Metis** [comment]
> 已修复~

感谢作者！
