### ISSUE TITLE
404界面的小猫咪钻鱼缸无法加载

### ISSUE THREAD

**Issue by michaelchen644** [LIlGG/halo-theme-sakura#272]
![image](https://user-images.githubusercontent.com/66155014/173361687-50eb8617-ada5-4347-9d3f-3aaa5b63384d.png)

如图，重装了一下博客，可爱小猫咪不见了。CDN和本地都不行，换了个主机也不行。应该是出bug了。

![image](https://user-images.githubusercontent.com/66155014/173362426-92ebf1ef-36fe-49f2-84cf-3279c84b8fe4.jpeg)

**Comment by LIlGG** [comment]
是否添加了额外的 JS 导致的？可以将博客地址发一下，方便我去定位问题~
