### ISSUE TITLE
如何使用自己的cdn进行加速

### ISSUE THREAD

**Issue by MiracleHYH** [LIlGG/halo-theme-sakura#274]
免费cdn有时卡顿感比较明显，请问是否能够使用自己的cdn进行加速，又该如何设置呢

**Comment by LIlGG** [comment]
可以将 `主题设置 - 其他 - 资源使用 CDN` 关闭，这时主题内的大部分资源将会使用自己的服务器资源，再将 CDN 绑定到自己的域名即可。

**Comment by MiracleHYH** [comment]
十分感谢，修改后速度有明显提升。
