### ISSUE TITLE
首页的社交媒体气泡框里怎么添加演示站里那样的文字啊

### ISSUE THREAD

**Issue by ANYNC** [LIlGG/halo-theme-sakura#275]
在后台设置里面没有找到对应的添加文字选项

**Comment by LIlGG** [comment]
文本取自个人资料内的个人说明
![image](https://user-images.githubusercontent.com/31335418/178424276-91e68306-6327-440c-ac40-f9f12734c838.png)

**Comment by ANYNC** [comment]
> 



> 文本取自个人资料内的个人说明 ![image](https://user-images.githubusercontent.com/31335418/178424276-91e68306-6327-440c-ac40-f9f12734c838.png)

好的，谢谢
