### ISSUE TITLE
关闭行号后主题切换出现问题

### ISSUE THREAD

**Issue by h1sk1** [LIlGG/halo-theme-sakura#278]
在文章页中关闭行号后，首次访问页面不会出现切换主题(SCHEME TOOL)，主题也不会加载

**Comment by LIlGG** [comment]
测试之后并没有这种情况，可以给我你的博客地址吗？

**Comment by wcytk** [comment]
> 测试之后并没有这种情况，可以给我你的博客地址吗？

感谢回复，我的博客地址是https://blog.wcytk.com

**Comment by LIlGG** [comment]
使用你提供的博客地址，也没有复现该问题。首次访问也加载了主题。

**Comment by wcytk** [comment]
> 使用你提供的博客地址，也没有复现该问题。首次访问也加载了主题。

感谢您的验证
但是我刚刚在所有设备上都访问了一下，确实存在这个问题

具体情况如下图所示，在首次访问或者刷新之后，主题无法加载。点进一个页面后就能加载出来
![issue1](https://images.all4guide.com/images/data/2022/07/20/issue1b0177ec9d6c76308.gif)
