### ISSUE TITLE
遇到的一些问题，提一下，希望越来越好

### ISSUE THREAD

**Issue by yuanxiuyao** [LIlGG/halo-theme-sakura#28]
1. 处理滚动条右侧（写的东西是两行或三行，代码块显示的时候变成了四行，导致滚动条莫名出现）
2. 友链（友人帐）页面，添加背景图后背景颜色会变成灰色
3. （在不使用页面head图片情况下）我新增了关于 和 留言板两个页面时，标题会自带两个中括号，就跟文章的标题一样（这个属于个人强迫症，其他自带的页面标题没有中括号）

**Comment by LIlGG** [comment]
@yuanxiuyao  第2个和第3个问题我排查过了， 确实是我这边疏忽导致的BUG，已经解决了。 但第1个问题没有复现，看你的博客也没看出来，所以暂时没改动。
你可以重新在线更新一下新的版本
如果你能提供关于问题一，你修复后和修复前的区别截图就更好了！！

**Comment by yuanxiuyao** [comment]
之前提的问题好像都没有了，我发现了一些新的
1. 主题的文章页 开启 “文章分享”，部分文章详情页会有js报错，导致页面部分功能加载不出来（例如head图和代码块样式）
参考[https://www.xiaoyaoba.top/archives/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0java%E4%B8%AD%E7%9A%84%E9%94%81](url)

2. 用户评论时，选择qq（有qq自带的头像），评论后头像就变成别的了，这个算bug吗

3. 博主回复评论时，能不能把博主的头像显示在评论列表里

**Comment by LIlGG** [comment]
> 之前提的问题好像都没有了，我发现了一些新的
> 
> 1. 主题的文章页 开启 “文章分享”，部分文章详情页会有js报错，导致页面部分功能加载不出来（例如head图和代码块样式）
>    参考[https://www.xiaoyaoba.top/archives/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0java%E4%B8%AD%E7%9A%84%E9%94%81](url)
> 2. 用户评论时，选择qq（有qq自带的头像），评论后头像就变成别的了，这个算bug吗
> 3. 博主回复评论时，能不能把博主的头像显示在评论列表里

这， 天生吸引BUG体质？第一个确实是个BUG，我会研究一下。
第二个倒不是BUG，在 [开发日志 7/5](https://lixingyong.com/s/halo-theme-sakure#toc-head-13) 里面有提到，由于官方数据库目前不支持评论存取额外数据，因此我这边只是预装了拉取QQ头像的功能。实际上还不能生效。等官方支持额外数据就行了
第三个，还是比较建议使用通用的gravata头像，因为评论组件实际上是使用vue采用rest接口写的，而接口是透明的，也就意味着没有博主的个人信息，如果强行将博主信息传到评论组件里又不是很好的做法。

**Comment by yuanxiuyao** [comment]
那我先把  文章分享关闭了，不然代码块  不太好看

**Comment by LIlGG** [comment]
> 那我先把 文章分享关闭了，不然代码块 不太好看

这，别急 我这边没有复现这个BUG的 等我修复完毕你再关吧 哈哈

**Comment by LIlGG** [comment]
> 那我先把文章分享关闭了，不然代码块不太好看

我这里新提交一次，你更新后看看还报不报错了

**Comment by yuanxiuyao** [comment]
还是报错，我是直接在线更新的；
Uncaught Error: code length overflow. (580>528)
    at Function.b.createData (qrcode.min.js:1)
    at b.makeImpl (qrcode.min.js:1)
    at b.getBestMaskPattern (qrcode.min.js:1)
    at b.make (qrcode.min.js:1)
    at QRCode.makeCode (qrcode.min.js:1)
    at new QRCode (qrcode.min.js:1)
    at Object.PE (app.js?ver=2.0.6.170420:764)
    at HTMLDocument.<anonymous> (app.js?ver=2.0.6.170420:936)
    at k (jquery.min.js?ver=2.0.6.170420:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=2.0.6.170420:2)

看错误信息好像是生成二维码的时候出了问题，“文章分享”是开启之后才会报错，文章分享应该是有方式的，不知道你那边 文章分享的具体链接方式  是不是可以生成

**Comment by LIlGG** [comment]
> 还是报错，我是直接在线更新的；
> Uncaught Error: code length overflow. (580>528)
> at Function.b.createData (qrcode.min.js:1)
> at b.makeImpl (qrcode.min.js:1)
> at b.getBestMaskPattern (qrcode.min.js:1)
> at b.make (qrcode.min.js:1)
> at QRCode.makeCode (qrcode.min.js:1)
> at new QRCode (qrcode.min.js:1)
> at Object.PE (app.js?ver=2.0.6.170420:764)
> at HTMLDocument. (app.js?ver=2.0.6.170420:936)
> at k (jquery.min.js?ver=2.0.6.170420:2)
> at Object.fireWith [as resolveWith] (jquery.min.js?ver=2.0.6.170420:2)
> 
> 看错误信息好像是生成二维码的时候出了问题，“文章分享”是开启之后才会报错，文章分享应该是有方式的，不知道你那边 文章分享的具体链接方式 是不是可以生成

还是报错的吗？你先关闭你的文章分享吧。 我这边本地复现再测测。这个报错是由于使用的生成二维码插件导致的。 他的插件原本就有这个BUG，而且作者已经7年没有更新了吧。我会寻找合适的方案来解决

**Comment by yuanxiuyao** [comment]
好

**Comment by LIlGG** [comment]
> 好

我这里采用了新的二维码库来生成二维码，你可以再次更新尝试一下。 另外如果你有使用cdn，记得一定要重新刷新一下缓存，否则会执行缓存版本

**Comment by yuanxiuyao** [comment]
巧了，你也加班

**Comment by yuanxiuyao** [comment]
问题解决了

**Comment by LIlGG** [comment]
> 巧了，你也加班

哈哈 这不是正常情况嘛。 搞搞博客，随便逛逛 也还挺好的

**Comment by LIlGG** [comment]
> 问题解决了

ok 解决了就行 如果有新的问题就再提出来。 目前主题还需要再多多完善

**Comment by yuanxiuyao** [comment]
> > 问题解决了
> 
> ok 解决了就行 如果有新的问题就再提出来。 目前主题还需要再多多完善

好的
