### ISSUE TITLE
评论表情包加载不出来

### ISSUE THREAD

**Issue by bebetterest** [LIlGG/halo-theme-sakura#286]
rt，评论表情包加载不出来，请问有什么解决办法吗？

<img width="930" alt="截屏2022-10-02 01 06 40" src="https://user-images.githubusercontent.com/105866222/193420369-bc54e36b-246c-4a66-9d37-692e9f263292.png">

**Comment by LIlGG** [comment]
更改主题设置 -> 其他 -> CDN 地址，替换成 `takagiの公共资源库` 试试

**Comment by bebetterest** [comment]
感谢
