### ISSUE TITLE
大佬，能分享一下音乐播放器组件那块的代码吗？

### ISSUE THREAD

**Issue by xTwos** [LIlGG/halo-theme-sakura#288]

**Comment by xTwos** [comment]
如题

**Comment by xTwos** [comment]
引入：    
<script src="https://lixingyong.com/themes/LIlGG_Sakura/source/lib/APlayer/APlayer.min.js" defer></script>
	<script src="https://lixingyong.com/themes/LIlGG_Sakura/plugins/aplayer/js/index.js" defer></script>
    <link rel="stylesheet" href="https://lixingyong.com/themes/LIlGG_Sakura/source/lib/APlayer/APlayer.min.css" media='all'>

html：
    
    <div id="aplayer-float" style="z-index: 100;" class="aplayer" data-global="true" data-id="7613959017" data-server="netease" data-type="playlist" data-fixed="true" data-preload="none" data-order="random" data-theme="#ffa500" data-autoplay="false"></div>

**Comment by LIlGG** [comment]
查看 https://github.com/DIYgod/APlayer，主题内使用的是此播放器，你可以参考一下。主题做的仅仅是对播放器的属性嵌入到了配置内，另外开放了一个自定义 API。

**Comment by xTwos** [comment]
谢谢大佬！###
