### ISSUE TITLE
建议：标签

### ISSUE THREAD

**Issue by RookieXv** [LIlGG/halo-theme-sakura#29]
感谢博主做出这么优秀的主题，辛苦啦！希望后面标签页可以做成彩色的，根据标签下文章数量的大小显示等比例的标签文字，类似标签云的样子。现在的太拥挤了，也没什么样式

**Comment by LIlGG** [comment]
> 感谢博主做出这么优秀的主题，辛苦啦！希望后面标签页可以做成彩色的，根据标签下文章数量的大小显示等比例的标签文字，类似标签云的样子。现在的太拥挤了，也没什么样式

目前是存在标签云的。下方的标签页也确实是彩色的。。 不过对于拥挤这个我今天做了调整，你可以更新一下

**Comment by RookieXv** [comment]
好的，感谢！！

**Comment by RookieXv** [comment]
更新了怎么没有demo网站的效果呀，还是没有样式，也没用标签云😭😭😭

**Comment by LIlGG** [comment]
> 更新了怎么没有demo网站的效果呀，还是没有样式，也没用标签云😭😭😭

是否使用了cdn？

**Comment by RookieXv** [comment]
> > 更新了怎么没有demo网站的效果呀，还是没有样式，也没用标签云😭😭😭
> 
> 是否使用了cdn？

啥？好像没有修改什么

**Comment by LIlGG** [comment]
> > > 更新了怎么没有demo网站的效果呀，还是没有样式，也没用标签云😭😭😭
> > 
> > 
> > 是否使用了cdn？
> 
> 啥？好像没有修改什么

如果使用了cdn 的话，需要去刷新CDN缓存。
方便的话可以把你的博客地址发一下吗？

**Comment by RookieXv** [comment]
https://www.liuwenxu.com

**Comment by LIlGG** [comment]
> https://www.liuwenxu.com

是标签吗？我看你标签是没有什么问题的。 可能是我对你的需求理解有点误差。 今天调整了上方标签云的宽度。

至于标签颜色，默认是随机颜色。彩色的话也不是很难，但问题是如何保证两个随机色差不是太大就是个问题了。 。字体实际上倒不会影响太多，有的太大有的太小反而很突兀，如果要说按数量排序还行。

确实是个好的建议，但目前的标签虽然不是特别好看却也足够使用了，还有优先级更高的东西，美化标签可能会放到1.2.0版本出来之后了。望理解。另外建议随机色调不要调太低，默认的实际上是我研究了很久，觉得最好看的一套色调了

**Comment by RookieXv** [comment]
不好意思，估计是有缓存的原因，我清除了一下，正常显示了，非常感谢您的帮助！我没有质疑它，挺好看的，谢谢！！

**Comment by LIlGG** [comment]
> 不好意思，估计是有缓存的原因，我清除了一下，正常显示了，非常感谢您的帮助！我没有质疑它，挺好看的，谢谢！！

嗯嗯 没有没有 上面的确实给了我启发，实际上将标签做成和你说的那种彩色的就挺好的。 实际上如果目前有时间我会优先做这个，确实感觉会好看些。 不过任务堆积的有点多，只能暂时先把样式调整的东西放一下

**Comment by RookieXv** [comment]
加油，期待更好的sakura

**Comment by LIlGG** [comment]
> 加油，期待更好的sakura

非常感谢！！！
