### ISSUE TITLE
使用外部的CDN后，看板娘无法加载

### ISSUE THREAD

**Issue by lukeewin** [LIlGG/halo-theme-sakura#291]
你好，配置外部的CDN后，看板娘无法显示，看控制台有报错信息，报错信息如下所示。
<img width="554" alt="屏幕截图 2022-10-17 222050" src="https://user-images.githubusercontent.com/41370685/196202073-d7204916-0478-4631-bf73-68e026371b21.png">
同时后台管理系统中无法正常使用评论的查询功能，无论是按照关键词还是评论状态，都无法正常使用，比如，选择显示待审核状态，但是还是会把所有评论都显示出来。

**Comment by LIlGG** [comment]
主题 2.x 重构之后将不再支持 1.x 相关功能。 待 #340 完成后此 Issue 将关闭。
另外看板娘功能在 Halo 2.x 中以插件支持，详见 https://github.com/LIlGG/plugin-live2d
