### ISSUE TITLE
关于首页文章列表的一些问题

### ISSUE THREAD

**Issue by cjhxc** [LIlGG/halo-theme-sakura#293]
如何修改可以使得文章框内颜色是纯白而不是跟背景一样
![Snipaste_2022-10-23_18-40-38](https://user-images.githubusercontent.com/73411853/197387903-7b9dae56-1fc2-4542-896e-4c33c2cbdb8f.jpg)
类似这种效果
![Snipaste_2022-10-23_18-46-37](https://user-images.githubusercontent.com/73411853/197387923-c4baa07b-22be-46d7-9dee-00d3eb69f543.jpg)

**Comment by LIlGG** [comment]
了解，这块确实可以进行优化，感谢建议。
