### ISSUE TITLE
移动端不显示右下角切换主题

### ISSUE THREAD

**Issue by YeJoe** [LIlGG/halo-theme-sakura#295]
移动端不显示右下角切换主题

```
@media (max-width:800px) {
	.changeSkin-gear span:before {
		content: ""
	}

	.changeSkin i {
		font-size: 20px
	}

	.changeSkin-gear i {
		font-size: 20px
	}
}
```

不知道上面的是不是控制移动端右下角显示gear图标的css。
如果是的话我这边关了浏览器的广告屏蔽也不显示。

- ios alook浏览器 safari浏览器都不行 
- 安卓via浏览器也没显示

在全局尝试增加背景颜色，大小也没生效。

![IMG_5090](https://user-images.githubusercontent.com/48477050/199640681-30f1b0f3-39e6-4a32-8c6b-4cec1d85a893.jpg)

请问是否默认不显示？如果要显示，在全局应该怎么配置

**Comment by LIlGG** [comment]
移动端不支持切换主题及显示看板娘。

**Comment by YeJoe** [comment]
> 移动端不支持切换主题及显示看板娘。

后续是否可以把夜间模式单独放到页面头部区域呢？毕竟夜间模式在切换主题里面，如果移动端不支持切换的话，夜晚就没法给博客加夜间模式

**Comment by LIlGG** [comment]
> > 移动端不支持切换主题及显示看板娘。
> 
> 后续是否可以把夜间模式单独放到页面头部区域呢？毕竟夜间模式在切换主题里面，如果移动端不支持切换的话，夜晚就没法给博客加夜间模式

这个已早有计划，将在 Halo 2.0 重写主题后实现

**Comment by YeJoe** [comment]
> > > 移动端不支持切换主题及显示看板娘。
> > 
> > 
> > 后续是否可以把夜间模式单独放到页面头部区域呢？毕竟夜间模式在切换主题里面，如果移动端不支持切换的话，夜晚就没法给博客加夜间模式
> 
> 这个已早有计划，将在 Halo 2.0 重写主题后实现
 好的，感谢~
