### ISSUE TITLE
自定义主题的bing 植入广告?

### ISSUE THREAD

**Issue by monkeyKinn** [LIlGG/halo-theme-sakura#297]
请问下 自定义主题 bing 后台初始化的时候为什么是个会跳转广告的连接(还是那种广告) 而且切换成这个主题的时候默认又关了灯?

**Comment by monkeyKinn** [comment]
自己替换掉连接后 回到切换主题还是默认关灯

**Comment by monkeyKinn** [comment]
应该是后台获取的bing接口原因  ,那个接口开始恰饭了............只能默认关灯 社会主义核心价值观背上

**Comment by monkeyKinn** [comment]
https://api.1314.cool/bingimg 网上搜来的接口 可以替换

**Comment by LIlGG** [comment]
感谢反馈，目前正在完善开源版本 API，将考虑在其内添加必应图片 API。目前的话请等待适配 Halo 2.0 的新版本发布之后修复这个问题。。
可以用你上面这个接口在`主题设置 - 主题切换 - 主题 7 ` 中改变 API， 另外关灯了的话应该是开启了主题7 的黑夜模式

**Comment by monkeyKinn** [comment]
> 感谢反馈，目前正在完善开源版本 API，将考虑在其内添加必应图片 API。目前的话请等待适配 Halo 2.0 的新版本发布之后修复这个问题。。 可以用你上面这个接口在`主题设置 - 主题切换 - 主题 7 ` 中改变 API， 另外关灯了的话应该是开启了主题7 的黑夜模式

嗯嗯 谢谢 辛苦了
