### ISSUE TITLE
文章归档同一月份有两篇文章时页面一直抖动虚化

### ISSUE THREAD

**Issue by codesensi** [LIlGG/halo-theme-sakura#30]
问题描述如题
环境：谷歌浏览器
地址：https://52sensi.cn/archives

**Comment by codesensi** [comment]
> 问题描述如题
> 环境：谷歌浏览器
> 地址：https://52sensi.cn/archives

**Comment by LIlGG** [comment]
> 问题描述如题
> 环境：谷歌浏览器
> 地址：[https](https://52sensi.cn/archives) : [//52sensi.cn/archives](https://52sensi.cn/archives)

我这里看了似乎没有问题？？ 再确认确认？

**Comment by codesensi** [comment]
> > 问题描述如题
> > 环境：谷歌浏览器
> > 地址：[https](https://52sensi.cn/archives) : [//52sensi.cn/archives](https://52sensi.cn/archives)
> 
> 我这里看了似乎没有问题？？ 再确认确认？

啊哈？那可能是我浏览器的问题？我再看看
