### ISSUE TITLE
社交信息关闭后，故障文字不显示

### ISSUE THREAD

**Issue by FuckAnyProblem** [LIlGG/halo-theme-sakura#301]

**Comment by LIlGG** [comment]
Feature。故障文字取的就是社交信息的文本，所以关闭社交信息之后就等于关闭了故障文字。

**Comment by LIlGG** [comment]
确实有这个问题，感谢提供信息~

**Comment by FuckAnyProblem** [comment]
> 确实有这个问题，感谢提供信息~

应该感谢您的主题才对，真的是一个非常棒的作品❤️

**Comment by LIlGG** [comment]
> 应该感谢您的主题才对，真的是一个非常棒的作品❤️

谢谢，后续如果有其他问题可以发布 issue 告知我们，我会抽出时间来进行修改。
