### ISSUE TITLE
代码块渲染问题

### ISSUE THREAD

**Issue by Cheung0-bit** [LIlGG/halo-theme-sakura#305]
设置代码块 点击保存正常渲染 但刷新一下页面就变成下面的样子
![image](https://user-images.githubusercontent.com/75574488/202450344-a2fc5048-7021-43b1-a921-f920cdb92d45.png)

**Comment by Cheung0-bit** [comment]
更新问题 点击文章页第一次进去代码块和标题层级都不能正常渲染 刷新一下页面就可以正常读取配置渲染了

**Comment by LIlGG** [comment]
是否自行添加过 Head 或者 Footer 代码块？这种问题是代码报错导致，你可以使用 F12 打开控制台，查看一下是否报错。

**Comment by Cheung0-bit** [comment]
> 是否自行添加过 Head 或者 Footer 代码块？这种问题是代码报错导致，你可以使用 F12 打开控制台，查看一下是否报错。

感谢回答。是静态资源没有加载完整导致的，需要刷新一下页面才可以加载完成。至于是什么原因，我没有深入研究，通过更新主题包就可以解决该问题。
