### ISSUE TITLE
next版本加载异常

### ISSUE THREAD

**Issue by cjhxc** [LIlGG/halo-theme-sakura#310]
如图，请问怎么解决
![image](https://user-images.githubusercontent.com/73411853/206195862-87a5144b-bafa-4d85-afe1-58d9f21f3d1d.png)
![image](https://user-images.githubusercontent.com/73411853/206222545-958702dd-5ba1-4770-a3cb-be66a2586e3c.png)

**Comment by cjhxc** [comment]
![image](https://user-images.githubusercontent.com/73411853/206222213-e4f11383-0049-4aed-8af3-0cb0ed24612a.png)

**Comment by LIlGG** [comment]
这个是由于我还没有想好用什么 LOGO，不影响主题使用

**Comment by Uyouii** [comment]
> 

但是看起来会报错，主页面进不去orz

**Comment by LIlGG** [comment]
昨天修复了这个问题，忘了没提交，你再重新拉取一下 next 代码试试看。

**Comment by Uyouii** [comment]
> 

看起来ok啦！ 👍，感谢

**Comment by Uyouii** [comment]
目前看起来可以进去，但是有些图标显示不全

**Comment by Uyouii** [comment]
<img width="1910" alt="截屏2022-12-08 19 06 47" src="https://user-images.githubusercontent.com/25459212/206431648-2ec8cf72-049c-4b0d-834d-d13fc6ff2d77.png">
这里添加了github的链接，发现图标没显示

**Comment by LIlGG** [comment]
![image](https://user-images.githubusercontent.com/31335418/206433935-8cd289af-4aa0-45fb-81fc-7c8d30c76aa8.png)

我这边是可以正常显示的

**Comment by Uyouii** [comment]
<img width="1525" alt="截屏2022-12-09 10 49 @LIlGG 1" src="https://user-images.githubusercontent.com/25459212/206613220-71cd1778-608d-49c5-9ebb-592fb05c1933.png">
@LIlGG 看起来assets/images/sns 下没有github的图标
