### ISSUE TITLE
评论插件：刷新后不能添加新评论

### ISSUE THREAD

**Issue by Uyouii** [LIlGG/halo-theme-sakura#311]
首次进入网站文章可以显示，command/ctrl + R后，可以显示已有评论，但是不能添加新评论

**Comment by LIlGG** [comment]
感谢反馈，目前针对于插件的适配性还并未完善，在发布正式版之前将会依次处理这些插件的问题

**Comment by Uyouii** [comment]
> 感谢反馈，目前针对于插件的适配性还并未完善，在发布正式版之前将会依次处理这些插件的问题

**Comment by xiwei26** [comment]
大佬的主题很漂亮，目前2.1.0版本启用评论插件无效，您自己的那个插件目前也无法在2.1.0版本适用。期待大佬早日适配！

**Comment by LIlGG** [comment]
> 大佬的主题很漂亮，目前Halo 2.1.0版本启用评论插件无效，您自己的那个插件目前也无法在2.1.0版本适用。期待大佬早日适配！

插件应当是没有问题的，我本地使用 2.1.x 开发环境可以正常使用插件。但评论组件确实存在刷新后无法添加新评论的问题，这是由于评论插件与 pjax 配合的问题，正在寻找解决方案。

**Comment by Miraclezhb** [comment]
> > 大佬的主题很漂亮，目前Halo 2.1.0版本启用评论插件无效，您自己的那个插件目前也无法在2.1.0版本适用。期待大佬早日适配！
> 
> 插件应当是没有问题的，我本地使用 2.1.x 开发环境可以正常使用插件。但评论组件确实存在刷新后无法添加新评论的问题，这是由于评论插件与 pjax 配合的问题，正在寻找解决方案。

这个问题什么时候解决啊？
