### ISSUE TITLE
PC端评论组件有时候展示有时候不展示

### ISSUE THREAD

**Issue by spider-warrior** [LIlGG/halo-theme-sakura#313]
chrome 版本107
halo版本：latest

**Comment by LIlGG** [comment]
使用什么版本的 sakura？

**Comment by spider-warrior** [comment]
下载的这个（主题页详情的链接）
https://github.com/LIlGG/halo-theme-sakura/archive/next.zip

**Comment by spider-warrior** [comment]
F12控制台信息补充

**Comment by LIlGG** [comment]
确实存在这个问题，初步判断是插件适配问题，正在解决。

**Comment by LIlGG** [comment]
当前 issue 问题与 #311 重复，关闭此 issue
