### ISSUE TITLE
适配 Halo2.0 搜索功能

### ISSUE THREAD

**Issue by spider-warrior** [LIlGG/halo-theme-sakura#314]
chrome 版本107
halo版本：2.1.0
sakura： next

**Comment by LIlGG** [comment]
Halo 2.x 目前需要使用搜索插件 [plugin-search-widget](https://github.com/halo-sigs/plugin-search-widget) 来支持搜索。由于与本主题风格不符，等待 Halo [基于路由的搜索](https://github.com/halo-dev/halo/issues/2862)功能完成之后再迁移搜索功能。
