### ISSUE TITLE
2.0 next post / previous post 图片加载失败

### ISSUE THREAD

**Issue by Uyouii** [LIlGG/halo-theme-sakura#315]
如图：
<img width="1893" alt="截屏2022-12-12 00 10 38" src="https://user-images.githubusercontent.com/25459212/206914906-b0d4c9d7-d9c5-473b-af19-3450cdd413d4.png">

**Comment by LIlGG** [comment]
。似乎是一个 bug？？需要我本地复现后再确定。感谢反馈
