### ISSUE TITLE
500

### ISSUE THREAD

**Issue by MrZhengI** [LIlGG/halo-theme-sakura#316]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.0.2

### 建议/问题
![image](https://user-images.githubusercontent.com/50481340/208246706-733af72e-4f5f-4c86-b9a7-6204c5460fa8.png)

设置启用主题后首页500

**Comment by LIlGG** [comment]
这个值按道理来说是不会为空的，你试试在后台保存一下配置文件，然后再打开试试。如果还不行那就再重启一下 Halo。有可能是 Halo 没有读取到默认值

**Comment by MrZhengI** [comment]
![image](https://user-images.githubusercontent.com/50481340/209075456-73048805-c5c5-467b-95c5-d0dd69cfa0df.png)
后台随便改了配置然后保存了主题，但是还是报这个错。前端ui依旧500

**Comment by LIlGG** [comment]
> ![image](https://user-images.githubusercontent.com/50481340/209075456-73048805-c5c5-467b-95c5-d0dd69cfa0df.png) 后台随便改了配置然后保存了主题，但是还是报这个错。前端ui依旧500

有试过重新启动 Halo 吗？这个问题在我这边无法复现。

**Comment by MrZhengI** [comment]
> > ![图像](https://user-images.githubusercontent.com/50481340/209075456-73048805-c5c5-467b-95c5-d0dd69cfa0df.png)后台随便改了配置然后保存了主题，但是还是报这个错。前端ui依旧500
> 
> 有试过重新启动 Halo 吗？这个问题在我这边无法复现。

保存重启过还是不行。

**Comment by LIlGG** [comment]
> 保存重启过还是不行。

本地测试过多次确实无法复现，你可以再尝试使用“重载主题配置” 试试。

![image](https://user-images.githubusercontent.com/31335418/209308146-a4db9141-2c45-41ec-8e4a-1336df9e711d.png)

**Comment by LIlGG** [comment]
我这里也重新提交了一份代码，修改了一部分可能导致当前问题出现的代码。你可以重新下载一下。安装完成之后重载主题配置，然后再保存一下主题配置。未能完全帮助到你很抱歉，只能麻烦你多多尝试一下。。

https://github.com/LIlGG/halo-theme-sakura/archive/refs/heads/next.zip

**Comment by MrZhengI** [comment]
我下载了最新版本的，然后现在已解决，能正常使用了
