### ISSUE TITLE
首页随机图bug

### ISSUE THREAD

**Issue by infanx** [LIlGG/halo-theme-sakura#318]
### 目前使用的 Sakura 版本？

2.0.0-beta

### 目前使用的 halo 版本？

2.1

### 建议/问题

首页随机图设置无效

设置获取随机图的范围后：
![image](https://user-images.githubusercontent.com/65985757/210150384-220547cf-4d08-43c7-8e46-5d0f3ab830b4.png)
并不会生效，首页无图片

前端的 /templates/inc/decorate.html 文件 第 414 行 
获取id是 [(${theme.config.random_image.**rimage_cover_back_id**})]

settings.yaml 中， 第 889 行
name: **rimage_cover_id**

两个值不一样，导致获取不到id

**Comment by LIlGG** [comment]
感谢反馈！ 确实存在这个问题，正在着手改动。
