### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Lpdog-py** [LIlGG/halo-theme-sakura#319]
### 目前使用的 Sakura 版本？

latest

### 目前使用的 halo 版本？

halo

### 建议/问题

怎么使用主题里的照片和日志
我有点搞不懂
如果方便的话能否加我v：15360029025

**Comment by LIlGG** [comment]
2.0.x 版本的 halo 不支持图库和日志功能。

**Comment by Lpdog-py** [comment]
好的了解了，辛苦您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月17日(周五) 下午4:16
收件人: ***@***.***&gt;;
抄送: "Luo ***@***.******@***.***&gt;;
主题: Re: [LIlGG/halo-theme-sakura] 使用问题 (Issue #319)




 
2.0.x 版本的 halo 不支持图库和日志功能。
