### ISSUE TITLE
文章最后编辑日期显示不正确

### ISSUE THREAD

**Issue by xiuyuanjun** [LIlGG/halo-theme-sakura#320]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.2.0

### 建议/问题

旧的文章修改后，文章页最后编辑日期显示不正确。
![image](https://user-images.githubusercontent.com/24690740/217493649-e086e92c-cade-4889-ac08-29a5c6abadbd.png)

**Comment by LIlGG** [comment]
2.0 版本最开始的时候并未提供最后编辑日期，因此代码内采用了发布日期。而 2.1.x 版本之后提供了这个字段，这里确实需要进行修改。

**Comment by LIlGG** [comment]
close https://github.com/LIlGG/halo-theme-sakura/commit/3499a420030d45638cd357868251226d85487fba
