### ISSUE TITLE
网页网易云播放器好像不能正常显示了

### ISSUE THREAD

**Issue by monkeyKinn** [LIlGG/halo-theme-sakura#321]
### 目前使用的 Sakura 版本？

1.3.4

### 目前使用的 halo 版本？

1.6.0

### 建议/问题

如题 没有更新 都是老的版本 是版本原因吗

**Comment by LIlGG** [comment]
目前网易云音乐 api 出现了问题，等待修复即可。

**Comment by monkeyKinn** [comment]
好得 谢谢回复

**Comment by monkeyKinn** [comment]
> 目前网易云音乐 api 出现了问题，等待修复即可。

佬,现在 1.看板娘+2.随机图(看了之前的issue说三四天恢复,但是还没好)+3.网易云播放器还是不行吗?

**Comment by monkeyKinn** [comment]
@LIlGG

**Comment by LIlGG** [comment]
> 

服务器昨天进行了处理，但 API 里随机图由于升级了图床版本，目前随机图无法访问，网易云播放器则是因为代理的问题，这两个将一起处理，需要修改源码比较麻烦。看板娘应该是不受影响的。

**Comment by monkeyKinn** [comment]
好得知道了 ,谢谢 坐等更新,
        另外看板娘的问题我刚看了只能显示看板娘上面的每日一句  图显示不出来,f12也没有啥报错 会是网络原因吧?
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月8日 16:58
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [LIlGG/halo-theme-sakura] 网页网易云播放器好像不能正常显示了 (Issue #321)
        
      
    
  



服务器昨天进行了处理，但 API 里随机图由于升级了图床版本，目前随机图无法访问，网易云播放器则是因为代理的问题，这两个将一起处理，需要修改源码比较麻烦。看板娘应该是不受影响的。

**Comment by monkeyKinn** [comment]
好得,知道了 ,谢谢 坐等更新~
另外看板娘的问题我刚看了只能显示看板娘上面的每日一句  图显示不出来,f12也没有啥报错 会是网络原因吧?
