### ISSUE TITLE
打开私有文章的时候报500的错误

### ISSUE THREAD

**Issue by xiuyuanjun** [LIlGG/halo-theme-sakura#322]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.2.0

### 建议/问题

通过console页面，打开私有文章的时候，报出500的错误。如图所示：

<img width="585" alt="1676339845389" src="https://user-images.githubusercontent.com/24690740/218619595-f335306f-c7b2-4d0f-bdcd-4e91b7c7d2e8.png">

**Comment by LIlGG** [comment]
感谢反馈，经过测试确实存在这个问题，正在着手修改。

**Comment by LIlGG** [comment]
经过排查，该问题属于 Halo 后端问题， see:  https://github.com/halo-dev/halo/issues/3016

**Comment by LIlGG** [comment]
此问题与主题没有太大的关联，后续请关注 Halo https://github.com/halo-dev/halo/issues/3016 。当前 issue 关闭
