### ISSUE TITLE
页面显示后必须执行一次刷新操作代码才能被正确渲染

### ISSUE THREAD

**Issue by 1246459206** [LIlGG/halo-theme-sakura#323]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.2.0

### 建议/问题

你好，我在主题使用中时发现代码块必须重新刷新一次才能被正确渲染，具体的步骤和现象记录如下。
操作手顺：
1、选取一篇包含代码块的文章点击查看；
2、代码块的显示效果如图所示，控制台提示oncanplay undefined
![image](https://user-images.githubusercontent.com/53229756/219090430-cbd50cb8-20e6-4b3e-a15e-3bfda7b3db75.png)

恢复手顺：
在当前页面重新刷新一次，但是如果退回首页再重新进入文章，代码块渲染依旧出现问题

**Comment by padoru233** [comment]
我也是，手动刷新才能正确渲染

**Comment by LIlGG** [comment]
感谢反馈，我会进行测试并计划解决这个问题。

**Comment by LIlGG** [comment]
经过测试，该问题出现的原因是没有开启首页视频的话，会导致对应的 dom 找不到，我会尽快开始修改。
