### ISSUE TITLE
头部随机图

### ISSUE THREAD

**Issue by yikexiaoyao** [LIlGG/halo-theme-sakura#325]
### 目前使用的 Sakura 版本？

1.3.4

### 目前使用的 halo 版本？

1.6.1

### 建议/问题

头部图片是作业题目
![220614566-2848ce01-2c61-42fb-8b32-8a23a6666e7e](https://user-images.githubusercontent.com/36374114/220801087-2dae5b8c-d8a6-4e35-bca3-b7bbe26efeb7.png)

**Comment by LIlGG** [comment]
个人使用随机图，应该尽量保证使用自己创建的相册或精选相册，如下图

![image](https://user-images.githubusercontent.com/31335418/220811705-cb25c616-41e4-4963-b92e-bbd48d1b5287.png)

可以前往 https://view.lixingyong.com 来选择/创建适合自己的相册

**Comment by LIlGG** [comment]
issue 我先关闭了，如果后续有其他问题可以再提新的 issue
