### ISSUE TITLE
代码块高亮需要刷新一次才能正确显示

### ISSUE THREAD

**Issue by syk1ng** [LIlGG/halo-theme-sakura#327]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.2.0

### 建议/问题

使用的代码高亮插件
![image](https://user-images.githubusercontent.com/48880350/221434803-4869c24f-e4dd-4a9b-89c0-102064f5f03c.png)

打开文章页不能正确显示
![image](https://user-images.githubusercontent.com/48880350/221434760-2b71a4d8-dca7-41c5-95e5-a17dfd712bc6.png)

刷新之后才能显示
![image](https://user-images.githubusercontent.com/48880350/221434853-8c2ce10e-f495-4f02-b903-bc694d751e0f.png)

**Comment by LIlGG** [comment]
我之前提交过一个 https://github.com/LIlGG/halo-theme-sakura/commit/996eb25f4c3a8fe8440dc1a4d3c4ed75f8ff3fa6 commit， 这个解决了刷新问题，你可以下载开发版本 https://github.com/LIlGG/halo-theme-sakura/archive/refs/heads/next.zip 试一试

**Comment by syk1ng** [comment]
> 我之前提交过一个 [996eb25](https://github.com/LIlGG/halo-theme-sakura/commit/996eb25f4c3a8fe8440dc1a4d3c4ed75f8ff3fa6) commit， 这个解决了刷新问题，你可以下载开发版本 https://github.com/LIlGG/halo-theme-sakura/archive/refs/heads/next.zip 试一试

完美解决
