### ISSUE TITLE
随即图的API是不是挂了？

### ISSUE THREAD

**Issue by xiongtete0519** [LIlGG/halo-theme-sakura#328]
### 目前使用的 Sakura 版本？

2.0.0-beta

### 目前使用的 halo 版本？

2.2.0

### 建议/问题

![image](https://user-images.githubusercontent.com/66518135/222692930-43251303-e2b9-4adc-af52-d53e8a807f40.png)

**Comment by LIlGG** [comment]
重置了服务器，正在进行升级，大概得等两到三天时间才能恢复。

**Comment by xiongtete0519** [comment]
好的
