### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zhajianjun** [LIlGG/halo-theme-sakura#329]
### 目前使用的 Sakura 版本？

master

### 目前使用的 halo 版本？

Halo 1.x

### 建议/问题

1. https://lixingyong.com demo页面404
2. https://api.lixingyong.com/api/neteaseye  接口404，导致博客网站图片无法加载

**Comment by LIlGG** [comment]
网站正在升级中，重置了服务器。待图床迁移完成即可开放

**Comment by zhajianjun** [comment]
ヽ(￣▽￣)و好的，大佬
