### ISSUE TITLE
首页文章风格建议增加无图片的风格

### ISSUE THREAD

**Issue by zhixiangyuan** [LIlGG/halo-theme-sakura#33]
![image](https://user-images.githubusercontent.com/25138766/88473703-cc4ba980-cf52-11ea-9f03-c486053b0b7a.png)

目前的风格如果上传了封面图会很好看，但是没上传页面美感下降太多，建议增加无图片的风格，或者是优化目前在无图片时的文章展示列表。

**Comment by zhixiangyuan** [comment]
![image](https://user-images.githubusercontent.com/25138766/88473781-71ff1880-cf53-11ea-86d5-f27230c88f0d.png)

目前这样的页面感觉不太好看

**Comment by LIlGG** [comment]
很不错的建议！

**Comment by ruibaby** [comment]
我也觉得。
