### ISSUE TITLE
求集成视频插件

### ISSUE THREAD

**Issue by cymx333** [LIlGG/halo-theme-sakura#330]
### 目前使用的 Sakura 版本？

 2.0.0

### 目前使用的 halo 版本？

2.3.1

### 建议/问题

目前halo自带的视频播放太难用了，播放流媒体惨不忍睹，看到大佬准备集成视频插件，求选一个好用的，能顺利拉流的那种。

**Comment by LIlGG** [comment]
目前主题内已集成 videojs，支持 HLS、DASH 等各种流媒体。但目前仅用于首屏背景视频，后续可能会扩展至每个页面。

待 #340 完成之后将关闭此 issue
