### ISSUE TITLE
头部装饰图，选择后保存不了

### ISSUE THREAD

**Issue by kanon-H** [LIlGG/halo-theme-sakura#332]
### 目前使用的 Sakura 版本？

 2.0.0

### 目前使用的 halo 版本？

2.4.0

### 建议/问题

![image](https://user-images.githubusercontent.com/108659129/229362189-4c3da542-e50b-446b-9534-62a4a5376056.png)

你好，如图所示：头部装饰图，关闭后，保存，再点打开，点保存，保存不上，下次进来时两个选项都是未选中状态，其它选项也有这种情况

**Comment by LIlGG** [comment]
这是 Halo 2.4 的 BUG，查看 https://github.com/halo-dev/halo/issues/3666 ，等待 2.4.1 发布后更新一下 Halo 就可以了。

**Comment by kanon-H** [comment]
> 这是 Halo 2.4 的 BUG，查看 [halo-dev/halo#3666](https://github.com/halo-dev/halo/issues/3666) ，等待 2.4.1 发布后更新一下 Halo 就可以了。

好的，感谢
