### ISSUE TITLE
api问题

### ISSUE THREAD

**Issue by Redemptionist** [LIlGG/halo-theme-sakura#334]
### 目前使用的 Sakura 版本？

1.3.4

### 目前使用的 halo 版本？

1.6

### 建议/问题

国外vps无法使用api接口了，博客首页一片空白，F12一看所有图片调用全是failed，之前还是可以用的

**Comment by monkeyKinn** [comment]
+1

**Comment by monkeyKinn** [comment]
甚至自己加了随机图api都不行

**Comment by Zhouqiee** [comment]
大多接口都不支持了，请问要如何解决

**Comment by LIlGG** [comment]
> 大多接口都不支持了，请问要如何解决

请提供一下网站地址。 如果是 cdn 问题，请前往 `主题设置-其他-使用 CDN`，将其值设置为 false 即可

**Comment by monkeyKinn** [comment]
> 

是的 已经解决 就是cdn问题

**Comment by monkeyKinn** [comment]
> > 大多接口都不支持了，请问要如何解决
> 
> 请提供一下网站地址。 如果是 cdn 问题，请前往 `主题设置-其他-使用 CDN`，将其值设置为 false 即可

为什么之前可以

**Comment by LIlGG** [comment]
> > > 大多接口都不支持了，请问要如何解决
> > 
> > 
> > 请提供一下网站地址。 如果是 cdn 问题，请前往 `主题设置-其他-使用 CDN`，将其值设置为 false 即可
> 
> 为什么之前可以

之前由于 `jsdelivr` 问题，公共的 CDN 不能使用，因此我自建了一个临时的 cdn 用于主题端访问，目前已经不推荐使用。关闭 cdn 之后，所有资源将会走自己服务器，如果服务器带宽不够，可以自己选择使用其他 cdn

**Comment by LIlGG** [comment]
> 之前由于 `jsdelivr` 问题，公共的 CDN 不能使用，因此我自建了一个临时的 cdn 用于主题端访问，目前已经不推荐使用。关闭 cdn 之后，所有资源将会走自己服务器，如果服务器带宽不够，可以自己选择使用其他 cdn

不久之后将会更新下一个版本，下个版本中会默认移除公共 cdn，资源将默认走自己服务器。主题也将会开始考虑减少对外部资源的依赖。

**Comment by monkeyKinn** [comment]
> > 之前由于 `jsdelivr` 问题，公共的 CDN 不能使用，因此我自建了一个临时的 cdn 用于主题端访问，目前已经不推荐使用。关闭 cdn 之后，所有资源将会走自己服务器，如果服务器带宽不够，可以自己选择使用其他 cdn
> 
> 不久之后将会更新下一个版本，下个版本中会移除公共 cdn，资源将默认走自己服务器。主题也将会开始考虑减少对外部资源的依赖。

get  辛苦了 大大

**Comment by Zhouqiee** [comment]
没太大问题 我学生机也能带得起。

**Comment by yzcyayaya** [comment]
关掉cdn确实可以了，问一下随机图我直接api转发cdn静态图片地址，为什么不能用？

**Comment by LIlGG** [comment]
> 关掉cdn确实可以了，问一下随机图我直接api转发cdn静态图片地址，为什么不能用？

正常来说，只要接口不报错，是不会出现问题的。

**Comment by Redemptionist** [comment]
多谢大佬，确实是cdn问题

**Comment by monkeyKinn** [comment]
目前:
1.https://takagi-api.com/directlink/1/cdn/1.0.8/img/Sakura/images/   的sakura.svg和scroll.png 提示ERR_CONNECTION_TIMED_OUT;
2.https://unpkg.com/katex@0.12.0/dist/katex.min.css   ----  提示 ERR CONNECTION ABORTED

**Comment by monkeyKinn** [comment]
@LIlGG

**Comment by LIlGG** [comment]
> 目前: 1.https://takagi-api.com/directlink/1/cdn/1.0.8/img/Sakura/images/ 的sakura.svg和scroll.png 提示ERR_CONNECTION_TIMED_OUT; 2.https://unpkg.com/katex@0.12.0/dist/katex.min.css ---- 提示 ERR CONNECTION ABORTED

2.x beta.2 版本将去处外部 js，目前 sakura.svg和scroll.png  可以使用 https://cdn.jsdelivr.net/gh/LIlGG/cdn@1.0.2/img/Sakura/images/scroll.png 及 https://cdn.jsdelivr.net/gh/LIlGG/cdn@1.0.2/img/Sakura/images/sakura.svg 替换

**Comment by monkeyKinn** [comment]
> > 目前: 1.https://takagi-api.com/directlink/1/cdn/1.0.8/img/Sakura/images/ 的sakura.svg和scroll.png 提示ERR_CONNECTION_TIMED_OUT; 2.https://unpkg.com/katex@0.12.0/dist/katex.min.css ---- 提示 ERR CONNECTION ABORTED
> 
> 2.x beta.2 版本将去除外部 js，目前 sakura.svg和scroll.png 可以使用 https://cdn.jsdelivr.net/gh/LIlGG/cdn@1.0.2/img/Sakura/images/scroll.png 及 https://cdn.jsdelivr.net/gh/LIlGG/cdn@1.0.2/img/Sakura/images/sakura.svg 替换

谢谢,我去试试,
另外 那个 katex.min.css,是在哪里用到的?(好像没加载也没啥区别)

**Comment by LIlGG** [comment]
> 谢谢,我去试试, 另外 那个 katex.min.css,是在哪里用到的?(好像没加载也没啥区别)
这个是数学公式，如果用不到可以不加载。我的默认设置中是没有开启数学公式插件的。你如果没有数学公式相关的文章可以进行关闭。
