### ISSUE TITLE
如何设置自定义头像？

### ISSUE THREAD

**Issue by KaniuBillows** [LIlGG/halo-theme-sakura#335]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.4.2

### 建议/问题

该主题能否支持自定义头像，我并没有找到入口，难道只能替换目录下的文件吗？

**Comment by LIlGG** [comment]
主题使用的头像是 Halo 站点头像，替换 Halo 头像即可。
