### ISSUE TITLE
回到顶部图片API访问缓慢

### ISSUE THREAD

**Issue by hhm1** [LIlGG/halo-theme-sakura#336]
### 目前使用的 Sakura 版本？

2.0.0-beta

### 目前使用的 halo 版本？

2.4.2

### 建议/问题

```
https://takagi-api.com/directlink/1/cdn/1.0.8/img/Sakura/images/scroll.png
```
这个API会拖慢网站加载速度，直连访问ERR_CONNECTION_TIMED_OUT

**Comment by LIlGG** [comment]
先不用关闭，等待修复之后再进行关闭。
