### ISSUE TITLE
无法关闭“复制内容增加版权声明”功能

### ISSUE THREAD

**Issue by ZJZ0405** [LIlGG/halo-theme-sakura#337]
### 目前使用的 Sakura 版本？

next

### 目前使用的 halo 版本？

2.0

### 建议/问题

在以前的issue找到了相同的问题，但作者没有明确说明是否复现了该问题，但我这里确实出现了。我有一段时间内没有更新我的主题了，如果在最新版本没有这个问题，请告知我更换版本

**Comment by LIlGG** [comment]
感谢反馈。 目前主题正在进行完全重构，我将会在重构过程中测试这个问题。如果确定是 bug 将同步进行修复。

**Comment by ZJZ0405** [comment]
> 感谢反馈。 目前主题正在进行完全重构，我将会在重构过程中测试这个问题。如果确定是 bug 将同步进行修复。

OK

**Comment by ZJZ0405** [comment]
> 使用 next 测试过在`主题设置 - 文章页 - 复制内容增加版权声明` 功能关闭之后，复制出的内容将不会增加版权声明。功能似乎没有问题。
> 
> 
> 
> 关闭前复制内容为：
> 
> ```
> 
>       # 商业转载请联系作者获得授权，非商业转载请注明出处。
> 
> 
> 
>       # For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
> 
> 
> 
>       # 协议(License): 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
> 
> 
> 
>       # 作者(Author): Administrator 
> 
> 
> 
>       # 链接(URL): /archives/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E 
> 
> 
> 
>       # 来源(Source): test 
> 
> 
> 
>       希望各位大大能够给个 star，你们的支持是我最大的动力~
> 
> ```
> 
> 
> 
> 关闭后复制的内容：
> 
> ```
> 
> 希望各位大大能够给个 star，你们的支持是我最大的动力~
> 
> ```

可能是我的版本比较老了，等我更新一下再试试
