### ISSUE TITLE
日志页

### ISSUE THREAD

**Issue by fzweclipse** [LIlGG/halo-theme-sakura#339]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.5.1

### 建议/问题

想知道目前日志页是否已经完成。显示版本要求2.2.0，是有新的版本了吗？在哪下载升级呀？

**Comment by LIlGG** [comment]
日志页目前已经完成，但还未发布版本。使用 next 分支拉去即可。

**Comment by fzweclipse** [comment]
docker部署是不是暂时没法用呀？

**Comment by fzweclipse** [comment]
我使用next分支拉取，进行升级之后，日志页还是提示404错误。
