### ISSUE TITLE
文章内容显示不全

### ISSUE THREAD

**Issue by fzweclipse** [LIlGG/halo-theme-sakura#341]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.5.2

### 建议/问题

![QQ截图20230518094934](https://github.com/LIlGG/halo-theme-sakura/assets/20226004/1395085b-f223-4060-8c4b-5d0f30b838ba)
文章内容显示不全

**Comment by LIlGG** [comment]
将鼠标移动到目标文本上，然后按下鼠标左边并向右拖拽看看是否能显示。

**Comment by fzweclipse** [comment]
是的，可以拖拽显示，这也算是一个解决办法吧。
