### ISSUE TITLE
图库可否新增倒序查询

### ISSUE THREAD

**Issue by liaoyiqing** [LIlGG/halo-theme-sakura#342]
### 目前使用的 Sakura 版本？

1.3.4

### 目前使用的 halo 版本？

1.5.4

### 建议/问题

上传的图片太多，想看最近上传的图片，需要滚动至最底部，很麻烦

**Comment by LIlGG** [comment]
确实应该增加此功能。不过应该会放在 beta.2 版本，用于适配 Halo 2.0。 1.x 版本后续只会修复 BUG。

**Comment by liaoyiqing** [comment]
辛苦大佬~

**Comment by LIlGG** [comment]
该功能可能需要 Halo 插件进行适配，目前 Halo 上是根据 Priority 以及 CreationTimestamp 进行排序的。但 Halo 目前针对于前端自由获取数据的方式还在探索当中，例如 https://github.com/halo-dev/halo/issues/3508 。因此主题端对于自定义倒序查询还是比较困难的。
计划可以先修改插件，让 CreationTimestamp 降序排序而不是升序，目前应该是一个 bug。


```
    static Comparator<Photo> defaultPhotoComparator() {
        Function<Photo, Integer> priority = link -> link.getSpec()
            .getPriority();
        Function<Photo, Instant> createTime = link -> link.getMetadata()
            .getCreationTimestamp();
        Function<Photo, String> name = link -> link.getMetadata().getName();
        return Comparator.comparing(priority, Comparators.nullsLow())
            .thenComparing(createTime)
            .thenComparing(name);
    }
```

**Comment by LIlGG** [comment]
图库插件已经更新，查看 https://halo.run/store/apps/app-BmQJW?tab=releases 使用最新的图库插件即可倒序排列。
