### ISSUE TITLE
日志页面出现404

### ISSUE THREAD

**Issue by sun-i** [LIlGG/halo-theme-sakura#345]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.6.0

### 建议/问题

按照文档配置了日志页面的菜单项，但是访问时找不到页面
![image](https://github.com/LIlGG/halo-theme-sakura/assets/111034439/48d2da7b-4da6-48a9-8d00-63464f363bdf)

**Comment by wxmgmh** [comment]
参考 https://halo.run/store/apps/app-YGkgz?tab=releases
已知迁移问题
页面
Halo 2.x 目前不存在图库路由/插件，图库暂未迁移，因此图库功能将无法使用
Halo 2.x 目前不存在日志路由/插件，日志暂未迁移，因此日志功能将无法使用
Halo 2.x 目前需要使用友链插件 [plugin-links](https://github.com/halo-sigs/plugin-links) 来支持友链。因此友链暂时不会在测试版中进行迁移，发布正式版之前将基于此插件开发友链界面
