### ISSUE TITLE
音乐播放器和看板娘重叠导致无法点击音乐播放器

### ISSUE THREAD

**Issue by wxmgmh** [LIlGG/halo-theme-sakura#346]
### 目前使用的 Sakura 版本？

2.0

### 目前使用的 halo 版本？

2.6

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/35417181/d29362d8-f8d9-4401-b705-7f926bd8af78)

**Comment by LIlGG** [comment]
感谢反馈，确实有这个问题，看板娘插件我设置了堆叠，但设置太高了，下个版本会调整一下。
主题 Beta.2 版本也会单独适配一下 Live2d 插件的样式，解决冲突。
