### ISSUE TITLE
回到顶部图片和页脚logo无法访问

### ISSUE THREAD

**Issue by wxmgmh** [LIlGG/halo-theme-sakura#348]
### 目前使用的 Sakura 版本？

2.0

### 目前使用的 halo 版本？

2.6

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/35417181/04fd715b-669c-47dc-831b-89640ba92c02)
图示中已换成了1.x版本的url

**Comment by LIlGG** [comment]
重复问题 #336 ，将在 sakura Beta.2 修复。
