### ISSUE TITLE
当友链多了之后显示有些 bug

### ISSUE THREAD

**Issue by zhixiangyuan** [LIlGG/halo-theme-sakura#35]
![image](https://user-images.githubusercontent.com/25138766/88473917-990a1a00-cf54-11ea-9471-fc066f5e5fcd.png)

**Comment by LIlGG** [comment]
BUG问题我会尽快解决， 可以把你的博客地址贴到下面嘛？我这边看一下是什么原因导致的！

**Comment by zhixiangyuan** [comment]
> BUG 问题我会尽快解决， 可以把你的博客地址贴到下面嘛？我这边看一下是什么原因导致的！

http://47.100.13.134/links 地址
