### ISSUE TITLE
Theme icons are missed

### ISSUE THREAD

**Issue by love98ooo** [LIlGG/halo-theme-sakura#350]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.0

### 建议/问题

更新主题之后发现主题工具列表中图标消失

![2023-06-13_194354](https://github.com/LIlGG/halo-theme-sakura/assets/77888749/fd0c1d33-6bf7-4a3e-a6f9-f892f2eff314)

> 图标库变动，不再使用字体图标，本版本使用 [iconify](https://iconify.design/) svg 作为内置图标库。

猜测可能与这次更新中的图标库更新有关

**Comment by LIlGG** [comment]
需要在后台中，初始化主题设置。

**Comment by LIlGG** [comment]
> 请问是这个吗
> 
> ![image](https://user-images.githubusercontent.com/77888749/245473886-97b4109a-af20-4b38-8b5d-ad90af3a4d3c.png)

最后一个 Reset
