### ISSUE TITLE
图库页面切换多张自动置顶切换失败

### ISSUE THREAD

**Issue by FueGold** [LIlGG/halo-theme-sakura#353]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.0

### 建议/问题

图库页面右边的切换为多张的图标按钮，我点击切换为多张自动会置顶跳转，不会切换，必须到顶部页面才能点击切换多张成功

**Comment by LIlGG** [comment]
经过测试，没有复现此问题。或许是由于你点击的时候，点到了回到顶部的挂绳上面。

**Comment by LIlGG** [comment]
挂绳会比实际看上去宽一些，因此还是容易点到的。

**Comment by FueGold** [comment]
> 挂绳会比实际看上去宽一些，因此还是容易点到的。
额，确实是挂绳问题，那就没办法了，只能不用挂绳或者弄宽分辨率了
