### ISSUE TITLE
评论回复功能样式问题

### ISSUE THREAD

**Issue by AbsoluteZeroKing** [LIlGG/halo-theme-sakura#354]
### 目前使用的 Sakura 版本？

v2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.1

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/45005201/9b7d7675-49d3-4eb6-b951-14bbc0433f47)

**Comment by LIlGG** [comment]
在 #418 中使用了评论组件自带的样式，使用该样式有以后应该不会再存在此问题。
