### ISSUE TITLE
切换主题样式问题

### ISSUE THREAD

**Issue by AbsoluteZeroKing** [LIlGG/halo-theme-sakura#355]
### 目前使用的 Sakura 版本？

v2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.1

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/45005201/2e771eab-b8bf-4938-98d3-c569d2bc3709)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/45005201/8bfee819-bc00-4e36-8c11-21b96db64807)

**Comment by LIlGG** [comment]
如果是从旧版本升级的，需要先进行主题设置重置。
![image](https://github.com/LIlGG/halo-theme-sakura/assets/31335418/b079e19e-0d34-4e6c-b496-0af5a7aeea01)


如果是全新的新版本，可能是由于配置项报错的问题，可以下载最新 next 分支来解决
https://github.com/LIlGG/halo-theme-sakura/archive/refs/heads/next.zip

**Comment by LIlGG** [comment]
有任何其他进展吗？
