### ISSUE TITLE
文章详情页中的作者信息直接显示用户名导致登录账号信息泄露

### ISSUE THREAD

**Issue by YyJqW** [LIlGG/halo-theme-sakura#356]
### 目前使用的 Sakura 版本？

 2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.0

### 建议/问题

文章详情页的页面底部，会显示的用户详情中，直接显示了用户名而非用户显示名，同时头像中包含的链接也直接显示了用户名，有泄露后台登录账户的危险性存在，就我个人而言，我在早期的halo版本中直接使用了其他社交账户的账号作为halo用户名，如今的halo版本中无法修改用户名只能修改用户显示名称，进而导致了在sakura目前版本的主题下我的社交账户被泄露。
![image](https://github.com/LIlGG/halo-theme-sakura/assets/57286294/bde42c9f-9445-47e9-850e-4bde0fd3846b)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/57286294/1be564d8-5b37-48e5-8edf-2bbb3850268d)
目前我通过在后台的全局代码注入中添加了js代码来临时删除这个dom
```
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	    $('.author-profile').remove();
	});
</script>
```
希望能在新版本中对这个问题进行修改

**Comment by LIlGG** [comment]
确实存在这个问题，将会在发布 2.0.0 正式版之前进行修复，感谢反馈。
不过你目前的解决问题会额外使用阻塞的 jquery，降低页面渲染速度，可暂时监听主题刷新事件来替换，如下所示。
```
<script>
window.addEventListener("sakura:refresh", () => {
  document.querySelector(".author-profile").remove();
})
</script>
```

**Comment by YyJqW** [comment]
> 

好的，谢谢

**Comment by LIlGG** [comment]
无需关闭此 issue，待修复完成之后我将关联关闭。
