### ISSUE TITLE
发布的"瞬间"不显示图片

### ISSUE THREAD

**Issue by wxmgmh** [LIlGG/halo-theme-sakura#357]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.1

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/35417181/b4a29d92-20ef-4546-a612-78407a7152b5)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/35417181/b9d85cf4-9708-4391-821e-db00da9acd13)

**Comment by LIlGG** [comment]
目前暂不支持单独添加的图片，只支持瞬间内容里的。

**Comment by LIlGG** [comment]
在 #455 中实现了对九宫格图片的支持。
