### ISSUE TITLE
升级halo2.7.0，瞬间页面500异常，服务器内部异常

### ISSUE THREAD

**Issue by FueGold** [LIlGG/halo-theme-sakura#362]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7.0

### 建议/问题

升级halo2.7.0，瞬间页面500异常，服务器内部异常，2.6没事

**Comment by LIlGG** [comment]
下载最新的瞬间插件即可，理论上，图库插件也需要更新最新版本。
