### ISSUE TITLE
升级halo2.7.0，代码块行号显示功能开启后仍然无法显示行号

### ISSUE THREAD

**Issue by Strider1230** [LIlGG/halo-theme-sakura#363]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7.0

### 建议/问题

升级halo2.7.0，代码块行号显示功能开启后仍然无法显示行号。

**Comment by LIlGG** [comment]
是否使用了代码高亮插件？主题自带代码高亮，因此会与代码高亮插件冲突。
如果是从 Beta.1 升级到 Beta.2，则需要重置一下主题配置。

**Comment by Strider1230** [comment]
> 是否使用了代码高亮插件？主题自带代码高亮，因此会与代码高亮插件冲突。 如果是从 Beta.1 升级到 Beta.2，则需要重置一下主题配置。

已经通过切换代码显示模式的方式解决行号不显示的问题。
