### ISSUE TITLE
将移动端侧边栏头像改为站点 LOGO

### ISSUE THREAD

**Issue by Strider1230** [LIlGG/halo-theme-sakura#364]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7.0

### 建议/问题

设置头像后主页左侧边栏显示的头像仍然是模板自带的默认头像，想问问修改的方式。

**Comment by LIlGG** [comment]
左侧边栏显示的是当前登录用户的头像。

**Comment by Strider1230** [comment]
> 左侧边栏显示的是当前登录用户的头像。

我明白了就是说未登录的访客看的话就是显示的默认的访客头像，访客的头像可以修改吗？如图所示：
![image](https://github.com/LIlGG/halo-theme-sakura/assets/38949080/e6eb6bd3-fd45-425a-827c-bf2f9dfcfb7b)

**Comment by LIlGG** [comment]
> 我明白了就是说未登录的访客看的话就是显示的默认的访客头像，访客的头像可以修改吗？如图所示： ![image](https://user-images.githubusercontent.com/38949080/251625209-e6eb6bd3-fd45-425a-827c-bf2f9dfcfb7b.png)

访客头像目前无法修改，1.x 版本的时候具有站点头像，但 2.x 没有站点头像这样的概念。
不过给访客显示默认的确实是一个问题，我会将其修改为显示为站点 logo。
