### ISSUE TITLE
深色模式支持响应用户本地系统设置这个功能怎么关闭

### ISSUE THREAD

**Issue by micro-mieruko** [LIlGG/halo-theme-sakura#365]
### 目前使用的 Sakura 版本？

2.0.0-Beta.2

### 目前使用的 halo 版本？

2.7.0

### 建议/问题

你好，深色模式支持响应用户本地系统设置，这个功能怎么关闭呀。因为我的windows系统用的是深色，浏览器没缓存的情况下打开博客总是一片黑。无论我在主题风格里设置默认主题是啥，主题风格里的每个主题的黑夜模式我都关闭了。

虽然说可以在右下角切换主题成白色的，浏览器缓存没清的话下次再打开还是白色主题。但是清理的话，打开来又是黑色的了。

我想实现的是，无论访问的浏览器是什么样的深浅色设置，第一次打开来看到的都是白色的。

**Comment by LIlGG** [comment]
当前无法做到完全关闭深色模式，但如果手动调整了主题，那么浏览器将会记录你的主题。如果不手动设置，则会响应当前系统色。

如果不想自适应，目前有两种办法∶
1. 关闭系统深色模式。
2. 手动切换主题。

如果清理浏览器缓存，将会恢复至默认行为，这是预期的事情。

**Comment by micro-mieruko** [comment]
> 当前无法做到完全关闭深色模式，但如果手动调整了主题，那么浏览器将会记录你的主题。如果不手动设置，则会响应当前系统色。
> 
> 如果不想自适应，目前有两种办法∶
> 
> 1. 关闭系统深色模式。
> 2. 手动切换主题。
> 
> 如果清理浏览器缓存，将会恢复至默认行为，这是预期的事情。

原来如此，因为我第一次打开https://lixingyong.com/就是白色的，如果打开我的，除了手动切换主题，怎么弄都是黑色的，所以有点奇怪。

**Comment by LIlGG** [comment]
> 原来如此，因为我第一次打开https://lixingyong.com/就是白色的，如果打开我的，除了手动切换主题，怎么弄都是黑色的，所以有点奇怪。

目前这个使用的是旧版本主题，暂时没有时间迁移。旧版本不支持自适应系统色，因此一直是白色的。但博客通常是给访客查看的，自适应访客客户端是更加重要的。

**Comment by micro-mieruko** [comment]
> > 原来如此，因为我第一次打开[https://lixingyong.com/就是白色的，如果打开我的，除了手动切换主题，怎么弄都是黑色的，所以有点奇怪。](https://lixingyong.com/%E5%B0%B1%E6%98%AF%E7%99%BD%E8%89%B2%E7%9A%84%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%89%93%E5%BC%80%E6%88%91%E7%9A%84%EF%BC%8C%E9%99%A4%E4%BA%86%E6%89%8B%E5%8A%A8%E5%88%87%E6%8D%A2%E4%B8%BB%E9%A2%98%EF%BC%8C%E6%80%8E%E4%B9%88%E5%BC%84%E9%83%BD%E6%98%AF%E9%BB%91%E8%89%B2%E7%9A%84%EF%BC%8C%E6%89%80%E4%BB%A5%E6%9C%89%E7%82%B9%E5%A5%87%E6%80%AA%E3%80%82)
> 
> 目前这个使用的是旧版本主题，暂时没有时间迁移。旧版本不支持自适应系统色，因此一直是白色的。但博客通常是给访客查看的，自适应访客客户端是更加重要的。

嗯嗯，如果可以的话，希望以后能有个开关😁

**Comment by LIlGG** [comment]
> 嗯嗯，如果可以的话，希望以后能有个开关😁
这个功能暂时不会发生变化，目前都是符合预期的。如果之后需求比较大，可能会再度变更。
