### ISSUE TITLE
安装 KaTeX 插件后无法正常渲染数学公式

### ISSUE THREAD

**Issue by doubleki7461** [LIlGG/halo-theme-sakura#369]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7.0

### 建议/问题

Halo 安装 KaTeX 2.0.0 插件后，从网站首页进入文章页面时，文章中的数学公式无法正常渲染，但是刷新后即可正常显示

无论是直接从链接访问，还是从搜索引擎跳转，KaTeX 均可正常显示，唯独从网站其他页面跳转时首次无法正常渲染

[blog 测试地址](https://blog.kierankihn.com/archives/jie-ti-bao-gao-p2674-qu-pa-de-shu-zi-you-xi-t2-duo-bian-xing-shu)

**Comment by LIlGG** [comment]
应该是由于 `pjax` 导致的，临时解决办法为关闭 `pjax` 即可

**Comment by LIlGG** [comment]
发现 `kaTex` 似乎有刷新方法。那么可以尝试在 `代码注入` 中使用如下代码来解决

```js
window.addEventListener("sakura:refresh", function () {
  renderMathInElement(document.body, {
    // customised options
    // • auto-render specific keys, e.g.:
    delimiters: [
      { left: "$$", right: "$$", display: true },
      { left: "$", right: "$", display: false },
      { left: "\\(", right: "\\)", display: false },
      { left: "\\[", right: "\\]", display: true },
    ],
    // • rendering keys, e.g.:
    throwOnError: false,
  });
});
```
