### ISSUE TITLE
系统设置中Logo、副标题等元素功能冲突

### ISSUE THREAD

**Issue by LostAttractor** [LIlGG/halo-theme-sakura#372]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/46527539/d3b6edd8-dae4-4504-9646-930ae0bc1fb5)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/46527539/9a873eb7-613d-4f4f-83a4-7d658dfbba69)

似乎升级到halo2后，中间的个人头像和下方的个人简介变为了 系统设置 - Logo 和 系统设置 - 站点副标题，原本是设置中个人资料的头像和个人简介
而这些系统设置中的Logo还会用于左上角站点标题，站点副标题还会被拼接在站点标题后方
![image](https://github.com/LIlGG/halo-theme-sakura/assets/46527539/2017d5f9-7b24-4b18-9d43-1aa0fc5d5c41)

似乎halo2加入了类似多用户的机制，不知道是否可以通过读取admin用户的头像和Bio获得这两个内容，若不可以我认为应该在主题设置中加入单独的设置选项

**Comment by LostAttractor** [comment]
> 中间的头像设置和下方个人简介为 Site 设置中的 站点 Logo 与 站点副标题是符合预期的。
> 
> 左上角之前的预期行为确实为站点标题。
> 
> 至于站点副标题拼接在 ~~站点标题~~（应该说是标题，不同页面的标题不一致）后方，是 Sakura beta.2 之后特意加上，对 SEO 有益。
> 
> 
> 
> 对于 Halo 2.x 来说，无法通过读取 Admin 用户的头像和 Bio，只能获取当前登录用户的信息。

可是这样我就不能把以前的页面无缝迁移过来了
以及左上角放个图片我觉得多少有点怪，然后SEO的话，我确实是不太在意SEO（）
请问你觉得加个是否额外自定义的选项怎么样，如果你觉得好的话我等一下发pr（

**Comment by LIlGG** [comment]
> 左上角放个图片我觉得多少有点怪
确实效果不是很好，目前的逻辑是，当存在站点头像的时候，就展示站点头像，否则展示站点标题。

https://github.com/LIlGG/halo-theme-sakura/blob/0dc9e7c3a87483b3d07bece7c40400db43ccac45/templates/module/header/brand.html#L3-L10

你可以在主题基本设置中设置一个选项，用来控制优先级。

> 然后SEO的话，我确实是不太在意SEO
作为一个开源主题，是需要考虑最佳情况的。

提前感谢你的 PR。
