### ISSUE TITLE
文章标题带中括号｛｝

### ISSUE THREAD

**Issue by peachestao** [LIlGG/halo-theme-sakura#377]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.0

### 建议/问题

文章标题无缘无故的带上了大括号｛｝
![image](https://github.com/LIlGG/halo-theme-sakura/assets/20684642/4a61f343-b9be-4070-b544-7274ac486d4b)

请问该如何解决？

**Comment by LIlGG** [comment]
这是主题不带封面图时的默认样式，如果不想要，可以在代码注入中使用 css 进行去除。

**Comment by peachestao** [comment]
搞定了，非常感谢。没想到这么快回复，作者辛苦了
