### ISSUE TITLE
Sakura 2.0 搜索样式

### ISSUE THREAD

**Issue by peachestao** [LIlGG/halo-theme-sakura#378]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.6.0

### 建议/问题

你好，我用的搜索插件是主题内置的，版本：1.1.0

现在的搜索效果：
![image](https://github.com/LIlGG/halo-theme-sakura/assets/20684642/a392332a-04b2-4b7b-bea4-f1164e63fea1)

我如何才能实现下面的搜索效果？这个效果我在主题的demo页https://lixingyong.com/ 看到的

![image](https://github.com/LIlGG/halo-theme-sakura/assets/20684642/e2449424-9b23-4759-87c6-ddc5df36c75d)

**Comment by LIlGG** [comment]
2.x 目前不支持基于路由的搜索功能。查看 https://github.com/halo-dev/halo/issues/2862 。目前使用的是 2.x 默认提供的搜索插件自带的，你看到的博客基于 1.x 搭建。

**Comment by peachestao** [comment]
如果我降级到Sakura 1.x 数据库的数据兼容吧？

**Comment by LIlGG** [comment]
> 我降级到Sakura 1.x 数据库的数据兼容吧？

sakura 1.x 只适配于 Halo1.x
sakura 2,x 只适配于 Halo2.x

并且 Halo 1.x 与 Halo2.x 不兼容。

**Comment by peachestao** [comment]
了解了，感谢

**Comment by peachestao** [comment]
> > 我降级到Sakura 1.x 数据库的数据兼容吧？
> 
> sakura 1.x 只适配于 Halo1.x sakura 2,x 只适配于 Halo2.x
> 
> 并且 Halo 1.x 与 Halo2.x 不兼容。
