### ISSUE TITLE
复制代码后出现版权声明

### ISSUE THREAD

**Issue by zhixiangyuan** [LIlGG/halo-theme-sakura#38]
```
# 商业转载请联系作者获得授权，非商业转载请注明出处。
# For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
# 协议(License)：署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
# 作者(Author)：
# 链接(URL)：
# 来源(Source)：It's me
```

复制代码出现该版权声明，如何关掉该功能？

**Comment by LIlGG** [comment]
> ```
> # 商业转载请联系作者获得授权，非商业转载请注明出处。
> # For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
> # 协议(License)：署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
> # 作者(Author)：
> # 链接(URL)：
> # 来源(Source)：It's me
> ```
> 
> 复制代码出现该版权声明，如何关掉该功能？

可以在后台 -> 主题 -> 设置 -> 提示及监听里面， 关闭复制内容增加版权声明即可。
![https://cdn.lixingyong.com/2020/07/29/0yOatf6Y6M.png](https://cdn.lixingyong.com/2020/07/29/0yOatf6Y6M.png)

**Comment by LIlGG** [comment]
我先关闭了！如果还没解决就再打开吧

**Comment by ZJZ0405** [comment]
我不能通过该选项关闭版权声明
