### ISSUE TITLE
首屏 - 聚焦故障文本 选项只会在头部样式设置为故障文字时才会出现

### ISSUE THREAD

**Issue by LostAttractor** [LIlGG/halo-theme-sakura#399]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7

### 建议/问题

首屏 - 聚焦故障文本 选项只会在头部样式设置为故障文字时才会出现，但是该选项始终对应移动端导航栏中头像下方的文字
应该始终显示该选项 或 在头部样式设置为头像时，移动端和电脑上保持一致都使用站点副标题作为文本填充

**Comment by LIlGG** [comment]
移动端与 PC 端样式是不相同的。
PC 端聚焦文本与头像互斥，并且聚焦文本适用于比较短小精简的文本，不适合使用站点副标题。

之所以互斥，原因是由于聚焦文本的光效可能会对某些癫痫症患者不友好，因此增加头像作为备用方案。移动端由于没有相同的特效，因此一直显示。

**Comment by LostAttractor** [comment]
> 

这样，虽然我觉得那个聚焦文本的效果不是很好看
不过我的意思是，如果这样的话，应该始终显示聚焦故障文本的选项，现在这个输入框只会在头部样式设置为故障文字时显示，这样就没法设置移动端菜单栏的文本内容了

**Comment by LIlGG** [comment]
这个确实是个问题，可以将这个设置改为永久显示。
