### ISSUE TITLE
原主题停更了

### ISSUE THREAD

**Issue by kfyidrig** [LIlGG/halo-theme-sakura#40]
https://github.com/mirai-mamori/Sakurairo   Sakurairo出现了，快看看，哈哈哈哈

**Comment by LIlGG** [comment]
这。我sakura还没完全移植完。。
不过感谢哈哈，我或许可以再借鉴一下。搞一套分支库再。。
坑还很大。。

**Comment by kfyidrig** [comment]
这两者差异不是很大的，可以直接参考最新的sakurairo哇，嘿嘿嘿，你这个主题我觉得很不错

**Comment by LIlGG** [comment]
> 这两者差异不是很大的，可以直接参考最新的sakurairo哇，嘿嘿嘿，你这个主题我觉得很不错

不过我觉得这个主题似乎太花里胡哨。。有些人还是喜欢精简的。
我回去再研究研究这个主题，或者说我可以加一些额外的配置，决定是精简样式还是比较好看的自定义样式。。我更想将这两个主题融合成一个。可以自定义配置的那种

**Comment by kfyidrig** [comment]
iro的配图用了第三方api，很方便的，就是他调用第三方api，文章和主页的配图都随机调用，省去了配图时间，还有一些音效，美滋滋

**Comment by LIlGG** [comment]
> iro的配图用了第三方api，很方便的，就是他调用第三方api，文章和主页的配图都随机调用，省去了配图时间，还有一些音效，美滋滋

嗯嗯。我完了会专门花时间研究一下，如果可行我就立马集成。。不过最近家里有事，可能赶不上进度。你要是有啥好的想法，可以帮忙pr或者提一下。

**Comment by kfyidrig** [comment]
幸苦咯，一定的

**Comment by LIlGG** [comment]
> 幸苦咯，一定的

嗯。不过确实每个文章自己配图特别麻烦。这个地方用API生成实际上是挺不错。能解决很多问题。。

**Comment by kfyidrig** [comment]
主要是，自己配很容易和炫酷的主题不搭，api调用几乎风格一致的图片很方便

**Comment by LIlGG** [comment]
> 主要是，自己配很容易和炫酷的主题不搭，api调用几乎风格一致的图片很方便

点错了。我之后会研究一下他的API。讲道理个人有点介意用别人的API。。

**Comment by kfyidrig** [comment]
嘿嘿嘿，他也用的第三方的，开发者表示找图头都找秃了

**Comment by LIlGG** [comment]
> 嘿嘿嘿，他也用的第三方的，开发者表示找图头都找秃了

不知道我个人图床能否开发一个API来调用。

**Comment by kfyidrig** [comment]
可以找找api开源，来做个这个主题专属的，嘿嘿嘿
他的电脑端：https://api.btstu.cn/sjbz/api.php?lx=dongman&format=images
手机端：https://api.uomg.com/api/rand.img2?sort=二次元&format=images

**Comment by LIlGG** [comment]
> 嘿嘿嘿，他也用的第三方的，开发者表示找图头都找秃了

这些问题后面再考虑。哈哈。这周怕是没时间搞了。。我先把sakura的1.2.0版本发布。然后再考虑集成这个吧

**Comment by kfyidrig** [comment]
ok，幸苦咯

**Comment by LIlGG** [comment]
> ok，幸苦咯

嗯嗯。感谢你过来提醒我。哈哈。不然我怕是都不知道还有这么优秀的主题。我先去star一下
