### ISSUE TITLE
个人资料页面跳转错误

### ISSUE THREAD

**Issue by zhajianjun** [LIlGG/halo-theme-sakura#400]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7

### 建议/问题

博客页面点击右上角的头像进入到个人信息页面，永远是admin账户的页面，而不是当前登录人的个人信息。管理员用户改成其它的也不行，反而会报用户不存在错误。

https://github.com/LIlGG/halo-theme-sakura/assets/40648630/50110af5-55e8-4cbb-851e-4515fac7d973

**Comment by LIlGG** [comment]
感谢反馈，确实存在这个问题
