### ISSUE TITLE
代码块不解析代码语言标记

### ISSUE THREAD

**Issue by itqzy** [LIlGG/halo-theme-sakura#420]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.7.0

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/45928094/ee27ce01-17e5-4eea-b40a-70954502d4a8)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/45928094/8980652c-4b69-4346-b09c-bfafd46b9523)

标记了代码语言但是在文章代码还是会自动选择auto，然后在文章内就会乱显示语言类型。

**Comment by LIlGG** [comment]
感谢反馈，我会验证一下
