### ISSUE TITLE
文章的换行问题

### ISSUE THREAD

**Issue by xiaofengjue** [LIlGG/halo-theme-sakura#421]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.8

### 建议/问题

文章内容没有换行，实测访问也是没有换行
![1691982571311](https://github.com/LIlGG/halo-theme-sakura/assets/37132723/27780f3f-b2ff-4e3a-b5e7-9c9d166575bb)

**Comment by LIlGG** [comment]
尝试过其他主题了吗

**Comment by xiaofengjue** [comment]
> 尝试过其他主题了吗

我刚刚试了earth主题也有这个问题，那应该是halo自身问题了

**Comment by LIlGG** [comment]
> > 尝试过其他主题了吗
> 
> 我刚刚试了earth主题也有这个问题，那应该是halo自身问题了

可以前往 Halo 提一个 issue

**Comment by xiaofengjue** [comment]
> > > 尝试过其他主题了吗
> > 
> > 
> > 我刚刚试了earth主题也有这个问题，那应该是halo自身问题了
> 
> 可以前往 Halo 提一个 issue

ok
