### ISSUE TITLE
文章中有序/无序列表的样式渲染优化

### ISSUE THREAD

**Issue by Groupsun** [LIlGG/halo-theme-sakura#422]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.8

### 建议/问题

在文章中插入有序/无序列表时，会加入一个包围的虚线框，对于一级的列表还可以，但是多级的列表样式就会变得很奇怪：

![image](https://github.com/LIlGG/halo-theme-sakura/assets/31958506/1067347c-cd14-429d-9cba-924733b98dcc)

能否考虑去掉该虚线框或者使用其他样式？

**Comment by masteranthoneyd** [comment]
同问, 看起来怪怪的
![image](https://github.com/LIlGG/halo-theme-sakura/assets/23326293/f899fd0f-4476-4327-bc93-f92f949feb64)
