### ISSUE TITLE
我想修改瞬间的发布日期，应该如何操作

### ISSUE THREAD

**Issue by chgy123** [LIlGG/halo-theme-sakura#427]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.8

### 建议/问题

我想修改瞬间的发布时间

![G LNP83}KGU} XAN}EOTLWP](https://github.com/LIlGG/halo-theme-sakura/assets/86524162/4f3b6971-0c6a-46f3-bad1-74f7e660fc18)

在数据库中找到了对应位置，接下来应该如何操作

![OFRVR7GH(SMAHG68)T1 ~KC](https://github.com/LIlGG/halo-theme-sakura/assets/86524162/043fbf7e-7015-419a-8221-4544a2ad640d)

**Comment by LIlGG** [comment]
抱歉回复的有点晚，但你这个问题与主题无关哈，建议去 Halo 发 issue 或者 discussions
