### ISSUE TITLE
使用ByteMD编辑器时，该主题怎么设置多个图片（横向）并列居中？

### ISSUE THREAD

**Issue by Snychng** [LIlGG/halo-theme-sakura#428]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.8.0

### 建议/问题

使用ByteMD编辑器，该主题怎么设置多个图片（横向）并列居中，代码块中的style好像并不能被识别。

**Comment by LIlGG** [comment]
抱歉回复的有些晚，不过这个问题与主题没关系。

原生的 Markdown 并不支持对图片进行调整，而且 ByteMD 编辑器不支持 HTML。

你可以尝试使用 https://www.halo.run/store/apps/app-kqZUw，这个编辑器可以使用 html 自定义。
或者可以使用默认编辑器搭配 https://www.halo.run/store/apps/app-NgHnY 插件，也可以实现。
