### ISSUE TITLE
当前主题新版过旧，halo商店已经无法下载。

### ISSUE THREAD

**Issue by leeima** [LIlGG/halo-theme-sakura#430]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.9.1

### 建议/问题

可以建个交流群吗

**Comment by LIlGG** [comment]
应用市场使用的版本校验与后端不同，所以导致无法校验到类似于 `1.x.x` 这类的，只能校验 `>=1.x.x` 这类。

**Comment by ruibaby** [comment]
现在已经支持。
