### ISSUE TITLE
手机查看网页时，如果标题过长会和后面的时间重叠

### ISSUE THREAD

**Issue by KianaMyWife** [LIlGG/halo-theme-sakura#435]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.10

### 建议/问题

可以将标题在时间前换行或者时间放在标题上面

**Comment by LIlGG** [comment]
感谢反馈，我会抽空复现并进行修复。

**Comment by LIlGG** [comment]
测试之后没有发现此问题，当内容过长时，在手机端只会显示两行，多余的会以 ... 代替。

<img width="376" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/f2a1bd67-3a88-48c5-96c5-b81f604b0908">

**Comment by KLBin** [comment]
> 测试之后没有发现此问题，当内容过长时，在手机端只会显示两行，多余的会以 ... 代替。
> 
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/31335418/288676777-f2a1bd67-3a88-48c5-96c5-b81f604b0908.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODYwMTYsIm5iZiI6MTcxMjQ4NTcxNiwicGF0aCI6Ii8zMTMzNTQxOC8yODg2NzY3NzctZjJhMWJkNjctM2E4OC00OGM1LTk2YzUtYjgxZjYwNGIwOTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEwMjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmODI2ZDU3NDI2NTc3MjE2ODI2MTE4OTE5YzdkNTA3YjA2ZTViZmE1OWIxOTNhYzVmNmEzMjA1Y2FkNGE3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggu31XmzcbrC6mAPkNd0YAz05ZE_CiOBrEEYcEAGkYE">

可能指的是这个首页的文章时间？
![image](https://github.com/LIlGG/halo-theme-sakura/assets/55175443/5041875e-ff31-49c9-b574-4a47c32d8625)

**Comment by LIlGG** [comment]
> 可能指的是这个首页的文章时间？

感谢感谢，应该是这里的问题。
