### ISSUE TITLE
公告栏功能增加

### ISSUE THREAD

**Issue by padoru233** [LIlGG/halo-theme-sakura#436]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.10.0

### 建议/问题

公告栏无法渲染HTML，希望能增加支持

**Comment by LIlGG** [comment]
在 https://github.com/LIlGG/halo-theme-sakura/commit/f450e70ed79a70284cb701f2ab69662268a90837 中已经支持此功能，但还未发布正式版本，下个版本就会支持了
