### ISSUE TITLE
公告内容无法嵌入html标签

### ISSUE THREAD

**Issue by pig-gua** [LIlGG/halo-theme-sakura#437]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.10.0

### 建议/问题

在Halo1.x中可以在公告内容中加入html，自定义内容。但是在2.x中无法嵌入，请问有什么好的解决办法吗？

1.x版本
![Snipaste_2023-11-03_09-55-03](https://github.com/LIlGG/halo-theme-sakura/assets/80743187/d9692ef0-3857-434e-ab58-657e7fd7cd2b)

2.x版本
![Snipaste_2023-11-03_09-57-12](https://github.com/LIlGG/halo-theme-sakura/assets/80743187/440a022b-7d94-4f4b-96d3-aeea2cd0e037)

**Comment by LIlGG** [comment]
see #436
