### ISSUE TITLE
个人资料的url不正确

### ISSUE THREAD

**Issue by bingbaihanji** [LIlGG/halo-theme-sakura#441]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.10.4

### 建议/问题

首页->头像->个人资料，个人资料的url不正确，
halo目前只有一个管理员用户

**Comment by bingbaihanji** [comment]
<a href="/console/users/-" target="_blank" data-i18n="user.info" aria-label="access the personal profile page"></a>

**Comment by bingbaihanji** [comment]
href="/console/users/-"

**Comment by LIlGG** [comment]
感谢提醒，在 halo 后续版本中更新了用户界面的地址，我会进行修改。
