### ISSUE TITLE
手机端菜单栏的LOGO无法修改

### ISSUE THREAD

**Issue by XiaoZzya** [LIlGG/halo-theme-sakura#443]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

 2.10.1

### 建议/问题
![微信图片编辑_20231114194741](https://github.com/LIlGG/halo-theme-sakura/assets/88625758/23c0679f-9e52-4950-b27e-f7e43556fdf1)
这个logo要在什么地方才能改呢？

**Comment by LIlGG** [comment]
这个使用的是站点的 LOGO。

@see #364
