### ISSUE TITLE
iam与oauth2认证回调后error

### ISSUE THREAD

**Issue by AbsoluteZeroKing** [LIlGG/halo-theme-sakura#444]
### 目前使用的 Sakura 版本？

v2.0.0-beta.2

### 目前使用的 halo 版本？

2.10.2

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/45005201/c4d44f2e-bb3f-4321-953c-92ef17c51599)
比如我用官方插件的github登录后他不会直接登录进去，看url看上去是走到了/console/login?error

**Comment by LIlGG** [comment]
此问题应该无关主题，建议前往 Halo 或者插件的 github 地址去提 issue。另外根据你的描述，应当是 github 配置的问题，查看 回调地址的 http 与 https 是否设置正常。
