### ISSUE TITLE
pjax和付费内容插件有冲突

### ISSUE THREAD

**Issue by AbsoluteZeroKing** [LIlGG/halo-theme-sakura#445]
### 目前使用的 Sakura 版本？

v2.0.0-beta.2

### 目前使用的 halo 版本？

2.10.2

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/45005201/e6445a52-1b46-49e1-b021-b4b2209f6e7e)
上面这张图是正常情况，但在解锁后返回主页再进来（或者直接到这个页面有概率也会直接变成下图）
![image](https://github.com/LIlGG/halo-theme-sakura/assets/45005201/19e232bd-a569-429a-b6eb-e1b159aeb78f)
也就是整个块的内容直接没了，当页面点击刷新会正常

**Comment by LIlGG** [comment]
目前这种情况主题端没有好的办法来处理，最好交由插件来适配，例如插件在加载时主动加上 `data-pjax` 等，保证 pjax 可以重新加载插件的 js。
