### ISSUE TITLE
默认的音乐播放API多了一个问号，导致qq音乐无法解析

### ISSUE THREAD

**Issue by Musicminion** [LIlGG/halo-theme-sakura#446]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

latest[版本无关]

### 建议/问题

默认的value有问题，找了半天才发现是这个地方多了个问号，最终发出去请求的时候会出现两个问号，建议把默认值修改为**没有问号的**

<img width="787" alt="截屏2023-11-20 23 39 02" src="https://github.com/LIlGG/halo-theme-sakura/assets/84625273/f65e691b-02f5-4a94-9f40-acb130e60f10">

如下所示，似乎网易云音乐没有问题，因为网易云是默认的解析条目
<img width="989" alt="截屏2023-11-20 23 40 48" src="https://github.com/LIlGG/halo-theme-sakura/assets/84625273/b03ae1a6-333d-4dc4-918b-598372aa5520">

链接定位 https://github.com/LIlGG/halo-theme-sakura/blob/3a1358138c7a4f011c48908c27e61e95360aef9d/settings.yaml#L960

找了我一个小时，呜呜，差点还准备自建API的（

高木同学下次能不能细心点，嘻嘻(#^.^#)

**Comment by LIlGG** [comment]
emm，上个版本改动比较大，可能是测试的时候只测试了网易云音乐的，我会改一下。

**Comment by Musicminion** [comment]
> emm，上个版本改动比较大，可能是测试的时候只测试了网易云音乐的，我会改一下。

补充问一个问题，请问这个头像可以修改吗？找了半天好像没找到用户的头像修改地方？
<img width="936" alt="截屏2023-11-21 10 59 38" src="https://github.com/LIlGG/halo-theme-sakura/assets/84625273/54c83438-5995-46a0-9b6a-697f10aa8aee">

**Comment by LIlGG** [comment]
> 补充问一个问题，请问这个默认的头像可以修改吗？找了半天好像没找到用户的头像修改地方？ <img alt="截屏2023-11-21 10 59 38" width="936" src="https://user-images.githubusercontent.com/84625273/284448532-54c83438-5995-46a0-9b6a-697f10aa8aee.png">

点击 console 页面左下角三个点，进入个人资料，之后点击头像就可以修改了。这里使用的是文章发布者的头像。

**Comment by Musicminion** [comment]
我懂了哈哈哈哈我是大傻子 居然没发现感谢啦发自我的 iPhone在 2023年11月21日，15:59，Takagi ***@***.***> 写道：﻿

补充问一个问题，请问这个默认的头像可以修改吗？找了半天好像没找到用户的头像修改地方？ 

点击 console 页面左下角三个点，进入个人资料，之后点击头像就可以修改了。这里使用的是文章发布者的头像。

**Comment by yejian95** [comment]
> 我懂了哈哈哈哈我是大傻子 居然没发现感谢啦发自我的 iPhone在 2023年11月21日，15:59，Takagi ***@***.***> 写道：﻿ 补充问一个问题，请问这个默认的头像可以修改吗？找了半天好像没找到用户的头像修改地方？ 点击 console 页面左下角三个点，进入个人资料，之后点击头像就可以修改了。这里使用的是文章发布者的头像。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

同学，请问移动端怎么修改头像呢？我电脑端修改了。移动端还是原来的
