### ISSUE TITLE
没有图库页面的模板

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#45]
# 显示当前主题没有对应模板
## 如果没有模板,希望加入:stuck_out_tongue_closed_eyes:
![image](http://blog.chenjaly.cn/upload/2020/08/image-36b2a4da03e547449fb06e30ae4b9430.png)

**Comment by LIlGG** [comment]
开发版是有图库的，最新的tag是上次发布的稳定版本，里面不包含图库界面。。
你可以直接在线拉取master分支上的代码。或者等待1.2.0版本的发布

**Comment by CodeChenL** [comment]
> 开发版是有图库的，最新的tag是上次发布的稳定版本，里面不包含图库界面。。
> 你可以直接在线拉取master分支上的代码。或者等待1.2.0版本的发布

了解,大佬辛苦了,这么晚还回复

**Comment by LIlGG** [comment]
> > 开发版是有图库的，最新的tag是上次发布的稳定版本，里面不包含图库界面。。
> > 你可以直接在线拉取master分支上的代码。或者等待1.2.0版本的发布
> 
> 了解,大佬辛苦了,这么晚还回复

没有关系。那issues我就关闭了！有问题可以再打开

**Comment by CodeChenL** [comment]
> > > 开发版是有图库的，最新的tag是上次发布的稳定版本，里面不包含图库界面。。
> > > 你可以直接在线拉取master分支上的代码。或者等待1.2.0版本的发布
> > 
> > 
> > 了解,大佬辛苦了,这么晚还回复
> 
> 没有关系。那issues我就关闭了！有问题可以再打开

行

**Comment by CodeChenL** [comment]
> > > 开发版是有图库的，最新的tag是上次发布的稳定版本，里面不包含图库界面。。
> > > 你可以直接在线拉取master分支上的代码。或者等待1.2.0版本的发布
> > 
> > 
> > 了解,大佬辛苦了,这么晚还回复
> 
> 没有关系。那issues我就关闭了！有问题可以再打开

那大佬有计划加入日志页面的模板吗

**Comment by LIlGG** [comment]
有的，但目前堆积的事情还蛮多的。日志界面也没有什么好的思路，如果你有什么好的日志界面模板 可以发给我借鉴一下
