### ISSUE TITLE
电脑端修改了头像，移动端未更新

### ISSUE THREAD

**Issue by yejian95** [LIlGG/halo-theme-sakura#451]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.10

### 建议/问题

![微信图片_20231130103152](https://github.com/LIlGG/halo-theme-sakura/assets/67468639/4b3ac28e-ac29-4de5-af01-9b933f6a54e0)
![微信图片_20231130103157](https://github.com/LIlGG/halo-theme-sakura/assets/67468639/01ad9ac5-3548-4dd2-9c23-e55a63cc2169)
电脑端修改了头像，移动端未更新！

请问作者，后序版本能否添加瞬间上传图片的功能，谢谢！

**Comment by LIlGG** [comment]
这两个头像不是同一个概念。桌面端右上角，是当前登录用户的头像，因此这里展现的登录用户头像。

而对于移动端侧边栏，则显示的是站点 LOGO，并不是用户头像。

ps: 瞬间上传图片的功能会做，但目前时间不是很充足，也欢迎各位提交 PR

**Comment by yejian95** [comment]
> 这两个头像不是同一个概念。桌面端右上角，是当前登录用户的头像，因此这里展现的登录用户头像。
> 
> 而对于移动端侧边栏，则显示的是站点 LOGO，并不是用户头像。
> 
> ps: 瞬间上传图片的功能会做，但目前时间不是很充足，也欢迎各位提交 PR

感谢感谢
