### ISSUE TITLE
如果可以的话,希望大佬背景音乐可以添加qq音乐的功能

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#46]
如题,

**Comment by LIlGG** [comment]
我也想啊 哈哈 但对于博客来说，这个功能属于附属功能。优先级不会特别高，如果等博客大致功能完版，就可能添加支持QQ音乐，虾米音乐等等了。

**Comment by LIlGG** [comment]
我先当做一个扩展功能记录下来。但暂时可能不会排期

**Comment by CodeChenL** [comment]
> 我先当做一个扩展功能记录下来。但暂时可能不会排期

有记录就行了,大佬先干正事

**Comment by ruibaby** [comment]
啊啊啊啊啊，我也好想要～

**Comment by LIlGG** [comment]
> 啊啊啊啊啊，我也好想要～

你个大水怪 你还想要什么

**Comment by LIlGG** [comment]
目前的 Beta.2 已经支持基于 Meting 的 API 了，理论上将能够支持QQ 音乐等功能，此 issue 关闭
