### ISSUE TITLE
评论后邮件通知未生效

### ISSUE THREAD

**Issue by Simple-Stark** [LIlGG/halo-theme-sakura#460]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.11.0

### 建议/问题

使用默认主题 评论后能收到邮件通知
![cd2f0439cf029632bcfe2d59b169cb2](https://github.com/LIlGG/halo-theme-sakura/assets/61400566/254b0b56-38d1-4d3d-bfa9-c61efad14043)
使用 Sakura 却收不到通知

**Comment by LIlGG** [comment]
已发布 2.0.0 版本
