### ISSUE TITLE
瞬间无法显示图片

### ISSUE THREAD

**Issue by rrbudd** [LIlGG/halo-theme-sakura#461]
### 目前使用的 Sakura 版本？

2.0.0-beta.2

### 目前使用的 halo 版本？

2.11.2

### 建议/问题

瞬间里面显示不了图片

**Comment by LIlGG** [comment]
see #357 

在 #455 中实现了九宫格图片类型，但还未发布正式版。

你可以使用 https://codeload.github.com/LIlGG/halo-theme-sakura/zip/refs/heads/next 下载开发版本进行体验。
