### ISSUE TITLE
副标题链接错误

### ISSUE THREAD

**Issue by yang316** [LIlGG/halo-theme-sakura#464]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.11.2

### 建议/问题

副标题链接错误
![1702448941940](https://github.com/LIlGG/halo-theme-sakura/assets/63343312/082f91c9-2cd0-4914-8e28-083d6e4af550)

**Comment by LIlGG** [comment]
需要在容器中定义外部访问链接，详见：

[外部访问链接](https://docs.halo.run/getting-started/install/docker-compose#:~:text=mysql%E3%80%81h2-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE)
