### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by jaslli** [LIlGG/halo-theme-sakura#468]
### 目前使用的 Sakura 版本？

2.0

### 目前使用的 halo 版本？

 2.11.2

### 建议/问题

我这两天使用了这个主题，发现了一些问题，顺带给您这边提供一些个人的使用建议
1. 不知道是不是我使用了第三方缓存的原因，每篇文章的目录点击后都会回到最上面（类似于go to top），不会定位到具体的标题上面。
2. 登录用户那里只有个人资料和退出登录，建议添加一个控制台，不然每次都要点击到个人资料在切换到控制台
3. 归档页面希望可以使用时间轴或者是分页查看文章信息，不然就像我网站一样，根本检索不到文章信息，全是时间信息
4. 主题风格只能添加图片，希望设置背景色
5. 希望可以设置自己的加载图

个人网站yww52.com，以上问题或者是建议可以来我的网站测试。

**Comment by LIlGG** [comment]
感谢提供的宝贵建议，不过我建议多个问题最好分开提交 issue，这样对于跟踪问题来说很有帮助。下面是相关的一些回答：

> 1. 不知道是不是我使用了第三方缓存的原因，每篇文章的目录点击后都会回到最上面（类似于go to top），不会定位到具体的标题上面。

查看了你的文章，你的文章未生成 ID，因此应该是 https://github.com/halo-dev/halo/pull/4997 的问题，在 Halo 2.11.2 中应该已经修复。如果你的文章是在 2.11.0 - 2.11.2 之间创建的，建议保存再发布一次。

> 2. 登录用户那里只有个人资料和退出登录，建议添加一个控制台，不然每次都要点击到个人资料在切换到控制台

由于目前 Halo 2.x 是支持多用户的，在管理员开启注册的情况下，大部分用户注册后可能没有后台管理的权限。主题端跳转到个人中心应该是最为恰当的做法。

> 3. 归档页面希望可以使用时间轴或者是分页查看文章信息，不然就像我网站一样，根本检索不到文章信息，全是时间信息

归档页面有计划重写 #48 ，但没有太多的想法，期待想法或者 PR。 

> 4. 主题风格只能添加图片，希望设置背景色

可以考虑，但优先级不会很高，并且这块修改起来较为麻烦，所以可以作为低优先级的工作。

> 5. 希望可以设置自己的加载图

目前并不存在所谓的加载图，默认提供的图片是作为最终措施而存在的。它会在主题使用者所提供的所有加载图失效之后出现，因此需要预设在主题内部。后面我会考虑更换加载图，选择更加美观的加载图。

**Comment by jaslli** [comment]
好的，我理解了，我没写过halo主题，关于第四和第五这种基础预设样式，按理应该是可以动态修改的吧，或者我是否可以通过导入自设定的css或者js直接覆盖呢

**Comment by LIlGG** [comment]
> 好的，我理解了，我没写过halo主题，关于第四和第五这种基础预设样式，按理应该是可以动态修改的吧，或者我是否可以通过导入自设定的css或者js直接覆盖呢

可以通过自定义 css 和 js 修改主题内的任何内容。
在后台 -> 代码注入中就可以进行修改。

另外针对于主题 pjax 之后的情况，你可以使用主题抛出的事件
```
window.addEventListener("sakura:refresh", function() {
    // todo
})
```
