### ISSUE TITLE
使用文档链接无法打开

### ISSUE THREAD

**Issue by dhe090** [LIlGG/halo-theme-sakura#472]
### 目前使用的 Sakura 版本？

2.0

### 目前使用的 halo 版本？

2.11.2

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/47225023/d5baeabf-f512-48cb-833e-75e573a60e09)

**Comment by LIlGG** [comment]
感谢~确实无法打开了，应该是我博客迁移到 2.x 之后链接更改了，我改一下。
