### ISSUE TITLE
麻烦问一下这个网站logo点击跳转的路径是写死的吗

### ISSUE THREAD

**Issue by 516966395** [LIlGG/halo-theme-sakura#474]
### 目前使用的 Sakura 版本？

 2.0.0

### 目前使用的 halo 版本？

 2.11.1

### 建议/问题

这个logo跳转的路径是写死的吗  还是可配置的   `<a data-pjax="" href="http://blog/" aria-label="access the homepage of this website" data-pjax-state=""> `

**Comment by 516966395** [comment]
<a data-pjax="" href="http://blog/" aria-label="access the homepage of this website" data-pjax-state="">

**Comment by LIlGG** [comment]
是可配置的。取的是你的站点路径。即 [站点外部访问地址](https://docs.halo.run/getting-started/install/docker-compose#:~:text=mysql%E3%80%81h2-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE)。

**Comment by 516966395** [comment]
好的谢谢
