### ISSUE TITLE
关于文章页的右侧导航窗口一点小建议

### ISSUE THREAD

**Issue by vivioning** [LIlGG/halo-theme-sakura#475]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.11.0

### 建议/问题

页面是：[https://www.southxs.com/archives/play-halo](https://www.southxs.com/archives/play-halo)

在阅读文章的时候，右侧的导航窗口的字体，是否可以做成动态配置（在后台的文章页配置里面）？字体感觉有点大了，标题与标题之间没有很明显的差距，颜色的对比不知道可否深一些，
![image](https://github.com/LIlGG/halo-theme-sakura/assets/19700469/5ad888b9-19e1-48cc-9d63-f05397024956)

当H标签设置比较多的时候，效果就像下面这样，有点看不太清
![image](https://github.com/LIlGG/halo-theme-sakura/assets/19700469/33e473dd-3598-446c-9b29-712d1d39dc7e)

**Comment by LIlGG** [comment]
感谢反馈。

> 在阅读文章的时候，右侧的导航窗口的字体，是否可以做成动态配置（在后台的文章页配置里面）？字体感觉有点大了，标题与标题之间没有很明显的差距，颜色的对比不知道可否深一些，

字体的话设置配置是比较困难的，目前也没有办法对字体进行更换。可能增加一下对比度，然后增加对应间距应该可以。

> 当H标签设置比较多的时候，效果就像下面这样，有点看不太清

同上面一样，增加对应间距应该就可以。或者后续考虑将最大宽度再调大一点
