### ISSUE TITLE
文章页内点作者头像跳转页面可否编辑

### ISSUE THREAD

**Issue by leeyin98** [LIlGG/halo-theme-sakura#477]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.11.3

### 建议/问题

文章页内点作者头像跳转页面报500，我想让点击后跳转**关于**页面，不知是否支持，或者如何解决，感谢作者！
![image](https://github.com/LIlGG/halo-theme-sakura/assets/39760117/276b43eb-1acc-4491-b13f-74e6f1d9ab4a)

**Comment by leeyin98** [comment]
好叭，这似乎是halo缺少author模板引擎的问题，我去那边看看

**Comment by LIlGG** [comment]
> 好叭，这似乎是halo缺少author模板引擎的问题，我去那边看看

Halo 现在是有作者页面的，这个页面需要主题来实现。目前本主题暂时没有提供这个界面。

**Comment by LIlGG** [comment]
> > 好叭，这似乎是halo缺少author模板引擎的问题，我去那边看看
> 
> Halo 现在是有作者页面的，这个页面需要主题来实现。目前本主题暂时没有提供这个界面。

不过倒是可以使用分类之类的页面来充当作者页，并展示当前作者下的所有文章

**Comment by leeyin98** [comment]
> > > 好叭，这似乎是halo缺少author模板引擎的问题，我去那边看看
> > 
> > 
> > Halo 现在是有作者页面的，这个页面需要主题来实现。目前本主题暂时没有提供这个界面。
> 
> 不过倒是可以使用分类之类的页面来充当作者页，并展示当前作者下的所有文章

soga
确实，可以自定义页面路径的话会更好，可以不需要指向作者页面。配置默认/authors/${username}，支持改成/about或者/archives之类的自定义页面来进行跳转

**Comment by leeyin98** [comment]
再提一个小小的用户体验问题，就是主题风格中错删、误删了其中一个或多个风格后没办法单独重置回来，插件的重置操作暂时还不敢进行操作。

**Comment by LIlGG** [comment]
> 再提一个小小的用户体验问题，就是主题风格中错删、误删了其中一个或多个风格后没办法单独重置回来，插件的重置操作暂时还不敢进行操作。

确实会有这个问题，只不过目前这块没有很好的办法，需要 Halo 支持局部配置重置才行。
