### ISSUE TITLE
字体css能不能换个cdn

### ISSUE THREAD

**Issue by mxyx0412** [LIlGG/halo-theme-sakura#479]
### 目前使用的 Sakura 版本？

2.0.0

### 目前使用的 halo 版本？

2.11.3

**Comment by LIlGG** [comment]
不是特别能理解你的意思，能否详细描述一下你的需求？

目前字体 css 使用的是 `https://fonts.googleapis.com/css`，此地址在国内是具有解析的

<img width="1344" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/32bf8a53-4601-4496-a676-9ec8ea0fc446">

并且针对于字体我做了 `阻塞渲染，非阻塞加载` 相关的优化。
