### ISSUE TITLE
点击主页logo会跳转到反代前的地址而不是跳转到反代后的域名

### ISSUE THREAD

**Issue by zhiyinp** [LIlGG/halo-theme-sakura#481]
### 目前使用的 Sakura 版本？

 2.0.0

### 目前使用的 halo 版本？

 2.13.1

### 建议/问题

希望能在主题设置增加一个设置logo跳转地址的功能，能自己设置跳转的域名，不然反代后每次点logo都会跳转到反代前的localhost:端口，而不是网站主页的域名

**Comment by LIlGG** [comment]
主页 logo 跳转的地址为 `site.url`，即站点外部访问链接。
此链接需要在 [外部访问链接](https://docs.halo.run/getting-started/install/docker-compose#%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA:~:text=%E5%AE%9E%E9%99%85%E9%9C%80%E8%A6%81%E4%BF%AE%E6%94%B9-,%2D%20%2D%2Dhalo.external%2Durl%3Dhttp%3A//localhost%3A8090/,-%23%20%E7%AB%AF%E5%8F%A3%E5%8F%B7%20%E9%BB%98%E8%AE%A4) 中进行设置，设置之后点击头像即可跳转至此目标地址。
