### ISSUE TITLE
BUG 文件名与请求路径不同

### ISSUE THREAD

**Issue by Flik6** [LIlGG/halo-theme-sakura#489]
### 目前使用的 Sakura 版本？

2.1.0

### 目前使用的 halo 版本？

2.13

### 建议/问题

# 原因
![image](https://github.com/LIlGG/halo-theme-sakura/assets/19778582/57e7d7d6-ab61-40c6-b9cb-65f84666f01c)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/19778582/31ccca93-e8f3-4639-adee-6f337874c0e3)
js请求路径为category.min.js ，实际build结果的文件名为categories.min.js
导致404

# 临时解决方法
1. 去halo跟目录下
2. 到/themes/theme-sakura/templates/assets/dist/page
3. 修改categories.min.js为category.min.js

**Comment by LIlGG** [comment]
<img width="744" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/ed5e222b-2c65-4dd0-9117-5f475bd21bc6">

我的线上环境中请求似乎没有问题。出现该异常时请求的页面是分类吗？

**Comment by Flik6** [comment]
> <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/31335418/313531497-ed5e222b-2c65-4dd0-9117-5f475bd21bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjczMzgsIm5iZiI6MTcxMDkyNzAzOCwicGF0aCI6Ii8zMTMzNTQxOC8zMTM1MzE0OTctZWQ1ZTIyMmItMmM2NS00ZGQwLTkxMTctNWY0NzViZDIxYmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5MzAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNWQxYmQ5NGJkYWU5ZTY3NjQxZmZjMzRmODE3MTIzNjljYmE2ZmI5MWYxYTUyMzVhY2MyZGNlYjM2NmU5NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a1vBk89Wh35Yh92BnbKayEHa9pya4IvSa5sIhMCkD5M">
> 我的线上环境中请求似乎没有问题。出现该异常时请求的页面是分类吗？

是分类   尝试在halo主题上重新安装 还是没有这个文件

**Comment by LIlGG** [comment]
> 是分类 尝试在halo主题上重新安装 还是没有这个文件

有可能是访问了分类归档页面。目前请求的 js 是根据目标页面的 `_templateId` 来确定的。理论上来说应该不会有什么影响。后续会修复一下。

感谢反馈！
