### ISSUE TITLE
没有给图库设置头图时图库图片进行加载时会一直转圈

### ISSUE THREAD

**Issue by Yaklo** [LIlGG/halo-theme-sakura#490]
### 目前使用的 Sakura 版本？

 2.1.0

### 目前使用的 halo 版本？

 2.13.1

### 建议/问题

通过其他页面第一次点击图库进入图库页面时，通过302重定向加载的图片在加载完后页面的加载图标不会消失，同时图片可以进行点击查看但也一直留白。

目前发现有以下几种形式能临时解决：
①电脑浏览器调整窗口大小可以显示出图片内容
②进入其他页面再点击图库返回图库页可以显示出图片内容
③刷新页面或者不通过点击博客菜单入口的形式直接进入图库页可以显示出图片内容

该问题可以通过清空浏览器缓存或是禁用浏览器缓存的形式稳定复现

可以通过我的博客进行复现
主页：https://blog.yaklo.cn/
图库页：https://blog.yaklo.cn/photos
或是通过我所使用的图片链接进行测试
https://sodayo.yaklo.cn/project/dlod/PNCJ/20240317025827.png
*使用Cloudreve存储策略为OneDrive的外链，所以会有302重定向跳转*

**Comment by LIlGG** [comment]
感谢反馈。 确实是有这样的问题，但我还需要在本地进行复现。

**Comment by Yaklo** [comment]
刚刚发现这个bug和302加载图片无关，而是没有设置头图的原因。只要没置头图就能稳定复现

**Comment by LIlGG** [comment]
> 刚刚发现这个bug和302加载图片无关，而是没有设置头图的原因。只要没置头图就能稳定复现

我在本地测试时，即便没有设置封面图，也没办法复现此问题。

**Comment by Yaklo** [comment]
那感觉还是302的问题，我这边图片现在也换成朴素的直链了。就当我前面是来酒馆点炒饭的吧😂
