### ISSUE TITLE
进入文章后显示500内部服务器错误

### ISSUE THREAD

**Issue by ZanJoye** [LIlGG/halo-theme-sakura#492]
### 目前使用的 Sakura 版本？

2.1.0

### 目前使用的 halo 版本？

2.13.0

### 建议/问题

[1.zip](https://github.com/LIlGG/halo-theme-sakura/files/14731508/1.zip)
这是日志文件，麻烦了

**Comment by LIlGG** [comment]
查看日志报错 `${site.url}/welcoming` 。但理论上来说我代码中写的应该是 `${site.url}`。不是很清楚这个 `welcoming` 从何而来。
是否有使用过其他第三方的插件？

**Comment by LIlGG** [comment]
如果没有其他进一步的信息，此 Issue 将进行关闭。如果有补充欢迎随时打开此 Issue。
