### ISSUE TITLE
关于手机版页面的优化建议

### ISSUE THREAD

**Issue by SmmnaBeta** [LIlGG/halo-theme-sakura#493]
### 目前使用的 Sakura 版本？

2.1.0

### 目前使用的 halo 版本？

2.13.1

### 建议/问题

非常抱歉，又是我😅首先我非常喜欢这个主题，所以我又来提建议啦。奈何咩有开发能力还望见谅!感谢作者和	
相关开发者的共同努力!
建议如下:
1.手机版页面，菜单名称超过(包含)4个字以上会进行换行，子菜单会展示在主菜单右下角，希望能优化布局。如:强制单行(ps: 当前样式，居中一行放10个字是够的，可能与不同机型、分辨率、浏览器有关。)子菜单仍进行折叠。
2.在手机版页面使用音乐插件时，歌词会被遮挡。希望优化手机版对兼容插件的布局。
3.手机版菜单开关按钮动画的优化

**Comment by LIlGG** [comment]
非常感谢提供的建议。

1. 子菜单展示在主菜单右下角，这是为了区分主菜单和子菜单。一行显示十个字符的话，尽管子菜单可以折叠，但子菜单如果展开，就会无法控制样式，最终效果也会呈现为当前的菜单状态。对于菜单名称字符换行限制的字符数量后续可以做一下调整，但可能仍旧会限制字符。
2. 确实会存在这个问题，将优化手机端收起音乐播放器时直接折叠回原位。
3. 确实有优化全局动画的想法，但这个比较耗费精力，see #408 

提一个建议，在提交 issue 时，建议将多个问题分 issue 处理，这样可以更好的对问题进行跟踪和反馈。
