### ISSUE TITLE
主题的行号显示关闭不生效

### ISSUE THREAD

**Issue by shuqian2017** [LIlGG/halo-theme-sakura#495]
### 目前使用的 Sakura 版本？

 Sakura 2.1.0

### 目前使用的 halo 版本？

halo  2.14.0

### 建议/问题

［主题]->[文章页]->[开启代码行号] 中关闭行号显示不生效，未安装第三方高亮插件
![image](https://github.com/LIlGG/halo-theme-sakura/assets/31362005/919a67a3-438d-43aa-bc85-dfbcf58d4b4a)

**Comment by LIlGG** [comment]
感谢反馈，目前确实存在这个问题。
