### ISSUE TITLE
优化友链界面

### ISSUE THREAD

**Issue by rong6** [LIlGG/halo-theme-sakura#498]
### 目前使用的 Sakura 版本？

 2.0.0

### 目前使用的 halo 版本？

2.12.2

### 建议/问题

目前友链界面还是有待优化，尤其是手机端图标全挤在一起很难受，希望手机端也可以按PC端一样以列表显示。

**Comment by LIlGG** [comment]
感谢反馈这个问题，手机端我会修改为单行显示。但这样可能会导致列表有点长。
