### ISSUE TITLE
头部标题栏个人信息缺失、文章信息缺失以及主题选择选项缺失

### ISSUE THREAD

**Issue by Groupsun** [LIlGG/halo-theme-sakura#507]
### 目前使用的 Sakura 版本？

2.2.1

### 目前使用的 halo 版本？

2.15.1

### 建议/问题

更新到最新的2.2.1版本主题后，发现头部标题栏的个人信息缺失：
<img width="165" alt="图片" src="https://github.com/LIlGG/halo-theme-sakura/assets/31958506/6b530b46-682d-47f5-bccb-10219dfa18db">
如果没有登陆的话就是这个样子：
<img width="118" alt="图片" src="https://github.com/LIlGG/halo-theme-sakura/assets/31958506/e2b8940c-71bb-4487-8dad-2b90a3c5940e">
首页的文章创建时间、浏览次数、评论数目等信息也缺失了：
<img width="807" alt="图片" src="https://github.com/LIlGG/halo-theme-sakura/assets/31958506/f869fe9f-0cf4-41f5-9fba-22cd762ec1dd">
文章页这些信息也都缺失了：
<img width="769" alt="图片" src="https://github.com/LIlGG/halo-theme-sakura/assets/31958506/dfb40a1d-0293-403f-8dff-0185802df216">
同时在页面右下角处的切换主题选项也缺失了：
<img width="523" alt="图片" src="https://github.com/LIlGG/halo-theme-sakura/assets/31958506/4e59b293-6469-40cf-9c47-c82c05c2bf40">

**Comment by LIlGG** [comment]
这应该是你的主题 i18n 没有加载成功的原因。你可以试试清空缓存或者重载主题设置。

**Comment by Groupsun** [comment]
清除缓存及重载主题设置后正常了，谢谢。
