### ISSUE TITLE
PC端头像和搜索和菜单重叠了

### ISSUE THREAD

**Issue by zxxhz** [LIlGG/halo-theme-sakura#508]
### 目前使用的 Sakura 版本？

 2.2.1

### 目前使用的 halo 版本？

 2.15.2

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/62083314/37aa77d2-66cf-4972-b879-0e0e6dbdd064)
今天更新完Sakura主题之后就这样了，之前是正常在右边的，设置同样的

**Comment by LIlGG** [comment]
清理一下缓存试试。这次确实改了这里。但我线上的测试没有问题来的

**Comment by zxxhz** [comment]
> 清理一下缓存试试。这次确实改了这里。但我线上的测试没有问题来的

Ctrl+F5试过了，换InPrivate窗口试过了，换浏览器试过了，手机浏览器用电脑ua试过了，问题仍存在

**Comment by LIlGG** [comment]
> > 清理一下缓存试试。这次确实改了这里。但我线上的测试没有问题来的
> 
> Ctrl+F5试过了，换InPrivate窗口试过了，换浏览器试过了，手机浏览器用电脑ua试过了，问题仍存在

可否提供一下网址？我这边去看看

**Comment by zxxhz** [comment]
> > > 清理一下缓存试试。这次确实改了这里。但我线上的测试没有问题来的
> > 
> > Ctrl+F5试过了，换InPrivate窗口试过了，换浏览器试过了，手机浏览器用电脑ua试过了，问题仍存在
> 
> 可否提供一下网址？我这边去看看

0cy.me
如有需要可以提供账号密码

**Comment by LIlGG** [comment]
<img width="434" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/1da1eea4-b40d-4b58-9cdc-3424dc56027d">

似乎你的页面结构与最新版的不一致。
下面是最新版本的页面结构。

<img width="382" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/607566a4-d0c2-4814-8f94-bcdf27ec9a7c">

目前的效果是 css 已经使用最新的了，但页面还是旧的，因此可能需要你在 Halo 后台仪表盘中，点击刷新页面缓存。

<img width="1078" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/5fac4506-a1c4-4749-af09-508d5ff3d929">

**Comment by zxxhz** [comment]
已解决
原因是我用的1panel面板中的halo，更新后镜像变成了halo-pro，本来以为pro版本不激活和正常版一样，结果出了这个问题
把compose改成halo后问题消失
