### ISSUE TITLE
退出登录界面异常

### ISSUE THREAD

**Issue by NorLorikein** [LIlGG/halo-theme-sakura#509]
### 目前使用的 Sakura 版本？

2.2.1

### 目前使用的 halo 版本？

2.15.2

### 建议/问题

![image](https://github.com/LIlGG/halo-theme-sakura/assets/117804471/7195579c-8b7b-4389-910b-f3e381bf8489)
退出登录跳转页面速度极慢，且排版错误

**Comment by LIlGG** [comment]
目前的退出登录页面是由 Halo 提供的，其可能是存在某些国内访问比较慢的资源。

后续可以在主题端优化一下，使用请求的方式退出登录。

see https://github.com/halo-dev/halo/issues/5806
