### ISSUE TITLE
黑夜模式

### ISSUE THREAD

**Issue by LIlGG** [LIlGG/halo-theme-sakura#51]
目前主题里的“关灯”只是增加遮罩，计划添加黑夜模式

**Comment by ruibaby** [comment]
那么，这个功能到底啥时候才能完成呢？

**Comment by LIlGG** [comment]
> 那么，这个功能到底啥时候才能完成呢？

所以，你要是帮我的话那这月底就能完成了😒

**Comment by ruibaby** [comment]
> > 那么，这个功能到底啥时候才能完成呢？
> 
> 所以，你要是帮我的话那这月底就能完成了😒

就这？那不是分分钟的事情吗？等着。

**Comment by LIlGG** [comment]
> > > 那么，这个功能到底啥时候才能完成呢？
> > 
> > 
> > 所以，你要是帮我的话那这月底就能完成了😒
> 
> 就这？那不是分分钟的事情吗？等着。

膜拜大佬！！！但可别整个黑色背景就放上来了 我怕怕

**Comment by ruibaby** [comment]
> > > > 那么，这个功能到底啥时候才能完成呢？
> > > 
> > > 
> > > 所以，你要是帮我的话那这月底就能完成了😒
> > 
> > 
> > 就这？那不是分分钟的事情吗？等着。
> 
> 膜拜大佬！！！但可别整个黑色背景就放上来了 我怕怕

![image](https://user-images.githubusercontent.com/21301288/90729339-04979b00-e2f9-11ea-8796-8b0a9786fc68.png)
