### ISSUE TITLE
图层冲突

### ISSUE THREAD

**Issue by NorLorikein** [LIlGG/halo-theme-sakura#513]
### 目前使用的 Sakura 版本？

2.2.1

### 目前使用的 halo 版本？

2.15.2

### 建议/问题

移动端设备下点击文章内的赞助按钮，弹出的界面和赞助二维码会被下方的评论区文本框覆盖掉( 尤其是未登录状态下还有额外的填写邮箱的文本框，几乎完全覆盖了 )，导致二维码显示不全。PC端没有测试。

**Comment by LIlGG** [comment]
在移动端下，文章赞助二维码与评论框应该是有很大一部分距离的。我测试时即便打开赞助二维码也是无法被遮挡的。能否提供对应的截图？

**Comment by NorLorikein** [comment]
> 在移动端下，文章赞助二维码与评论框应该是有很大一部分距离的。我测试时即便打开赞助二维码也是无法被遮挡的。能否提供对应的截图？

![image](https://github.com/LIlGG/halo-theme-sakura/assets/117804471/fada9179-d476-4d55-a523-57bc1c997d2c)

**Comment by NorLorikein** [comment]
如果没有开启最底下的上一篇/下一篇功能，或者当前页面只有一个上一篇或下一篇，就会导致被覆盖，一个没有就会完全覆盖
