### ISSUE TITLE
能否自行注入一个全局的CSS样式？

### ISSUE THREAD

**Issue by 99Mr-Z** [LIlGG/halo-theme-sakura#516]
### 目前使用的 Sakura 版本？

 2.2.1

### 目前使用的 halo 版本？

2.15.1

### 建议/问题

能否用户自行注入一个CSS的全局样式？经常访问萌娘百科感觉，字体的黑幕遮挡效果和模糊效果在写文的时候还是很好用的，以及有部分页面的全局模糊效果
这个是黑幕提供参考的CSS样式

 1 .heimu, .heimu a, a .heimu, .heimu a.new {
 2     background-color: #252525;
 3     color: #252525;
 4     text-shadow: none;
 5 }
 6 .heimu:hover, .heimu:active,
 7 .heimu:hover .heimu, .heimu:active .heimu {
 8     color: white !important;
 9 }
10 .heimu:hover a, a:hover .heimu,
11 .heimu:active a, a:active .heimu {
12     color: lightblue !important;
13 }
14 .heimu:hover .new, .heimu .new:hover, .new:hover .heimu,
15 .heimu:active .new, .heimu .new:active, .new:active .heimu {
16     color: #BA0000 !important;
17 }
18 
19 /*阅读更多：https://zh.moegirl.org/MediaWiki:Mobile.css 本文引自萌娘百科(https://zh.moegirl.org)，文字内容默认使用《知识共享 署名-非商业性使用-相同方式共享 3.0》协议。*/

**Comment by LIlGG** [comment]
自定义注入 css 请参考 https://docs.halo.run/user-guide/settings#%E4%BB%A3%E7%A0%81%E6%B3%A8%E5%85%A5

**Comment by 99Mr-Z** [comment]
不好意思，在设置里以下看到三个注入有点没敢乱动，以为是其他之类的代码注入，把官方的说明文档给拉下了，提了一个没有意义的议题，抱歉

**Comment by 99Mr-Z** [comment]
> 自定义注入 css 请参考 [代码注入](https://docs.halo.run/user-guide/settings#%E4%BB%A3%E7%A0%81%E6%B3%A8%E5%85%A5)

还想请教下，如果想要自行对主题进行修改，应该具备哪些知识，用什么工具？想要尝试使用chatgpt类的工具尝试下对主题进行修订，目前也就刚开始学习了点c和c++，目前看项目语言的使用类型是CSS和HTML为主。
