### ISSUE TITLE
文章页背景图和标题

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#52]
图:![image](http://blog.chenjaly.cn/upload/2020/08/image-f1e986e705db4200866fbafc64883742.png)
感觉直接把标题和某些背景搭配会比较难看,希望主题选项添加文章页头图的透明度,模糊之类的效果的选项,又或者可以设置标题和头图的位置分离

**Comment by LIlGG** [comment]
这个肯定不能是在主题的设置中，那样的话对于本主题的所有文章都会变模糊或者其他的。
我会考虑在文章中设置元数据来控制。但实际上这个问题的话，换一个图就好了。😂。
毕竟如果再弄个白色的背景，那么标题文本颜色也得调整了。。就很麻烦。

**Comment by LIlGG** [comment]
不过对于通用的透明度或者模糊，可以全局设置。后续我会测试，调整看看。先做个记录吧

**Comment by CodeChenL** [comment]
> 不过对于通用的透明度或者模糊，可以全局设置。后续我会测试，调整看看。先做个记录吧

行
