### ISSUE TITLE
随机图设置能否提供占位符

### ISSUE THREAD

**Issue by ShiinaKin** [LIlGG/halo-theme-sakura#522]
### 目前使用的 Sakura 版本？

2.2.1

### 目前使用的 halo 版本？

最新编译

### 建议/问题

rt，提供如`{post_id}`之类的占位符，在`第三方 API 自定义参数`处

需求是如果三方api对于资源id的接受参数名不叫`postid`的话，无法调用，现有的自定义参数只能是静态的

**Comment by LIlGG** [comment]
感谢反馈，可以考虑让用户自定义 postid 参数名。

**Comment by ShiinaKin** [comment]
能否给个思路，我看了一下源码：
https://github.com/ShiinaKin/halo-theme-sakura/blob/59ed652dc0ddd63ec81b3864cf13268e738bfebc/templates/macro/page-header.html#L35
这里的似乎不是很好处理

**Comment by LIlGG** [comment]
> 能否给个思路，我看了一下源码： [ShiinaKin/halo-theme-sakura@`59ed652`/templates/macro/page-header.html#L35](https://github.com/ShiinaKin/halo-theme-sakura/blob/59ed652dc0ddd63ec81b3864cf13268e738bfebc/templates/macro/page-header.html#L35) 这里的似乎不是很好处理

类似于 `${#strings.isEmpty(theme.config.random_image.rimage_other_params) ? '' : '&' + theme.config.random_image.rimage_other_params}` 这种写法即可。

例如有个配置叫做 `theme.config.random_image.custom_param` 那就可以使用  `${#strings.isEmpty(theme.config.random_image.custom_param) ? '' : '&' + theme.config.random_image.custom_param=（id != null ? id : extension.metadata.name）}`

没验证过，但大致写法如上应该就可以。
