### ISSUE TITLE
归档页面显示不全

### ISSUE THREAD

**Issue by laaacf** [LIlGG/halo-theme-sakura#523]
### 目前使用的 Sakura 版本？

2.21

### 目前使用的 halo 版本？

2.15.1

### 建议/问题

反应一个小问题，目前在halo 2.12-2.21 上，归档文章显示不全，换用其它主题可以完整显示所有归档文章。麻烦楼主能够解决这个问题吗？谢谢楼主付出，主题很好。
![](https://s2.loli.net/2024/02/13/dHlRJCEFUSh9T2V.png)

**Comment by laaacf** [comment]
不是指文章目录未展开的问题，我在2023-06之前还有很多文章，但是不能显示出来。具体参考网址：https://laaa.site

**Comment by LIlGG** [comment]
看到了。十分感谢反馈。确实存在这样的问题，应该是取值的时候只取到了第一页的。

**Comment by laaacf** [comment]
应该是我们用户感谢你的辛苦付出，我个人非常喜欢这个主题，很赞，谢谢你！
