### ISSUE TITLE
有序列表渲染格式错误

### ISSUE THREAD

**Issue by lumia1998** [LIlGG/halo-theme-sakura#526]
### 目前使用的 Sakura 版本？

2.2.1

### 目前使用的 halo 版本？

 2.15.2

### 建议/问题

文章写完后的界面和预览界面不一样,更换主题后正常,换过编辑器无效,如图所示
![cfe90d5e94c109cd69668aeb0fd3d878](https://github.com/LIlGG/halo-theme-sakura/assets/63107956/525a9420-66ed-44b7-84c9-8028036396c2)
上半部分是编辑器界面,下半部分是sakura主题文章界面

![e122371c14c08b65f3b568b34edd7661](https://github.com/LIlGG/halo-theme-sakura/assets/63107956/08b43b40-4c83-4c45-8cbf-26b930e286e4)
更换别的主题后的编辑器和文章界面一样

**Comment by LIlGG** [comment]
本主题对页面格式做了一些调整，例如标题，会加以 # 作为区分。

不过对于有序列表，这里展示为了无序列表，确实是一个 bug。

**Comment by lumia1998** [comment]
你看标题后面多个奇怪的符号呢
![image](https://github.com/LIlGG/halo-theme-sakura/assets/63107956/8c849f6d-3fce-4e15-b8e6-421bba4054fe)

**Comment by LIlGG** [comment]
> 你看标题后面多个奇怪的符号呢

主题默认样式就是这样的。

**Comment by lumia1998** [comment]
下次更新能设置个开关的选项吗,,,我这标题只有这一个符号真受不了
我看正常是2个引号啊标题的开头和结尾,我这就后面有一个还是一半..

**Comment by LIlGG** [comment]
> 下次更新能设置个开关的选项吗,,,我这标题只有这一个符号真受不了 我看正常是2个引号啊标题的开头和结尾,我这就后面有一个还是一半..

这种样式方面的很难做调整，因为审美观各不相同，做配置项也并不合适，因为太多了。所以对这种样式问题我只建议使用注入 css 代码来进行修改，例如去除标题后的符号
```css
.entry-content h2::after {
	content: ""
}
```

具体修改了哪些样式你可以看看 [halo主题sakura食用说明](https://lixingyong.com/archives/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E)

**Comment by lumia1998** [comment]
> > 下次更新能设置个开关的选项吗,,,我这标题只有这一个符号真受不了 我看正常是2个引号啊标题的开头和结尾,我这就后面有一个还是一半..
> 
> 这种样式方面的很难做调整，因为审美观各不相同，做配置项也并不合适，因为太多了。所以对这种样式问题我只建议使用注入 css 代码来进行修改，例如去除标题后的符号
> 
> ```css
> .entry-content h2::after {
> 	content: ""
> }
> ```
> 
> 具体修改了哪些样式你可以看看 [halo主题sakura食用说明](https://lixingyong.com/archives/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E)

这是修改哪部分?common下的page的css吗

**Comment by LIlGG** [comment]
> > ```css
> > .entry-content h2::after {
> > 	content: ""
> > }
> > ```

> 这是修改哪部分?common下的page的css吗

所有内容页下的二级标题。
