### ISSUE TITLE
Favicon 不显示

### ISSUE THREAD

**Issue by jinyanshenxing** [LIlGG/halo-theme-sakura#528]
### 目前使用的 Sakura 版本？

 2.2.1

### 目前使用的 halo 版本？

 2.16.0-rc.2

### 建议/问题

设置了不显示

**Comment by LIlGG** [comment]
Favicon 是否显示与主题无关，Favicon 是在 Halo 配置项中进行设置的。

**Comment by jinyanshenxing** [comment]
> Favicon 是否显示与主题无关，Favicon 是在 Halo 配置项中进行设置的。

en  我设置了 换别的主题也是不显示 在后台面板能显示出来

**Comment by jinyanshenxing** [comment]
已解决
