### ISSUE TITLE
图库页面模板死循环

### ISSUE THREAD

**Issue by NorLorikein** [LIlGG/halo-theme-sakura#529]
### 目前使用的 Sakura 版本？

2.2.1

### 目前使用的 halo 版本？

2.15.2

### 建议/问题

在首次或清除缓存后访问图库页面，会一直卡在加载的动画图标上
只有再次刷新页面或者点击图片分类按钮后才会正常显示图片
![image](https://github.com/LIlGG/halo-theme-sakura/assets/117804471/09b78fd8-12ed-430f-9572-f3ee1c0c7ca7)

**Comment by LIlGG** [comment]
或许与这个问题是一样的，但我本地未能复现。

see #490

**Comment by NorLorikein** [comment]
> 或许与这个问题是一样的，但我本地未能复现。
> 
> see #490

该问题与我站点的情况不同，我站点是一直加载，图片也是一张都没显示，模块也没有。

**Comment by LIlGG** [comment]
> 该问题与我站点的情况不同，我站点是一直加载，图片也是一张都没显示，模块也没有。

有可能是资源加载失败的问题。我之前似乎看过有人用了 `takagi-cdn` 这一个过期的 cdn。你可以检查一下。

**Comment by SakuraMuxia** [comment]
目前使用的是halo版本是2.17.1，sakura主题版本2.4.0，图库的显示出现了问题。
**问题具体如下：**
1、图片可以加载完成，但图片在页面的实际渲染高度和宽度均为0。
![alt text](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/question3.png)
**经过一些排查：**
1、更换了图片的格式，-> 无效。
2、在F12中调试了一些样式 有点效果，图片显示了。
![alt text2](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/question4.png)
**后来我发现DEMO的网站也是这样，是我网络的问题吗**
![alt text3](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/question2.png)
