### ISSUE TITLE
有些随机图加载会出现302，报错thumbnail of the cover of the post

### ISSUE THREAD

**Issue by snjl** [LIlGG/halo-theme-sakura#541]
### 目前使用的 Sakura 版本？

2.3.0

### 目前使用的 halo 版本？

 2.16.3

### 建议/问题

有些随机图加载会出现302，并且无法显示，报错：
thumbnail of the cover of the post
![image](https://github.com/LIlGG/halo-theme-sakura/assets/39609584/00ba2468-a1fc-4429-9675-24f4c99e3398)

随机图配置：
![image](https://github.com/LIlGG/halo-theme-sakura/assets/39609584/d5ffb120-d157-4b32-a499-aeae96f84feb)

出现问题的blog链接：http://blog.snjl.site/

**Comment by LIlGG** [comment]
可能是你的网络不支持 IPV6 导致的，目前为了节省随机图 API 的资源，我将其放置在了个人家庭服务器中，但由于网络限制，因此使用了 IPV6。因此如果不支持 IPV6 将可能无法访问此 API。

不过我也使用了 CDN 对接口进行了缓存，理论上来说在部分情况下 ipv4 也是可以访问到的。

**Comment by snjl** [comment]
应当是支持的，我能用ipv6下载torrent的数据，并且我能够正常访问其他人搭建的halo+Sakura，所以我有些怀疑是不是我配置问题

**Comment by snjl** [comment]
我尝试更换随机图API地址为：https://api.btstu.cn/sjbz/api.php?lx=dongman&format=images 能够解决问题，所以我感觉可能是https://api.lixingyong.com/api/images存在一些无效的链接？

**Comment by LIlGG** [comment]
> 我尝试更换随机图API地址为：https://api.btstu.cn/sjbz/api.php?lx=dongman&format=images 能够解决问题，所以我感觉可能是https://api.lixingyong.com/api/images存在一些无效的链接？
> 

也确实是有这个可能，当初迁移时部分图片损坏。。虽然备份数据还存在但图片比较难以恢复。
