### ISSUE TITLE
为多行代码框添加长代码自动换行功能

### ISSUE THREAD

**Issue by Yaklo** [LIlGG/halo-theme-sakura#543]
### 目前使用的 Sakura 版本？

 2.3.0

### 目前使用的 halo 版本？

 2.15.0

### 建议/问题

可以为多行代码框添加长代码自动换行功能吗
效果图：
![Snipaste_2024-06-30_00-21-24](https://github.com/LIlGG/halo-theme-sakura/assets/50908861/3a1aaa90-052c-4c28-84bc-a74516849ffe)

**Comment by LIlGG** [comment]
确实可以考虑添加此功能。
