### ISSUE TITLE
文章无法显示有序列表

### ISSUE THREAD

**Issue by Terryisthebest** [LIlGG/halo-theme-sakura#549]
### 目前使用的 Sakura 版本？

已激活主题: [Sakura 2.3.0]

### 目前使用的 halo 版本？

2.17.0

### 建议/问题

![346247068-99125c98-fc6e-471b-b8a6-19cd56623825](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/2a482858-ac30-4284-8b7f-a4954d4854e8)
![346247078-f217b645-9a44-4703-b749-0a754c892a32](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/3f583a05-f6d7-4daf-bea7-4d54fe2a006d)

**Comment by LIlGG** [comment]
已在 #547 中修复。将会发布在下个版本中。

**Comment by Terryisthebest** [comment]
> 已在 #547 中修复。将会发布在下个版本中。

OKOK～
