### ISSUE TITLE
浏览器夜览模式下高亮文字无法正常显示

### ISSUE THREAD

**Issue by Terryisthebest** [LIlGG/halo-theme-sakura#550]
### 目前使用的 Sakura 版本？

2.3.0

### 目前使用的 halo 版本？

2.17.0

### 建议/问题

![截屏2024-07-08 上午11 47 32](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/afb2e72b-b8ac-4abb-a43d-a42ec624a696)
![截屏2024-07-08 上午11 47 53](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/ceabf5ff-b89e-4a93-875c-4113c2ea42f2)

**Comment by LIlGG** [comment]
这个似乎没有什么好的解决办法。因为背景色与文本颜色是由用户主动设置的。

唯一能做的优化，就是当用户设置了背景色但未设置文本颜色时，将文本颜色改为黑色。 但你也不能保证用户是否将背景色也设置为了黑色。

**Comment by Terryisthebest** [comment]
ok, 那我把高亮文字主动设为黑色试试

**Comment by Terryisthebest** [comment]
主动把文字设为黑色后，浅色/深色模式下都能正确显示了！
![截屏2024-07-08 下午12 13 53](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/0d429557-0a00-4736-9a03-ca952f358d69)
![截屏2024-07-08 下午12 13 40](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/8f2d7dca-3d0d-4f9e-9862-5047477a7a46)
诶那如果默认将文字的高亮与字体颜色绑定，是否就可以解决这个问题了～

**Comment by LIlGG** [comment]
> 诶那如果默认将文字的高亮与字体颜色绑定，是否就可以解决这个问题了～

问题就是如何绑定。由用户自定义的内容确实比较困难。我会尝试在用户没有自行添加字体颜色时，将其默认改为黑色。应该能解决大部分问题。

**Comment by Terryisthebest** [comment]
okok，感谢！！
