### ISSUE TITLE
提几个改善的小建议

### ISSUE THREAD

**Issue by Terryisthebest** [LIlGG/halo-theme-sakura#552]
### 目前使用的 Sakura 版本？

2.3.0

### 目前使用的 halo 版本？

2.17.0

### 建议/问题

很喜欢这个主题！！
因为日常把这个作为同学的学习交流网站，所以使用的时候偶尔有些感想就在这里聊聊～
我不是专业的程序员，有些复杂的代码啊什么的我也不会弄，所以提的问题可能会比较愚蠢，请见谅！

1.文章下方只能给评论点赞，但是能不能给文章点赞呢？比如在这里加个小爱心什么的：
![截屏2024-07-08 下午7 17 25](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/e74800e3-4646-4273-b912-574e7cae8fe5)

2.可不可以实现文章下方显示本文标签，点击后可以跳转到标签页面，就像微信公众号里这样：
![截屏2024-07-08 下午7 19 38](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/9ac0be18-1bf3-4d41-880d-00383368d166)

3.发布文章的时候只能选择一个作者，如果是两个人联合发表文章怎么办嘞
![截屏2024-07-08 下午7 13 58](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/c0329e48-f692-4620-a066-1cae2700b368)

4.文章封面的随机图如果不使用默认的api的话，能不能让它自动从自己上传的图集里选一张；而且每次刷新的时候都会重新加载新的随机图作为封面，能不能实现第一次加载的随机图直接保存到本地作为固定的封面哩

5.点击作者头像后跳转到这个作者发布的所有文章的页面：
![截屏2024-07-08 下午7 44 03](https://github.com/LIlGG/halo-theme-sakura/assets/140528909/00e9efb3-71b6-430c-9716-fd5128193818)
不知道是否可以把这个页面丰富一下呢～比如把这个页面作为作者的资料页，显示作者的个性签名，也可以加个给作者点赞的功能什么的

当然，以上只是个人的一些小建议，只是提供参考，不采纳也可以哒！后面想到什么点子我再提～

**Comment by LIlGG** [comment]
感谢反馈。不过建议将不同的 issue 分开提交，方便跟踪问题。

> 1. 文章下方只能给评论点赞，但是能不能给文章点赞呢？

文章可以增加点赞的功能，不过目前本主题还没有实现这个功能。

> 2. 可不可以实现文章下方显示本文标签，点击后可以跳转到标签页面

目前是有这样的功能的，见下图

<img width="945" alt="image" src="https://github.com/LIlGG/halo-theme-sakura/assets/31335418/171b50ae-eddc-4532-8faf-28ef3b33ad1e">

> 3. 发布文章的时候只能选择一个作者

这里的作者指的是 Owner，而不是 Contributions 。只要多个人编辑过同一个文章，就会自动添加至 Contributions 中。主题也支持显示多个作者。

> 4. 文章封面的随机图如果不使用默认的api的话，能不能让它自动从自己上传的图集里选一张；而且每次刷新的时候都会重新加载新的随机图作为封面，能不能实现第一次加载的随机图直接保存到本地作为固定的封面哩

并不可以，目前随机图就是使用的第三方随机图，与 Halo 本身无关。
如果使用默认 API，刷新时会保持幂等，即同一个接口在一段时间内返回的随机图是同一个的。

> 5. 比如把这个页面作为作者的资料页，显示作者的个性签名，也可以加个给作者点赞的功能什么的

目前还没有优化的计划。但确实可以优化。
