### ISSUE TITLE
在哪改头像嘞

### ISSUE THREAD

**Issue by wsuint** [LIlGG/halo-theme-sakura#556]
### 目前使用的 Sakura 版本？

 2.4.0

### 目前使用的 halo 版本？

 2.17.1

### 建议/问题

首屏的默认头像和侧边栏默认头像，我没有找到入口改，是需要该文件吗？

**Comment by LIlGG** [comment]
取的是你 Halo 的站点 logo，在 Halo 后台 - 设置 - 站点设置中
