### ISSUE TITLE
画廊不显示图片

### ISSUE THREAD

**Issue by SakuraMuxia** [LIlGG/halo-theme-sakura#560]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

2.17.1

### 建议/问题

本地在部署后画廊不显示，同时发现Demo站的画廊也出现同样问题，

![](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/github-issue02.png)

**经过修改 .photos-content 类的样式后显示。**
![](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/github-issue03.png)

**Comment by LIlGG** [comment]
感谢反馈，确实存在这样的问题。

**Comment by Epoch-guo** [comment]
这 css 文件在哪搁这。 我去改改

**Comment by SakuraMuxia** [comment]
/项目文件夹/.halo2/themes/theme-sakura/src/css/theme/photos/style-masonry.css
![](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/css.png)

**Comment by SakuraMuxia** [comment]
> 这 css 文件在哪搁这。 我去改改

/项目文件夹/.halo2/themes/theme-sakura/src/css/theme/photos/style-masonry.css
![](https://kano-1303231448.cos.ap-nanjing.myqcloud.com/hanser/css.png)

**Comment by Epoch-guo** [comment]
改了。貌似没啥用。我看渲染的还是之前的

**Comment by Epoch-guo** [comment]
感谢。已经解决
