### ISSUE TITLE
自定义首屏社交信息上方的文字

### ISSUE THREAD

**Issue by ShiinaKin** [LIlGG/halo-theme-sakura#562]
### 目前使用的 Sakura 版本？

最新构建

### 目前使用的 halo 版本？

2.17

### 建议/问题

![image](https://github.com/user-attachments/assets/4f937706-1f96-4871-9f6b-5144b4f97ae5)

rt，现在默认读取站点副标题

**Comment by ShiinaKin** [comment]
目前想法是在主题设置增加新配置项，默认为空
有更好的做法吗

**Comment by LIlGG** [comment]
close #566

**Comment by Yaklo** [comment]
存在BUG，当**没有添加**任何一种社交网络时不会显示个人介绍，必须添加任何一种社交网络时关闭
显示社交信息才会仅显示个人介绍

**Comment by ShiinaKin** [comment]
@Yaklo 
我认为是这里没有考虑到这种情况
https://github.com/ShiinaKin/halo-theme-sakura/blob/dc9f68ffccb8080405cc6e15f005285bbb1c20b6/templates/module/home/img_box.html#L40

你可以提交一个pr修复此问题，这应该是很简单的😃
