### ISSUE TITLE
搜索结果没有翻页

### ISSUE THREAD

**Issue by Maxwellsonleison** [LIlGG/halo-theme-sakura#563]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

 2.18.0

### 建议/问题

使用搜索功能展示结果时只展示了10条，且后面没有翻页按钮
实际切换回官方earth主题，使用同样的关键词搜索可以完整显示20条结果。
![8abe4dea062a0d48aec5a09200a48f0](https://github.com/user-attachments/assets/be6c6b54-2149-4ddb-ad09-0a1e6bc087fc)

**Comment by LIlGG** [comment]
搜索目前是没有分页的，他会把所有已搜索到的内容展示出来，因此不需要分页。
