### ISSUE TITLE
怎么给图片添加超链接啊

### ISSUE THREAD

**Issue by Terryisthebest** [LIlGG/halo-theme-sakura#572]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

2.18.0

### 建议/问题

 目前只有文字可以添加超链接。但是我想给图片也加入这样的功能，就是点击图片自动跳转到指定页面。但是如果直接把链接改掉的话图片就没有了……

**Comment by LIlGG** [comment]
该问题与主题无关。在图片上修改图片跳转链接即可。

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/b5cb8c57-c5bd-45c2-a8dc-8e5ce81039f5">

**Comment by Terryisthebest** [comment]
<img width="393" alt="iShot_2024-08-29_15 23 36" src="https://github.com/user-attachments/assets/b9d57986-cecb-457a-88ba-eff34e5641be">
我测试了一下，只有把元素里这一小段删掉才能正常跳转

**Comment by LIlGG** [comment]
> 我测试了一下，只有把元素里这一小段删掉才能正常跳转

emm，gallery 确实可能会导致图片跳转出现问题。我会再验证一下。

**Comment by Terryisthebest** [comment]
好的👌感谢

**Comment by Terryisthebest** [comment]
哦对还有就是点击文章内的视频的时候，会自动打开视频播放窗口（好像是叫灯箱吧？），但是网页端和灯箱端会同时播放视频，这时又必须得手动关掉一个。不知道是不是也跟这个 gallery 有关系。
![截屏2024-08-30 下午2 35 25](https://github.com/user-attachments/ass
![截屏2024-08-30 下午2 35 31](https://github.com/user-attachments/assets/28b98fc6-9db8-430d-80c7-467f424a4b7d)
ets/7fc3df9f-f3dd-4809-9e79-a9cd45ee469a)
