### ISSUE TITLE
关于移动端侧边栏的展开问题

### ISSUE THREAD

**Issue by mobaisilent** [LIlGG/halo-theme-sakura#576]
### 目前使用的 Sakura 版本？

2.3.0

### 目前使用的 halo 版本？

2.17.0

### 建议/问题

<img width="492" alt="image" src="https://github.com/user-attachments/assets/18f81e37-fa70-4f7a-a3f2-50a23c48f0a0">

这是我自己的博客，在移动端端侧边栏可以实现自动展开，可见清单下的标签和分类是二级菜单，友人下的友链池和提交友链是二级菜单，在没有任何点击的情况下实现了自动展开。
<img width="612" alt="image" src="https://github.com/user-attachments/assets/4e9744a1-2722-4054-94d0-b599c1d68239">

但是作者的侧边栏的二级菜单显然是我把鼠标放上面去才能自动展开，然后在移动设备上这个是不好实现的，点击也无法正常展开，造成了二级菜单展开困难。
<img width="403" alt="image" src="https://github.com/user-attachments/assets/8fe450cb-2e1b-4769-b19b-e27340a04d44">

这是我一个友人的博客，其展开逻辑和作者大大的保持一致，那么如何才能达到我自己博客的效果：自动展开，（我自己是不太记得如何实现的了emm），以及自动展开是否为侧边栏更好的解决方案？ 更适合移动端设备的使用和查看。

**Comment by LIlGG** [comment]
正常逻辑移动端应该是需要自动展开的，现在的点击展开实际上是一个 BUG。

**Comment by mobaisilent** [comment]
那么解决方式是什么呀？重装halo及其作者大大的Sakura主题应该可以解决吧？

**Comment by mobaisilent** [comment]
> 正常的逻辑移动端应该是需要自动展开的，现在的点击展开实际上是一个BUG。

那么解决方式是什么呀？重装halo及其作者大大的Sakura主题应该可以解决吧？
