### ISSUE TITLE
halo2.19，对后台编辑器的优化冲突

### ISSUE THREAD

**Issue by 3214693547** [LIlGG/halo-theme-sakura#577]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

2.19.0

### 建议/问题

halo2.19，对后台编译器的优化导致前端代码显示和  highlight.js插件代码高亮冲突，从而显示异常。
![Uploading 0.png…]()

**Comment by LIlGG** [comment]
在 `highlight.js` 配置中，关闭主题端渲染即可。
