### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by Terryisthebest** [LIlGG/halo-theme-sakura#578]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

2.19.0

### 建议/问题

 总结我使用下来的一部分优化建议，只是个人想法，可以选择性采纳
因为建议比较杂而且我不确定该优化属于主题端还是默认端，所以我干脆列在一起吧；
如果觉得哪项建议有用的话，到时再单独提一个 issue 也行

1. 电脑端主题有搜索文章功能，但手机端我没看到搜索选项，是否能够选择添加该功能

2. 在Console界面“文章”右下角能显示每页文章条数，默认 20 条/页。点击后可暂时改成 50 条每页，但是点击其它页面再回到这个页面后又恢复成 20 条每页了。这对文章编辑不是很方便
<img width="1278" alt="iShot_2024-09-13_21 00 09" src="https://github.com/user-attachments/assets/f16d46e5-6886-49af-846d-ba4ddaa496c5">

3. 同样是Console“文章”界面，顶上的排序可以从“默认”改成“较近发布”；但是点击“仪表盘”再点击“文章”之后又恢复成默认排序了，这点也很麻烦

4. 文章中插入音频文件时，会显示一个音频框来播放音频，但是只能实现基本的播放和暂停功能。可否将这个功能优化一下，比如加个倍速功能什么的
<img width="850" alt="iShot_2024-09-13_21 08 19" src="https://github.com/user-attachments/assets/e740adb4-80f8-4150-a521-0ed1b9cdd058">

5. 在文章设置里，希望可以让管理员能够自定义修改文章贡献者，最好还能够注明每位贡献者在文章发表中扮演的角色等

6. 插件一个一个点击更新有点麻烦，有没有“一键更新”之类的功能

7. 这个用户权限设置的功能感觉不是很好用，有挺多权限相冲突或矛盾的地方。比如在自己主页“我的文章”里没有“设置”按键，只能进入文章后再点击设置，并且此时一些插件例如“隐藏内容设置”也无法正常使用，并且无法在这里删除自己的文章，而只能从 console 界面编辑。但是进入 console 界面的话，又无法只管理自己的文章，例如不打开“文章管理”权限就无法正常管理自己的文章，而打开该权限后却能够轻易删除别人的文章，所以单在文章权限设置上我就没法让用户享有对自己文章的完全设置权同时无法管理别人的文章。另外其它的可选权限我感觉也是莫名其妙，光看权限名称也不知道该权限到底有什么用。所以希望可以在这一点上优化一下。

平常学业比较忙，但有空还是会在 github 上反馈一些建议的。我技术不专业，可能提一些愚蠢的问题，请谅解！

**Comment by Terryisthebest** [comment]
诶对我的站点 https://www.terryliu.top:2507 （一个主打学习分享的平台），欢迎随时参观提提建议什么的～嘿嘿

**Comment by LIlGG** [comment]
感谢反馈，不过除了第一个问题之外，其他的问题与主题关联不大，建议拆分问题之后前往 Halo 提问。

> 电脑端主题有搜索文章功能，但手机端我没看到搜索选项，是否能够选择添加该功能

此问题属于 2.0 之后缺失的功能，会进行添加。
