### ISSUE TITLE
建议：可以添加使隐藏瞬间在主题上登录可见吗

### ISSUE THREAD

**Issue by holwell** [LIlGG/halo-theme-sakura#582]
### 目前使用的 Sakura 版本？

最新版本

### 目前使用的 halo 版本？

2.19

### 建议/问题

想让隐藏的瞬间在登录的情况下，在主题页面也能显示出来，甚至可以在登录情况下显示一个发布瞬间的入口。

**Comment by LIlGG** [comment]
让隐藏的瞬间在登录状态下显示，需要瞬间插件的支持，可以在瞬间插件中提一个 issue。

登录情况下增加入口可以考虑添加。

**Comment by holwell** [comment]
谢谢😭提了很多天了，只能等了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月16日(周三) 下午3:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LIlGG/halo-theme-sakura] 建议：可以添加使隐藏瞬间在主题上登录可见吗 (Issue #582)




 
让隐藏的瞬间在登录状态下显示，需要瞬间插件的支持，可以在瞬间插件中提一个 issue。
 
登录情况下增加入口可以考虑添加。

**Comment by LIlGG** [comment]
> 谢谢😭提了很多天了，只能等了

大概率只会提供一个跳转至后台的按钮。
想在主题端完全实现一个瞬间发布功能的代价比较大且只能使用接口的方式，个人不是非常建议。

**Comment by holwell** [comment]
> > 谢谢😭提了很多天了，只能等了
> 
> 大概率只会提供一个跳转至后台的按钮。 想在主题端完全实现一个瞬间发布功能的代价比较大且只能使用接口的方式，个人不是非常建议。

大佬这个项目写的真好啊，看了这么多主题仓库，你这个最规范优雅了
