### ISSUE TITLE
相册页面无法显示任何图片

### ISSUE THREAD

**Issue by 0x1233333** [LIlGG/halo-theme-sakura#583]
### 目前使用的 Sakura 版本？

2.40

### 目前使用的 halo 版本？

2.20.8

### 建议/问题

相册页面无法显示图片，测试过很多册，包括重装系统。换其他主题没有遇到过这种事情
<img width="855" alt="image" src="https://github.com/user-attachments/assets/09626b38-def4-4951-9cd6-4fd8b9194349">
不过，我发现我浏览https://lixingyong.com/photos时也无法查看，手机和pc以及切换网络都有尝试，也不能查看图片
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/d9b17cb4-93dc-4387-b743-3292fcbe1ed8">

**Comment by LIlGG** [comment]
可能与 #567 的问题一致，不过修改之后还未发版。

**Comment by firefox-half** [comment]
> 可能与 #567 的问题一致，不过修改之后还未发版。

大佬快快发版，球球了

**Comment by LIlGG** [comment]
已经发布 [2.4.1](https://github.com/LIlGG/halo-theme-sakura/releases/tag/v2.4.1) 版本
