### ISSUE TITLE
导航菜单栏icon问题

### ISSUE THREAD

**Issue by xiongzhuang1234** [LIlGG/halo-theme-sakura#584]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

2.20.8

### 建议/问题

我这边设置sakura博客的时候， 发现引用阿里巴巴矢量库里面的图标的时候， 总是失败
我这里参考的引用图标的方法链接 : https://ono.ee/?p=1693459637574

halo的默认提示是 支持所有 iconify 图标。例如 https://icones.netlify.app/。
虽然默认的iconify图标这边测试可以用， 但是感觉图标少了， 所以询问你这边有没有好的解决办法。 可以引用到阿里巴巴矢量库的图标

**Comment by LIlGG** [comment]
可以去新版本 iconify 图标库查看 https://icon-sets.iconify.design/

无法使用阿里巴巴矢量库图标，矢量库图标似乎是需要嵌入额外的 js\css 的，且与现有的动态渲染方式不符。

**Comment by xiongzhuang1234** [comment]
好的， 谢谢，我试试这个图标库
