### ISSUE TITLE
BUG 评论没有正常加载，无法评论

### ISSUE THREAD

**Issue by KingPrimes** [LIlGG/halo-theme-sakura#586]
### 目前使用的 Sakura 版本？

2.4.0

### 目前使用的 halo 版本？

2.20.9

### 建议/问题

安装了**评论组件**版本为：**2.5.1**
在文章页、瞬间页，没有评论输入框了

**Comment by KingPrimes** [comment]
> 在我的线上环境中，没有能够复现这个问题。
> 
> 是否可以提供一下网站地址。

https://kingprimes.top

**Comment by KingPrimes** [comment]
> > 在我的线上环境中，没有能够复现这个问题。
> > 是否可以提供一下网站地址。
> 
> https://kingprimes.top Sakura 更新到2.4.1版本仍然存在此问题 安装了评论插件，版本为2.5.1

 因为sakura主题存在问题我暂时将主题更改为了Dream主题

**Comment by LIlGG** [comment]
本地环境中也未复现这个问题。

<img width="1881" alt="image" src="https://github.com/user-attachments/assets/7a520234-9eba-4fef-9744-d74676d297f7">

另外，瞬间默认是关闭了评论与点赞的，需要前往主题设置中开启。

<img width="886" alt="image" src="https://github.com/user-attachments/assets/60f5049a-1d63-484c-a077-425774f5b97e">

**Comment by KingPrimes** [comment]
![image](https://github.com/user-attachments/assets/d3e81b2a-7d60-4717-b123-dff527b38ceb)
抱歉，是我的设置问题。
在其它设置中开启了备案模式，关闭之后就出现了评论
