### ISSUE TITLE
回到顶部部件无法正常显示

### ISSUE THREAD

**Issue by kayuml** [LIlGG/halo-theme-sakura#589]
### 目前使用的 Sakura 版本？

 2.4.1

### 目前使用的 halo 版本？

 2.20.10

### 建议/问题

![image](https://github.com/user-attachments/assets/44c07ac7-0551-48cc-8126-4d3ef673f64f)
一旦关闭主题切换，返回顶部部件就会无法显示

**Comment by LIlGG** [comment]
确实存在这个问题，将在下一个版本中修复。
