### ISSUE TITLE
博客页面cpu占用大

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#59]
# 如图:![image](http://blog.chenjaly.cn/upload/2020/08/image-7eeb633658f444e58b12e351aec548fd.png)
## 在配置低一点的机器上略微卡顿,希望后期可以优化一下.

**Comment by LIlGG** [comment]
吃内存是chromium内核的通病

**Comment by LIlGG** [comment]
不过对比一下确实本主题的CPU占用会大点。 因为主题用了很多图片数据，会产生一些缓存。后续会考虑优化这方面，比如缩减图片缓存，减少请求量等等
