### ISSUE TITLE
文章内部超链接点击后没有反应

### ISSUE THREAD

**Issue by PPOmega12138** [LIlGG/halo-theme-sakura#592]
### 目前使用的 Sakura 版本？

2.4.1

### 目前使用的 halo 版本？

2.20.10

### 问题描述
1、文章内部的超链接以及侧边栏的文章结构目录在点击后没有反应
2、页面内其他元素（包括顶部菜单、文章底部的下一篇文章等）可以正常点击跳转
3、可以右键从新标签页打开，即超链接和目录的目标路径没有问题

### 版本相关
在回退到2.4.0版本后问题消失

相关issue #590

**Comment by LIlGG** [comment]
经过测试没有能够复现。是否使用的默认编辑器？

方便的话可以提供一下网站地址。

**Comment by PPOmega12138** [comment]
使用的是默认编辑器
我的网站是https://blog.bakano1.top

事实上我在访问您的网站时也有这个问题。
未复现成功可能是浏览器缓存导致的，我在尝试通过更换主题版本复现问题时每次都需要清除浏览器缓存才能生效
使用的浏览器有chrome、edge和safari

**Comment by asd13852710118** [comment]
我感觉问题是一样的。个人资料，退出登录按钮点击无效，但是可以右键--在新窗口打开链接

**Comment by alittlehuaji** [comment]
我也有类似的问题。具体包括：

1. 未登录状态下，右上角点击登录没有反应（首页右上角 -> 登录）

   已登录状态下也同样，无法直接点击进入个人资料界面。退出登录按钮也同样

2. 社交网络连接直接点击也无法跳转（主页中间）

3. 进入任意文章进行评论，实测提交评论按钮也是用不了的（文章底部右下方 -> 提交评论）

我也使用多个浏览器尝试复现过，部分复现成功（具体包括电脑端 Edge 以及电脑端 Chrome）。手机浏览器（Edge）似乎不存在上述第2个问题，另外的两个问题暂时还没有尝试去复现。

另外通过 右键 -> 在新标签页中打开链接 可以正常打开超链接
