### ISSUE TITLE
主题内所有方式的超链接失效

### ISSUE THREAD

**Issue by MariaSakura** [LIlGG/halo-theme-sakura#594]
### 目前使用的 Sakura 版本？

2.4.1

### 目前使用的 halo 版本？

2.4.1

### 建议/问题

无论是使用halo自带的文字超链接功能，还是通过HTML模块使用<a href="" target="_blank"></a>语句
都无法正常跳转至链接，现象为点击后没有任何反应
使用halo的默认主题则没有此问题，故判断为sakura主题问题

**Comment by LIlGG** [comment]
感谢反馈，我今天会抽空处理一下这个问题。
