### ISSUE TITLE
新版本超链接仍然无效

### ISSUE THREAD

**Issue by MariaSakura** [LIlGG/halo-theme-sakura#597]
### 目前使用的 Sakura 版本？

 2.4.2

### 目前使用的 halo 版本？

 2.4.2

### 建议/问题

更新到最新版本，超链接问题依旧存在。
![image](https://github.com/user-attachments/assets/699c68bb-8301-4cbd-b787-853c6d423887)

**Comment by LIlGG** [comment]
应该是缓存导致的，清理一下缓存。

**Comment by MariaSakura** [comment]
> 应该是缓存导致的，清理一下缓存。

清除缓存后依旧无效

**Comment by alittlehuaji** [comment]
> > 应该是缓存导致的，清理一下缓存。
> 
> 清除缓存后依旧无效

我刚才也遇到了同样的问题，建议试着清除一下 nginx反向代理缓存、浏览器缓存，如果有cdn或有安装halo缓存插件的话，那么也可以试着清除一下
具体可以参照此issue #598

**Comment by LIlGG** [comment]
后续可以考虑在每个版本的静态资源中，添加 version 用于当前版本下首次更新时确保静态资源不被缓存。

**Comment by MariaSakura** [comment]
已清理本地浏览器缓存，服务器也已清理nginx缓存，没有使用cdn，也没有安装halo缓存插件，重新安装主题问题仍然存在

**Comment by LIlGG** [comment]
> 已清理本地浏览器缓存，服务器也已清理nginx缓存，没有使用cdn，也没有安装halo缓存插件，重新安装主题问题仍然存在

提供一下地址，我去看看。

**Comment by MariaSakura** [comment]
> > 已清理本地浏览器缓存，服务器也已清理nginx缓存，没有使用cdn，也没有安装halo缓存插件，重新安装主题问题仍然存在
> 
> 提供一下地址，我去看看。

https://blog.lorikein.cn/

**Comment by LIlGG** [comment]
> [blog.lorikein.cn](https://blog.lorikein.cn/)

应该也是哪里存在了缓存。

<img width="834" alt="image" src="https://github.com/user-attachments/assets/1a695543-6b6c-461e-b7cf-d2536d364276">

可以看到这个文件的最后修改时间是 11 月 30 号，且缓存策略表示 
`cache-control: max-age=31536000` 即缓存了 365 天。

**Comment by MariaSakura** [comment]
> > [blog.lorikein.cn](https://blog.lorikein.cn/)
> 
> 应该也是哪里存在了缓存。
> 
> <img alt="image" width="834" src="https://private-user-images.githubusercontent.com/31335418/394649362-1a695543-6b6c-461e-b7cf-d2536d364276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTc4OTUsIm5iZiI6MTczMzkxNzU5NSwicGF0aCI6Ii8zMTMzNTQxOC8zOTQ2NDkzNjItMWE2OTU1NDMtNmI2Yy00NjFlLWI3Y2YtZDI1MzZkMzY0Mjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDExNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MmY2NjJhMGFhNjczNzBiYWM3NGFiZWI4YjNhYWU1YjZiN2M1OWNmMzk1NWUwODBkM2ZkOTNiN2U3YzMxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mPXkxqydS1zJNC0hBUc7ewJ11z056kOAD871guS8jNk">
> 可以看到这个文件的最后修改时间是 11 月 30 号，且缓存策略表示 `cache-control: max-age=31536000` 即缓存了 365 天。

这个可以通过等待下次更新修复吗，我这里实在找不到是哪的缓存了。o(￣┰￣*)ゞ

**Comment by LIlGG** [comment]
> 这个可以通过等待下次更新修复吗，我这里实在找不到是哪的缓存了。o(￣┰￣*)ゞ

可以，下个版本我会给主题内的静态资源加上当前版本号。

**Comment by MariaSakura** [comment]
> > 这个可以通过等待下次更新修复吗，我这里实在找不到是哪的缓存了。o(￣┰￣*)ゞ
> 
> 可以，下个版本我会给主题内的静态资源加上当前版本号。

好的，感谢。
