### ISSUE TITLE
主题超链接无法正常跳转

### ISSUE THREAD

**Issue by alittlehuaji** [LIlGG/halo-theme-sakura#598]
### 目前使用的 Sakura 版本？

2.4.2

### 目前使用的 halo 版本？

2.20.11

### 网站地址

https://blog.alittlehuaji.top

### 建议/问题

有关于之前出现的超链接无法正常跳转的问题。现在更新到最新版本后，即使清理了浏览器缓存，问题依旧存在

视频仅供问题排查：[视频](https://github.com/user-attachments/assets/47622bdf-8c69-4c9e-bf27-b37026dd1157)

如果需要更多的信息或进行其他问题的排查，请在评论中联系我，我可以提供网站后台进行进一步的排查

**Comment by LIlGG** [comment]
<img width="509" alt="image" src="https://github.com/user-attachments/assets/cd78b9bd-45c6-4627-9395-06307c554067">

这个 js 文件处于缓存状态。是否使用了 CDN 或者 Halo 开启了缓存策略？如果是的话清理一下对应的缓存。

**Comment by alittlehuaji** [comment]
感谢，刚才经过排查发现确实是缓存的问题。上述问题均已恢复正常。这里就先关闭此issue了😊
