### ISSUE TITLE
设置皮肤点击保存报错500

### ISSUE THREAD

**Issue by LJ-panda** [LIlGG/halo-theme-sakura#63]
大佬，我使用的halo版本是1.3.2，使用你这个皮肤，我设置了点击保存就报错500。查看halo日志，报错查询结果不唯一：Caused by: javax.persistence.NonUniqueResultException: query did not return a unique result: 8。不晓得咋个回事

**Comment by LIlGG** [comment]
你这个是halo的问题，由于本主题的配置量比其他主题的多，所以出现这种BUG的次数也多。主要原因是保存的时候点击太快，导致相同的数据保存了两次，已经将BUG反馈给了官方，后续版本就会修复。
目前的解决方案，需要自行到数据库的 themes表里，删除具有相同变量名的数据，然后只保留一条就可以解决。

**Comment by LJ-panda** [comment]
好的，谢谢老哥
