### ISSUE TITLE
文本太长，导致移动端显示时用户信息被折叠

### ISSUE THREAD

**Issue by LIlGG** [LIlGG/halo-theme-sakura#64]
RT，标题文本过长时，移动端用户信息会被折叠。

![1.png](https://cdn.jsdelivr.net/gh/RalstonLiu/MdnicePic/2020-9-3/1599095878727-image.png)

**Comment by parasomn1a** [comment]
1. 将标题限定最大长度，多出部分使用 `...` 处理
2. 当标题过长时，增加 `pattern-attachment-img` 高度

您认为哪一种处理方式更加合理或是有更好的解决方案呢？

**Comment by LIlGG** [comment]
> 1. 将标题限定最大长度，多出部分使用 `...` 处理
> 2. 当标题过长时，增加 `pattern-attachment-img` 高度
> 
> 您认为哪一种处理方式更加合理或是有更好的解决方案呢？

感觉一味地增加高度似乎不是个好选择，至少也得限制一下高度，但那样又会出现上述问题。
所以我觉得使用 `……` 处理似乎更好一些。
