### ISSUE TITLE
markdown的分割线显示出错

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#66]
无论是使用`***`还是使用`---`的markdown分割线的语法页面显示如下图:
![image](http://blog.chenjaly.cn/upload/2020/09/image-a18f16bedee0413593f23bbd30f05a59.png)

**Comment by LIlGG** [comment]
。刚刚仔细排查过了。 这个是没有问题的，无论是*** 还是 --- 。markdown的解析都是hr 而主题里的hr分割线 目前就是如此设计的。。
实际上样式之类的东西，都可以通过css来自行控制。以下是分割线的默认css
```html
.entry-content hr {
	margin-top: 40px;
	margin-bottom: 40px;
	display: block;
	border: 0;
	text-align: center;
	background: 0 0
}

.entry-content hr:before {
	content: '...';
	display: inline-block;
	margin-left: .6em;
	color: rgba(0,0,0,.8);
	position: relative;
	top: -30px;
	font-size: 28px;
	letter-spacing: .6em
}
```

**Comment by CodeChenL** [comment]
> 。刚刚仔细排查过了。 这个是没有问题的，无论是*** 还是 --- 。markdown的解析都是hr 而主题里的hr分割线 目前就是如此设计的。。
> 实际上样式之类的东西，都可以通过css来自行控制。以下是分割线的默认css
> 
> ```
> .entry-content hr {
> 	margin-top: 40px;
> 	margin-bottom: 40px;
> 	display: block;
> 	border: 0;
> 	text-align: center;
> 	background: 0 0
> }
> 
> .entry-content hr:before {
> 	content: '...';
> 	display: inline-block;
> 	margin-left: .6em;
> 	color: rgba(0,0,0,.8);
> 	position: relative;
> 	top: -30px;
> 	font-size: 28px;
> 	letter-spacing: .6em
> }
> ```

我还以为是bug呢,既然主题原生是这样的话我就不改,谢谢大佬解答
