### ISSUE TITLE
文章代码块放大之后的问题

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#67]
问题一:文章代码块放大之后,如代码过多,超过屏幕,不能下滑,显示不完全
问题二:如单行代码过长,超过屏幕,没有滑块

**Comment by LIlGG** [comment]
非常感谢提的BUG
对于第一个问题，确实有这个问题，已经计划修复。
第二个问题，单行代码过长，默认在我的设计中就是不出现滑块的，你可以通过鼠标向右拖拽来实现，或者通过键盘左右键来移动。如果有这个需求，实际上可以在后台全局css里面增加如下代码来出现滑块
```html
.code-block-fullscreen code {
	overflow-y: auto !important;
}
```

**Comment by CodeChenL** [comment]
为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)

**Comment by LIlGG** [comment]
> 为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)

是在线更新的吗？是否使用了cdn，如果有cdn，那就清理一下缓存。否则读取的还是上个版本的缓存

**Comment by CodeChenL** [comment]
> > 为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)
> 
> 是在线更新的吗？是否使用了cdn，如果有cdn，那就清理一下缓存。否则读取的还是上个版本的缓存

并没有使用cdn,只使用了内网穿透

**Comment by LIlGG** [comment]
> > > 为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)
> > 
> > 
> > 是在线更新的吗？是否使用了cdn，如果有cdn，那就清理一下缓存。否则读取的还是上个版本的缓存
> 
> 并没有使用cdn,只使用了内网穿透

那就清理本地缓存。 可以把博客地址发一下吗？我这边看一下

**Comment by CodeChenL** [comment]
http://blog.chenjaly.cn/archives/%E5%AD%A6%E4%B9%A0ajas%E6%97%B6%E7%BC%96%E5%86%99%E7%9A%84%E4%BB%A3%E7%A0%81

**Comment by CodeChenL** [comment]
> > > > 为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)
> > > 
> > > 
> > > 是在线更新的吗？是否使用了cdn，如果有cdn，那就清理一下缓存。否则读取的还是上个版本的缓存
> > 
> > 
> > 并没有使用cdn,只使用了内网穿透
> 
> 那就清理本地缓存。 可以把博客地址发一下吗？我这边看一下

http://blog.chenjaly.cn/archives/%E5%AD%A6%E4%B9%A0ajas%E6%97%B6%E7%BC%96%E5%86%99%E7%9A%84%E4%BB%A3%E7%A0%81

**Comment by LIlGG** [comment]
> > > > > 为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)
> > > > 
> > > > 
> > > > 是在线更新的吗？是否使用了cdn，如果有cdn，那就清理一下缓存。否则读取的还是上个版本的缓存
> > > 
> > > 
> > > 并没有使用cdn,只使用了内网穿透
> > 
> > 
> > 那就清理本地缓存。 可以把博客地址发一下吗？我这边看一下
> 
> http://blog.chenjaly.cn/archives/%E5%AD%A6%E4%B9%A0ajas%E6%97%B6%E7%BC%96%E5%86%99%E7%9A%84%E4%BB%A3%E7%A0%81

我这边看着是可以的。但和我想的有所出入，我重新提交一下，你等下再拉取一下

**Comment by CodeChenL** [comment]
> > > > > > 为什么我安装了最新的主题还是,放大代码还是不能下滑,浏览器是最新的edge(chrome内核版本)
> > > > > 
> > > > > 
> > > > > 是在线更新的吗？是否使用了cdn，如果有cdn，那就清理一下缓存。否则读取的还是上个版本的缓存
> > > > 
> > > > 
> > > > 并没有使用cdn,只使用了内网穿透
> > > 
> > > 
> > > 那就清理本地缓存。 可以把博客地址发一下吗？我这边看一下
> > 
> > 
> > http://blog.chenjaly.cn/archives/%E5%AD%A6%E4%B9%A0ajas%E6%97%B6%E7%BC%96%E5%86%99%E7%9A%84%E4%BB%A3%E7%A0%81
> 
> 我这边看着是可以的。但和我想的有所出入，我重新提交一下，你等下再拉取一下

好的

**Comment by LIlGG** [comment]
@CodeChenL 已经重新提交新的版本 你再拉取一下，记得清理本地缓存

**Comment by CodeChenL** [comment]
> @CodeChenL 已经重新提交新的版本 你再拉取一下，记得清理本地缓存

清理了本地缓存,问题已解决👌
