### ISSUE TITLE
在主页展开显示指定目录下文章悬浮窗设置的可能性

### ISSUE THREAD

**Issue by duanmofan** [LIlGG/halo-theme-sakura#69]
我在使用您的sakura主题，我想在主页上创建一个可以跟踪界面移动带滚轮的悬浮窗，来显示指定目录下的所有文章，并可以点击后接入该文章链接。
但我在主题设置中没有找到有类似的设置，也没有在halo博客设置中找到可以自定义设计的接口。
请问我可以如何实现这个功能？

**Comment by LIlGG** [comment]
如上的功能，可能需要你自定义编写代码来实现，这种功能并不在预设的范围呢。根据你的描述，我的大致分析如下：
1. 一个跟随界面的浮动框，类似于 `position: fixed;`
2. 目标悬浮框可以上下滚动，类似于 `overflow: scroll`
3. 显示指定目录下的所有文章，对于指定目录，我这边其实不太理解什么叫目录，所以我暂且认定为分类或者标签吧。所以就是获取某个分类下的所有文章。那么你就可以采用类似下面的方式，来尝试获取。
```
<@categoryTag method="list">
    <a href="${category.fullPath!}" title="${category.name!}: ${category.postCount!}">
         <span class="chip center-align waves-effect waves-light chip-default" data-tagname="${category.name!}">${category.name!}
             <span class="tag-length">${category.postCount!}</span>
          </span>
    </a>
</@categoryTag>
```

当然了，如上只是我猜测，看你具体的做法
