### ISSUE TITLE
Mac本下，聚焦图的样式错乱

### ISSUE THREAD

**Issue by LIlGG** [LIlGG/halo-theme-sakura#7]
RT，但由于我没有Mac本，BUG修复时间未知。。。（流下了贫穷的泪水）

**Comment by limin04551** [comment]
第三个图换行了 样式.from_left_and_right width:257px 改为256px即可。代码显示上方黑框，经常误点击出现弹框，很难受，建议改成简书网站的代码显示形式，简洁明了。^_^

**Comment by LIlGG** [comment]
> 第三个图换行了 样式.from_left_and_right width:257px 改为256px即可。代码显示上方黑框，经常误点击出现弹框，很难受，建议改成简书网站的代码显示形式，简洁明了。^_^

非常感谢，马上去调一下！
代码块默认是支持单击放大功能的。实际上这个小功能我还是比较喜欢的。。
如果觉得太麻烦的话我就设置一个功能来决定是否开启代码块放大功能吧。 或者我将单击改成双击
