### ISSUE TITLE
第一屏上的部分BUG

### ISSUE THREAD

**Issue by LIlGG** [LIlGG/halo-theme-sakura#73]
根据反馈，第一屏有如下问题：

- [x] 背景视频无法显示全【已知的统一问题，设置video高度为100vh即可解决】
- [x] 社交网络上增加上telegram与email
- [x] 评论模块填写特殊的域名提示域名不正确。【例如 blog.lixian.download】
- [x] bilibili 视频无法加载【接口问题，计划修复】
- [ ] 第一屏在ipad上时，整体布局会左偏，且首页图会有空白，如下图所示

![1.png](https://i.loli.net/2020/10/06/WNXfpnx8PKOvq6C.png)

**Comment by wuyan-ling** [comment]
> * ad上时，整体布局会左偏，且首页图会有空

有一个问题想请教一下，就是第一屏社交信息上面的那句话， You got to put the past behind you before you can move on. 。为什么没有看到设置的地方，也没有显示，故障文字倒是有显示。
![image](https://user-images.githubusercontent.com/33196182/100400419-7702de80-3091-11eb-8741-8691362fe4ae.png)

**Comment by LIlGG** [comment]
> > * ad上时，整体布局会左偏，且首页图会有空
> 
> 有一个问题想请教一下，就是第一屏社交信息上面的那句话， You got to put the past behind you before you can move on. 。为什么没有看到设置的地方，也没有显示，故障文字倒是有显示。
> ![image](https://user-images.githubusercontent.com/33196182/100400419-7702de80-3091-11eb-8741-8691362fe4ae.png)

这个是你的个人说明。修改 后台管理系统 -> 用户 -> 个人资料 -> 个人说明  即可

**Comment by LIlGG** [comment]
经过验证，blog.lixian.download 这种是没有问题的

**Comment by RealKiro** [comment]
telegram填的id还是用户名？两者试了都跳转不成功...(大雾...

加个提示扒
