### ISSUE TITLE
首页文章随机图片

### ISSUE THREAD

**Issue by codesensi** [LIlGG/halo-theme-sakura#76]
大佬，主题游首页文章随机图吗？我没找到，没有的话，考虑搞一下么，毕竟每篇文章都搞一个图片有点烦，嘻嘻

**Comment by LIlGG** [comment]
目前没有随机图，分析过halo的随机图实现，但不是很方便。因此后续打算基于图床，弄个随机图API。

**Comment by codesensi** [comment]
> 目前没有随机图，分析过halo的随机图实现，但不是很方便。因此后续打算基于图床，弄个随机图API。

搜嘎，那我就静待了，顺便再说一下，我个人感觉把主题里的一些英文单词换成中文会更舒服一点，比如discovery，comments这些。

**Comment by Creator2K** [comment]
在文章封面图地址输入随机图片API就OK了，不过加载会变慢就是了
