### ISSUE TITLE
文章中上一文与下一文背景展示

### ISSUE THREAD

**Issue by xiaofsu** [LIlGG/halo-theme-sakura#77]
![image](https://user-images.githubusercontent.com/46067472/96083949-c8477c00-0ef0-11eb-9c02-d9478871d00e.png)

如果这篇文章没有设置封面图，则会出现如上的问题

如果要增加功能：#76  可以顺手处理一下这个问题。

**Comment by LIlGG** [comment]
这个倒不是BUG，默认就是这样的，不过效果确实不好。。

**Comment by xiaofsu** [comment]
😁😁😁  期待解决方案

**Comment by LIlGG** [comment]
> 😁😁😁 期待解决方案

所以就只能把随机图方案提前了。但资源是最大的问题，符合条件的资源。我会调研一下，看看是自己写接口，还是使用别人的接口
