### ISSUE TITLE
天啊，看板娘不见了

### ISSUE THREAD

**Issue by yuanxiuyao** [LIlGG/halo-theme-sakura#78]
首页看板娘菜单都有，说的文字也有，就是人没了
附上网站地址：https://www.xiaoyaoba.top/

**Comment by LIlGG** [comment]
是有的哦，但你的文本高度似乎设置的有点低了

![image](https://user-images.githubusercontent.com/31335418/96664625-c9abf500-1385-11eb-804f-0b51c16912db.png)

**Comment by yuanxiuyao** [comment]
是我公司网络配置的问题，我让我朋友打开是可以看见，我在公司就看不见
