### ISSUE TITLE
评论对旧版本的浏览器不太友好

### ISSUE THREAD

**Issue by gybaoyu** [LIlGG/halo-theme-sakura#81]
当我使用win10自带的edge访问时(不是最新版的那个新图标的edge)
评论模块无法正常使用,还有没有办法再拉宽一下对浏览器的限制呢....
谢谢![](https://pan.abalone.life/api/v3/share/preview/gKsG)

**Comment by gybaoyu** [comment]
https://pan.abalone.life/api/v3/share/preview/gKsG

**Comment by LIlGG** [comment]
emm 评论应该支持所有Vue支持的浏览器吧。 也许是其他的问题，edge应该是没有问题的吧。 不是最新版的那个新图标的edge 是啥？？？
如果可以的话，可否提供一下浏览器截图以及控制台信息？？

**Comment by gybaoyu** [comment]
我现在没办法找到那个旧版浏览器,到时候给你控制台截图
![这个就是新版edge的截图了](https://abalone-1301105015.cos.ap-shanghai.myqcloud.com/abalone-blog/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202020-11-07%20090656_1604711583305.jpg)

**Comment by gybaoyu** [comment]
上面那张图时我说的"新版edge"
这张图时我说的"旧版edge"![屏幕截图 2020-11-07 091814](https://abalone-1301105015.cos.ap-shanghai.myqcloud.com/abalone-blog/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202020-11-07%20091814_1604711917935.jpg)

**Comment by LIlGG** [comment]
看到了，但旧版的 edge 是没有问题的。 我这边亲测过的。。你那边具体是神马问题？？就评论不能使用吗

**Comment by gybaoyu** [comment]
我现在没办法用我那台旧的机器,我看看能不能把控制台的截图给你,那边就是单纯的评论不能用,没有显示出评论的表单

**Comment by gybaoyu** [comment]
今天晚点我看看能不能把控制台截图给你,谢谢了!

**Comment by LIlGG** [comment]
行 也许不是评论的问题，可能是其他地方报错导致的评论出现错误

**Comment by LIlGG** [comment]
过去太久了，我先关闭 issue 了，有问题可以再次打开！
