### ISSUE TITLE
二级菜单宽度太小

### ISSUE THREAD

**Issue by wpengsen** [LIlGG/halo-theme-sakura#82]
我设置四字一级菜单，再添加四字二级菜单，二级菜单拉取出来一个二级菜单会显示两行，是否修改下.lower li ul下的宽度

**Comment by LIlGG** [comment]
> 我设置四字一级菜单，再添加四字二级菜单，二级菜单拉取出来一个二级菜单会显示两行，是否修改下.lower li ul下的宽度

这个默认可以自行设置 CSS 来处理。关于样式的话没办法，众口难调，调了可以四个的话也许还会有五个的情况。
其实我蛮想改成自适应的，但自适应会带来很多问题。后续再处理吧

**Comment by wpengsen** [comment]
ok
