### ISSUE TITLE
浏览器控制台有报错

### ISSUE THREAD

**Issue by CodeChenL** [LIlGG/halo-theme-sakura#83]
# <a href="http://blog.chenjaly.cn/">地址</a>
# ![image](https://user-images.githubusercontent.com/43897062/98822697-1908b100-246c-11eb-8a44-d2f63d23da5a.png)
# 虽然貌似不影响使用,但是强迫症啊🤣

**Comment by LIlGG** [comment]
讲道理，你这个 JS 和这个 config_json 属性，我都没见过，没法帮你改。

**Comment by CodeChenL** [comment]
> 讲道理，你这个 JS 和这个 config_json 属性，我都没见过，没法帮你改。

原来是我的浏览器插件,不好意思打扰大佬了

**Comment by CodeChenL** [comment]
> 讲道理，你这个 JS 和这个 config_json 属性，我都没见过，没法帮你改。

但是确实有一个cdn资源没有
![image](https://user-images.githubusercontent.com/43897062/98829841-a223e600-2474-11eb-9652-85b3ca096087.png)

**Comment by LIlGG** [comment]
> > 讲道理，你这个 JS 和这个 config_json 属性，我都没见过，没法帮你改。
> 
> 但是确实有一个cdn资源没有
> ![image](https://user-images.githubusercontent.com/43897062/98829841-a223e600-2474-11eb-9652-85b3ca096087.png)

这个我已经改了，已经提交但还没有发布。下个版本就会去掉~
