### ISSUE TITLE
文章分类页面展示的分类是全部的分类，二级分类也和一级分类目录一样展示出来了

### ISSUE THREAD

**Issue by wuyan-ling** [LIlGG/halo-theme-sakura#84]
文章分类展示的应该是一级目录，而不是二级目录和一级目录一样一起展示出来。麻烦博主有空解答一下，感谢！

![image](https://user-images.githubusercontent.com/33196182/100405180-0a421100-309e-11eb-9401-6ffa85eedafd.png)
![image](https://user-images.githubusercontent.com/33196182/100405426-89cfe000-309e-11eb-9f50-34a186130dc1.png)

**Comment by wuyan-ling** [comment]
> 文章分类展示的应该是一级目录，而不是二级目录和一级目录一样一起展示出来。麻烦博主有空解答一下，感谢！
> 
> ![image](https://user-images.githubusercontent.com/33196182/100405180-0a421100-309e-11eb-9401-6ffa85eedafd.png)

![image](https://user-images.githubusercontent.com/33196182/100405381-6f960200-309e-11eb-81a0-6e00332523b6.png)
wen'zhang文章分类以及雷达图展示的不对。

**Comment by LIlGG** [comment]
这是 halo 的定义。详见 [目录下的子目录，没有归并到目录下](https://github.com/halo-dev/halo/issues/1136)。

**Comment by wuyan-ling** [comment]
> 这是 halo 的定义。详见 [目录下的子目录，没有归并到目录下](https://github.com/halo-dev/halo/issues/1136)。
好的，感谢回复。速度很快啊。

**Comment by LIlGG** [comment]
> > 这是 halo 的定义。详见 [目录下的子目录，没有归并到目录下](https://github.com/halo-dev/halo/issues/1136)。
> > 好的，感谢回复。速度很快啊。

主要是有邮件提醒。。所以看到之后就能回复了
