### ISSUE TITLE
关于主题的几个功能的feature.

### ISSUE THREAD

**Issue by hongcyu** [LIlGG/halo-theme-sakura#85]
目前，正在修改主题，遇到几个问题。

1.文章字体大小，间距，行距，字体样式希望可以在主题设置里可以修改。（个人感觉现在字体有点小看不清，不知道是不是我自己的问题，正在找位置修改，如果作者看到可以直接告诉我字体修改的位置，QAQ）
2.点击侧边目录导航会在正文显示黑色框，个人感觉有点突兀。
![image](https://user-images.githubusercontent.com/41502466/100562936-0e696b00-32f8-11eb-96b2-ef539d12d429.png)
3.返回顶部样式是否可以自定义。
4.是否有办法让某些页面不显示右侧目录导航。
5.本来想采取不同图标大小进行首页社交按钮的设置，可是发现修改源图片却无法改ico大小，后来我只能使用svg的方式添加图标，可能是我没找到修改位置。
6.同时目前默认的希望改成实底图标，不然个人感觉看不清==
![image](https://user-images.githubusercontent.com/41502466/100563064-7324c580-32f8-11eb-838b-e550509729b5.png)

**Comment by LIlGG** [comment]
非常感谢提的几点建议。下面是就这些建议做出的回答：
1.  字体大小，间距，样式等。可以在 ```主题设置 -> 自定义 CSS``` 样式中，自定义 CSS 来实现，因为是样式类的问题，每个人的定制化需求可能不一样，因此放在配置里面并不适合。而**直接改源码可能会导致后续无法更新本主题**，因此建议在配置中修改 CSS 来实现。
对于字体大小来说，可以这样编写 CSS 来修改。 20 改成你想要的大小即可。
```
.entry-content p {
    font-size: 20px;
}
```
2. 黑色框不考虑移除。主要是目录这边需要一个定位显示。
3. 如果是 PC 端右侧的返回顶部，目前可以更换图片，但无法切换其他类型。如果想要切换图片，可以在 ```主题设置 -> 其他 -> 回到顶部图片``` 中修改。你也可以通过修改 CSS 来定制化。
4. 让某些页面不显示目录的方法。 在 后台发布文章/页面时， 点击选项中的 高级选项 -> 新增元数据 -> ```key: toc, value: true/false``` 只能写 true/false，否则会报错。
![image](https://user-images.githubusercontent.com/31335418/100564021-c730a980-32fa-11eb-903f-70455e5a8e28.png)

最后关于图标，我个人本身是打算弄成 SVG 格式的，只不过目前重心没在这块。如果你有更好的建议或者想法，可以提交 PR。 非常感谢！！！

**Comment by hongcyu** [comment]
@LIlGG 收到~非常感谢你的解答，目前为了实现一些样式可能直接修改了源码，但是通过你说明的更新问题我点醒了我，我后期会注意一下的。再次感谢。

**Comment by LIlGG** [comment]
> @LIlGG 收到~非常感谢你的解答，目前为了实现一些样式可能直接修改了源码，但是通过你说明的更新问题我点醒了我，我后期会注意一下的。再次感谢。

我希望的是尽可能做到零改源码的定制化。可惜那样可能有点难度，基于条件目前只能如此实现。 另外你的社交图标感觉还是蛮好看的，如果可以希望能够提交 PR。哈哈

**Comment by hongcyu** [comment]
@LIlGG 好的，想想你询问一下，我之前修改过一些style.css ，如果在主题 ` 设置 -> 自定义 CSS ` 中添加是一样的效果嘛？

**Comment by hongcyu** [comment]
@LIlGG  好的，想想你询问一下:
1.我之前添加了一些style.css ，如果在主题 设置 -> 自定义 CSS 中添加是一样的效果嘛？
2.对于在git上进行团队合作开发我还是个萌新,目前还在研究如何push更改。如果研究好了会进行push一些图标。
3.如果我修改ftl文件也会导致更新主题的问题嘛。
4.目前是否有可能开发头像和故障文字一同出现的feture呢？
![image](https://user-images.githubusercontent.com/41502466/100574734-9f9b0a80-3315-11eb-95f4-0abf36d9e258.png)

**Comment by LIlGG** [comment]
> @LIlGG 好的，想想你询问一下:
> 1.我之前添加了一些style.css ，如果在主题 设置 -> 自定义 CSS 中添加是一样的效果嘛？
> 2.对于在git上进行团队合作开发我还是个萌新,目前还在研究如何push更改。如果研究好了会进行push一些图标。
> 3.如果我修改ftl文件也会导致更新主题的问题嘛。
> 4.目前是否有可能开发头像和故障文字一同出现的feture呢？
> ![image](https://user-images.githubusercontent.com/41502466/100574734-9f9b0a80-3315-11eb-95f4-0abf36d9e258.png)

大部分情况下，自定义 CSS 会覆盖默认 CSS，因为优先度的原因，如果遇到部分无法覆盖，直接添加 ````!important`` 即可。
修改任何文件都可能导致主题无法更新，目前 halo 是更新是采用全部覆盖的方式，无法做到类似 git 这种版本控制的功能。
故障文本和头像同时出现的话，感觉首页空间会显得很挤。

**Comment by hongcyu** [comment]
@LIlGG 
也就是说更新主题会导致主题重置是嘛？
目前我是向master提交了，但是我看见dev分支进行大幅度的修改，想询问一下我是否该向dev分支重新push？（git萌新，向这种情况大家都是往master提交还是dev提交呢？）以及目前计划什么时候会更新下一个版本？

**Comment by LIlGG** [comment]
> @LIlGG
> 也就是说更新主题会导致主题重置是嘛？
> 目前我是向master提交了，但是我看见dev分支进行大幅度的修改，想询问一下我是否该向dev分支重新push？（git萌新，向这种情况大家都是往master提交还是dev提交呢？）以及目前计划什么时候会更新下一个版本？

并不会重置，而是会直接报错无法更新。 除非你删除掉修改后的主题重新下载，否则是不能再更新主题了。 但删除的后果就是你做的改动也就跟着删除了。
正常来说是需要提交到 dev，因为 dev 版本才是下个发行版本。 如果是紧急 BUG，那么可以直接提交到 master 版本。。 你可以切换到 dev 分支，然后传到 dev 上。其实也可以提交到 master，我后续会补充到 dev 版本。

**Comment by LIlGG** [comment]
> @LIlGG
> 也就是说更新主题会导致主题重置是嘛？
> 目前我是向master提交了，但是我看见dev分支进行大幅度的修改，想询问一下我是否该向dev分支重新push？（git萌新，向这种情况大家都是往master提交还是dev提交呢？）以及目前计划什么时候会更新下一个版本？

目前的 dev 版本计划主要做如下计划：
1. 静态资源重构，便于支持用户 cdn
2. bilibili 流视频支持
3. 基于图床的随机图 API支持

应该很快就会更新下个版本了。目前接口已经实现了，正在测试阶段。

**Comment by hongcyu** [comment]
@LIlGG 作者，请问你知道菜单的下拉子菜单在哪里设置嘛...我看别人都有我真找不到设置的地方。。。
![image](https://user-images.githubusercontent.com/41502466/100608468-6a0f1500-3347-11eb-81f7-5ea8dde421ef.png)
