### ISSUE TITLE
请问主题怎么渲染mathjax公式？

### ISSUE THREAD

**Issue by barwe** [LIlGG/halo-theme-sakura#90]
预览界面能看到，但是发布之后就没了 @)_(@

**Comment by LIlGG** [comment]
emm 就如你所看到的。 目前没有支持， 之前没有用到，所以没想着弄，哈哈。。
不过既然有需求的话，我会在今天尝试支持一下，并添加到下个版本

**Comment by barwe** [comment]
感谢大佬~
