### ISSUE TITLE
怎么开启Aplayer，我找半天没找到，还是在哪里设置？

### ISSUE THREAD

**Issue by pentest404** [LIlGG/halo-theme-sakura#93]

**Comment by LIlGG** [comment]
首先确保主题设置 `插件功能 ->  开启Aplayer 插件` 处于开启状态。
然后在主题设置 `背景音乐` 里面设置 aplyer

**Comment by pentest404** [comment]
开启了，然后也设置了，但是左下角还是没有 http://lone0x0.tk/

**Comment by pentest404** [comment]
为啥换成我自已的网易云歌单id，它就不显示，而使用默认的它就可以显示，不能换成自已的歌单吗？

**Comment by pentest404** [comment]
> 首先确保主题设置 `插件功能 -> 开启Aplayer 插件` 处于开启状态。
> 然后在主题设置 `背景音乐` 里面设置 aplyer


为啥换成我自已的网易云歌单id，它就不显示，而使用默认的它就可以显示，不能换成自已的歌单吗？

**Comment by LIlGG** [comment]
> > 首先确保主题设置 `插件功能 -> 开启Aplayer 插件` 处于开启状态。
> > 然后在主题设置 `背景音乐` 里面设置 aplyer
> 
> 为啥换成我自已的网易云歌单id，它就不显示，而使用默认的它就可以显示，不能换成自已的歌单吗？

检查一下你的歌单是否是私密的。而且必须保证是歌单，不可以是其他的。
