### ISSUE TITLE
如何关闭评论

### ISSUE THREAD

**Issue by szxczyc** [LIlGG/halo-theme-sakura#94]
作者您好，主题非常nice，但是由于我需要备案，不允许出现评论，请问该如何关闭呢？

**Comment by LIlGG** [comment]
感谢支持！正好我前段时间也刚刚备案了，给你参考一下吧。【现在不支持一键隐藏，之后会考虑在主题设置里面加一个 备案选项】
目前需要隐藏的位置有如下，可能需要暂时调整一下代码，等备案结束之后还原即可。
1. 首页的列表上面的评论显示
2. 各个文章、页面的评论
3. 留言板
***
下面是具体操作方式，首先找到 后台 -> 主题编辑
1. 找到 `tpl -> content-thumb.ftl ` 文件，在第 27 行上下分别加上 `<!-- 与 --> `。如下
```
<!--
<span class="comments-number"><i class="iconfont icon-mark"></i>${post.commentCount!0} 条评论</span>
-->
```
2. 找到 `comments.flt` 文件，在 第 13 行上加上 `<!--` 在第 21 行上加上 `-->`。如下
```'
<!--
	<#if !target.disallowComment!false>
		<section id="comments" class="comments">
			<div class="comments-main">
				<h3 id="comments-list-title">Comments | <span class="noticom">${target.commentCount!0} 条评论 </span></h3>
				<halo-comment id="${target.id?c}" type="${type}" :configs="configs"/>
			</div>
		</section>
	</#if>
-->
```
3. 留言板的话属于自定义页面，在所有页面将其转换为草稿，并暂时去掉菜单的显示即可。（如果没有就不用管）

上面的方法都需要改代码，**记得备案成功之后改回来**，否则将可能无法更新主题！！！

**Comment by szxczyc** [comment]
已经修改成功了，非常感谢！
