### ISSUE TITLE
导入提示无法安装这个包。 主题缺少style.css样式表

### ISSUE THREAD

**Issue by bb281561032** [LIlGG/halo-theme-sakura#95]
导入提示无法安装这个包。 主题缺少style.css样式表

**Comment by LIlGG** [comment]
希望能够给出详细的信息或者截图。

**Comment by bb281561032** [comment]
好像我搞错了?不是wordpress导入主题吗

**Comment by LIlGG** [comment]
> 好像我搞错了?不是wordpress导入主题吗

本主题是基于 (Halo)[halo.run] CMS 进行的，不是 wordpress。 不过本主题的原版主题正好就是 wordpress 上的，你可以去看一看。
