### ISSUE TITLE
朋友圈

### ISSUE THREAD

**Issue by winsway** [LIlGG/halo-theme-sakura#96]
博主，什么时候可以支持一下朋友圈发布图片排版的功能呢？

**Comment by LIlGG** [comment]
什么朋友圈。本主题好像没有朋友圈的功能。。

**Comment by winsway** [comment]
> 什么朋友圈。本主题好像没有朋友圈的功能。。

就是心情的菜单栏目中，我看了一下这个和朋友圈的功能很相似。如果能够实现图片的有效排版就非常好了。

**Comment by LIlGG** [comment]
> > 什么朋友圈。本主题好像没有朋友圈的功能。。
> 
> 就是心情的菜单栏目中，我看了一下这个和朋友圈的功能很相似。如果能够实现图片的有效排版就非常好了。

你说的是日志界面吧。。 这个里面的内容、图片什么的，都是基于 markdown 的语法，实际上直接使用 html 改变即可。不过我想了解一下你需要怎样的排版样式

**Comment by winsway** [comment]
> > > 什么朋友圈。本主题好像没有朋友圈的功能。。
> > 
> > 
> > 就是心情的菜单栏目中，我看了一下这个和朋友圈的功能很相似。如果能够实现图片的有效排版就非常好了。
> 
> 你说的是日志界面吧。。 这个里面的内容、图片什么的，都是基于 markdown 的语法，实际上直接使用 html 改变即可。不过我想了解一下你需要怎样的排版样式

是这样的，因为现在微信朋友圈都是领导和老师，已经不太适合发表自己的生活状态，而是发表站队比较明确的公众号了。而博客相对自由一些，想记录一下自己的生活。但是有时候又不可能长篇大论，因此朋友圈的九宫格的布局，或者其它的一种布局对于心情和状态的记录应有用的。而不同的图片的大小和像素不同，极有可能产生排版难看的效果。因此希望博主能够开发出这样的新功能。

**Comment by LIlGG** [comment]
了解你的需求了。 但可能心情页的运行方式与你想的可能不一样。
对于朋友圈而言，他发表图片时是单独上传的。因此可以将所有上传的图片放在说说下面。
而对于博客内的心情页，图片是一个外链格式，因此我不会控制图片必须显示在下面，并且以九宫格的形式，也很难控制。图片该出现在哪儿，该多大，都需要写心情的时候考虑。我所能做的，是给予一个默认的图片样式，因此九宫格的方式可能不适合本主题。那样反而限制了自由。
