### ISSUE TITLE
友情链接页面出错了

### ISSUE THREAD

**Issue by Dean0731** [LIlGG/halo-theme-sakura#98]
显示500错误，错误日志如https://user-images.githubusercontent.com/37725307/103601230-2c07a100-4f44-11eb-858e-058c30eac034.png

**Comment by LIlGG** [comment]
您好，请问 使用的是什么版本的 sakura 主题？

**Comment by LIlGG** [comment]
> 显示500错误，错误日志如https://user-images.githubusercontent.com/37725307/103601230-2c07a100-4f44-11eb-858e-058c30eac034.png

刚刚看到了，确实有代码问题，已经更改，可以更新一下再试试
